// SPDX-License-Identifier: MIT
// Copyright (c) Uri Shaked and contributors
// Generated by tools/convert.cjs. Source: src/cpu/cpu.spec.ts
use crate::scenario::*;
pub const IMPORTS: &[&str] = &[r#"CPU"#];
pub fn cases() -> Vec<Case> {
    vec![
        case_001_should_set_initial_value_of_sp_to_the_last_byte_of_internal_sram(),
        case_002_should_execute_queued_events_after_the_given_number_of_cycles_has_passed(),
        case_003_should_correctly_sort_the_events_when_added_in_reverse_order(),
        case_004_should_update_the_number_of_cycles_for_the_given_clock_event(),
        case_005_should_remove_the_given_clock_event(),
        case_006_should_return_false_if_the_provided_clock_event_is_not_scheduled(),
    ]
}

fn setup_0() -> Vec<Step> {
    vec![]
}

pub fn case_001_should_set_initial_value_of_sp_to_the_last_byte_of_internal_sram() -> Case {
    Case {
        source: r#"src/cpu/cpu.spec.ts"#,
        name: r#"cpu / should set initial value of SP to the last byte of internal SRAM"#,
        line: 7,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                8,
                bind(
                    r#"cpu"#,
                    new(
                        r#"CPU"#,
                        vec![new(r#"Uint16Array"#, vec![num(1024.0)]), num(4096.0)],
                    ),
                ),
            ),
            at(
                9,
                check(
                    get(var(r#"cpu"#), text(r#"SP"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(4351.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_001_should_set_initial_value_of_sp_to_the_last_byte_of_internal_sram_native() {
    crate::run_native(case_001_should_set_initial_value_of_sp_to_the_last_byte_of_internal_sram());
}

pub fn case_002_should_execute_queued_events_after_the_given_number_of_cycles_has_passed() -> Case {
    Case {
        source: r#"src/cpu/cpu.spec.ts"#,
        name: r#"cpu / events / should execute queued events after the given number of cycles has passed"#,
        line: 13,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                14,
                bind(
                    r#"cpu"#,
                    new(
                        r#"CPU"#,
                        vec![new(r#"Uint16Array"#, vec![num(1024.0)]), num(4096.0)],
                    ),
                ),
            ),
            at(15, bind(r#"events"#, array(vec![]))),
            at(
                16,
                for_of(
                    r#"i"#,
                    array(vec![num(1.0), num(4.0), num(10.0)]),
                    vec![at(
                        17,
                        eval(call(
                            get(var(r#"cpu"#), text(r#"addClockEvent"#)),
                            vec![
                                function(
                                    vec![],
                                    vec![at(
                                        17,
                                        ret(call(
                                            get(var(r#"events"#), text(r#"push"#)),
                                            vec![array(vec![
                                                var(r#"i"#),
                                                get(var(r#"cpu"#), text(r#"cycles"#)),
                                            ])],
                                        )),
                                    )],
                                ),
                                var(r#"i"#),
                            ],
                        )),
                    )],
                ),
            ),
            at(
                19,
                for_(
                    vec![at(19, bind(r#"i"#, num(0.0)))],
                    binary(r#"<"#, var(r#"i"#), num(10.0)),
                    update(var(r#"i"#), 1, false),
                    vec![
                        at(
                            20,
                            eval(update(get(var(r#"cpu"#), text(r#"cycles"#)), 1, false)),
                        ),
                        at(21, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
                    ],
                ),
            ),
            at(
                23,
                check(
                    var(r#"events"#),
                    r#"toEqual"#,
                    false,
                    vec![array(vec![
                        array(vec![num(1.0), num(1.0)]),
                        array(vec![num(4.0), num(4.0)]),
                        array(vec![num(10.0), num(10.0)]),
                    ])],
                ),
            ),
        ],
    }
}
#[test]
fn case_002_should_execute_queued_events_after_the_given_number_of_cycles_has_passed_native() {
    crate::run_native(
        case_002_should_execute_queued_events_after_the_given_number_of_cycles_has_passed(),
    );
}

pub fn case_003_should_correctly_sort_the_events_when_added_in_reverse_order() -> Case {
    Case {
        source: r#"src/cpu/cpu.spec.ts"#,
        name: r#"cpu / events / should correctly sort the events when added in reverse order"#,
        line: 30,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                31,
                bind(
                    r#"cpu"#,
                    new(
                        r#"CPU"#,
                        vec![new(r#"Uint16Array"#, vec![num(1024.0)]), num(4096.0)],
                    ),
                ),
            ),
            at(32, bind(r#"events"#, array(vec![]))),
            at(
                33,
                for_of(
                    r#"i"#,
                    array(vec![num(10.0), num(4.0), num(1.0)]),
                    vec![at(
                        34,
                        eval(call(
                            get(var(r#"cpu"#), text(r#"addClockEvent"#)),
                            vec![
                                function(
                                    vec![],
                                    vec![at(
                                        34,
                                        ret(call(
                                            get(var(r#"events"#), text(r#"push"#)),
                                            vec![array(vec![
                                                var(r#"i"#),
                                                get(var(r#"cpu"#), text(r#"cycles"#)),
                                            ])],
                                        )),
                                    )],
                                ),
                                var(r#"i"#),
                            ],
                        )),
                    )],
                ),
            ),
            at(
                36,
                for_(
                    vec![at(36, bind(r#"i"#, num(0.0)))],
                    binary(r#"<"#, var(r#"i"#), num(10.0)),
                    update(var(r#"i"#), 1, false),
                    vec![
                        at(
                            37,
                            eval(update(get(var(r#"cpu"#), text(r#"cycles"#)), 1, false)),
                        ),
                        at(38, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
                    ],
                ),
            ),
            at(
                40,
                check(
                    var(r#"events"#),
                    r#"toEqual"#,
                    false,
                    vec![array(vec![
                        array(vec![num(1.0), num(1.0)]),
                        array(vec![num(4.0), num(4.0)]),
                        array(vec![num(10.0), num(10.0)]),
                    ])],
                ),
            ),
        ],
    }
}
#[test]
fn case_003_should_correctly_sort_the_events_when_added_in_reverse_order_native() {
    crate::run_native(case_003_should_correctly_sort_the_events_when_added_in_reverse_order());
}

pub fn case_004_should_update_the_number_of_cycles_for_the_given_clock_event() -> Case {
    Case {
        source: r#"src/cpu/cpu.spec.ts"#,
        name: r#"cpu / events / updateClockEvent / should update the number of cycles for the given clock event"#,
        line: 48,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                49,
                bind(
                    r#"cpu"#,
                    new(
                        r#"CPU"#,
                        vec![new(r#"Uint16Array"#, vec![num(1024.0)]), num(4096.0)],
                    ),
                ),
            ),
            at(50, bind(r#"events"#, array(vec![]))),
            at(51, bind(r#"callbacks"#, array(vec![]))),
            at(
                52,
                for_of(
                    r#"i"#,
                    array(vec![num(1.0), num(4.0), num(10.0)]),
                    vec![at(
                        53,
                        eval(assign(
                            get(var(r#"callbacks"#), var(r#"i"#)),
                            call(
                                get(var(r#"cpu"#), text(r#"addClockEvent"#)),
                                vec![
                                    function(
                                        vec![],
                                        vec![at(
                                            53,
                                            ret(call(
                                                get(var(r#"events"#), text(r#"push"#)),
                                                vec![array(vec![
                                                    var(r#"i"#),
                                                    get(var(r#"cpu"#), text(r#"cycles"#)),
                                                ])],
                                            )),
                                        )],
                                    ),
                                    var(r#"i"#),
                                ],
                            ),
                            r#"="#,
                        )),
                    )],
                ),
            ),
            at(
                55,
                eval(call(
                    get(var(r#"cpu"#), text(r#"updateClockEvent"#)),
                    vec![get(var(r#"callbacks"#), num(4.0)), num(2.0)],
                )),
            ),
            at(
                56,
                eval(call(
                    get(var(r#"cpu"#), text(r#"updateClockEvent"#)),
                    vec![get(var(r#"callbacks"#), num(1.0)), num(12.0)],
                )),
            ),
            at(
                57,
                for_(
                    vec![at(57, bind(r#"i"#, num(0.0)))],
                    binary(r#"<"#, var(r#"i"#), num(14.0)),
                    update(var(r#"i"#), 1, false),
                    vec![
                        at(
                            58,
                            eval(update(get(var(r#"cpu"#), text(r#"cycles"#)), 1, false)),
                        ),
                        at(59, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
                    ],
                ),
            ),
            at(
                61,
                check(
                    var(r#"events"#),
                    r#"toEqual"#,
                    false,
                    vec![array(vec![
                        array(vec![num(4.0), num(2.0)]),
                        array(vec![num(10.0), num(10.0)]),
                        array(vec![num(1.0), num(12.0)]),
                    ])],
                ),
            ),
        ],
    }
}
#[test]
fn case_004_should_update_the_number_of_cycles_for_the_given_clock_event_native() {
    crate::run_native(case_004_should_update_the_number_of_cycles_for_the_given_clock_event());
}

pub fn case_005_should_remove_the_given_clock_event() -> Case {
    Case {
        source: r#"src/cpu/cpu.spec.ts"#,
        name: r#"cpu / events / updateClockEvent / clearClockEvent / should remove the given clock event"#,
        line: 69,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                70,
                bind(
                    r#"cpu"#,
                    new(
                        r#"CPU"#,
                        vec![new(r#"Uint16Array"#, vec![num(1024.0)]), num(4096.0)],
                    ),
                ),
            ),
            at(71, bind(r#"events"#, array(vec![]))),
            at(72, bind(r#"callbacks"#, array(vec![]))),
            at(
                73,
                for_of(
                    r#"i"#,
                    array(vec![num(1.0), num(4.0), num(10.0)]),
                    vec![at(
                        74,
                        eval(assign(
                            get(var(r#"callbacks"#), var(r#"i"#)),
                            call(
                                get(var(r#"cpu"#), text(r#"addClockEvent"#)),
                                vec![
                                    function(
                                        vec![],
                                        vec![at(
                                            74,
                                            ret(call(
                                                get(var(r#"events"#), text(r#"push"#)),
                                                vec![array(vec![
                                                    var(r#"i"#),
                                                    get(var(r#"cpu"#), text(r#"cycles"#)),
                                                ])],
                                            )),
                                        )],
                                    ),
                                    var(r#"i"#),
                                ],
                            ),
                            r#"="#,
                        )),
                    )],
                ),
            ),
            at(
                76,
                eval(call(
                    get(var(r#"cpu"#), text(r#"clearClockEvent"#)),
                    vec![get(var(r#"callbacks"#), num(4.0))],
                )),
            ),
            at(
                77,
                for_(
                    vec![at(77, bind(r#"i"#, num(0.0)))],
                    binary(r#"<"#, var(r#"i"#), num(10.0)),
                    update(var(r#"i"#), 1, false),
                    vec![
                        at(
                            78,
                            eval(update(get(var(r#"cpu"#), text(r#"cycles"#)), 1, false)),
                        ),
                        at(79, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
                    ],
                ),
            ),
            at(
                81,
                check(
                    var(r#"events"#),
                    r#"toEqual"#,
                    false,
                    vec![array(vec![
                        array(vec![num(1.0), num(1.0)]),
                        array(vec![num(10.0), num(10.0)]),
                    ])],
                ),
            ),
        ],
    }
}
#[test]
fn case_005_should_remove_the_given_clock_event_native() {
    crate::run_native(case_005_should_remove_the_given_clock_event());
}

pub fn case_006_should_return_false_if_the_provided_clock_event_is_not_scheduled() -> Case {
    Case {
        source: r#"src/cpu/cpu.spec.ts"#,
        name: r#"cpu / events / updateClockEvent / clearClockEvent / should return false if the provided clock event is not scheduled"#,
        line: 87,
        assertions: 4,
        setup: setup_0(),
        body: vec![
            at(
                88,
                bind(
                    r#"cpu"#,
                    new(
                        r#"CPU"#,
                        vec![new(r#"Uint16Array"#, vec![num(1024.0)]), num(4096.0)],
                    ),
                ),
            ),
            at(
                89,
                bind(
                    r#"event4"#,
                    call(
                        get(var(r#"cpu"#), text(r#"addClockEvent"#)),
                        vec![function(vec![], vec![at(89, ret(num(0.0)))]), num(4.0)],
                    ),
                ),
            ),
            at(
                90,
                bind(
                    r#"event10"#,
                    call(
                        get(var(r#"cpu"#), text(r#"addClockEvent"#)),
                        vec![function(vec![], vec![at(90, ret(num(0.0)))]), num(10.0)],
                    ),
                ),
            ),
            at(
                91,
                eval(call(
                    get(var(r#"cpu"#), text(r#"addClockEvent"#)),
                    vec![function(vec![], vec![at(91, ret(num(0.0)))]), num(1.0)],
                )),
            ),
            at(
                94,
                check(
                    call(
                        get(var(r#"cpu"#), text(r#"clearClockEvent"#)),
                        vec![var(r#"event4"#)],
                    ),
                    r#"toBe"#,
                    false,
                    vec![boolean(true)],
                ),
            ),
            at(
                95,
                check(
                    call(
                        get(var(r#"cpu"#), text(r#"clearClockEvent"#)),
                        vec![var(r#"event10"#)],
                    ),
                    r#"toBe"#,
                    false,
                    vec![boolean(true)],
                ),
            ),
            at(
                97,
                check(
                    call(
                        get(var(r#"cpu"#), text(r#"clearClockEvent"#)),
                        vec![var(r#"event4"#)],
                    ),
                    r#"toBe"#,
                    false,
                    vec![boolean(false)],
                ),
            ),
            at(
                98,
                check(
                    call(
                        get(var(r#"cpu"#), text(r#"clearClockEvent"#)),
                        vec![var(r#"event10"#)],
                    ),
                    r#"toBe"#,
                    false,
                    vec![boolean(false)],
                ),
            ),
        ],
    }
}
#[test]
fn case_006_should_return_false_if_the_provided_clock_event_is_not_scheduled_native() {
    crate::run_native(case_006_should_return_false_if_the_provided_clock_event_is_not_scheduled());
}
