// SPDX-License-Identifier: MIT
// Copyright (c) Uri Shaked and contributors
// Generated by tools/convert.cjs. Source: src/cpu/interrupt.spec.ts
use crate::scenario::*;
pub const IMPORTS: &[&str] = &[r#"CPU"#, r#"avrInterrupt"#];
pub fn cases() -> Vec<Case> {
    vec![
        case_001_should_execute_interrupt_handler(),
        case_002_should_push_a_3_byte_return_address_when_running_in_22_bit_pc_mode_issue_58(),
    ]
}

fn setup_0() -> Vec<Step> {
    vec![]
}

pub fn case_001_should_execute_interrupt_handler() -> Case {
    Case {
        source: r#"src/cpu/interrupt.spec.ts"#,
        name: r#"avrInterrupt / should execute interrupt handler"#,
        line: 9,
        assertions: 6,
        setup: setup_0(),
        body: vec![
            at(
                10,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(32768.0)])]),
                ),
            ),
            at(
                11,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"pc"#)),
                    num(1312.0),
                    r#"="#,
                )),
            ),
            at(
                12,
                eval(assign(
                    get(get(var(r#"cpu"#), text(r#"data"#)), num(94.0)),
                    num(0.0),
                    r#"="#,
                )),
            ),
            at(
                13,
                eval(assign(
                    get(get(var(r#"cpu"#), text(r#"data"#)), num(93.0)),
                    num(128.0),
                    r#"="#,
                )),
            ),
            at(
                14,
                eval(assign(
                    get(get(var(r#"cpu"#), text(r#"data"#)), num(95.0)),
                    num(129.0),
                    r#"="#,
                )),
            ),
            at(
                15,
                eval(call(var(r#"avrInterrupt"#), vec![var(r#"cpu"#), num(5.0)])),
            ),
            at(
                16,
                check(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(2.0)],
                ),
            ),
            at(
                17,
                check(
                    get(var(r#"cpu"#), text(r#"pc"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(5.0)],
                ),
            ),
            at(
                18,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), num(93.0)),
                    r#"toEqual"#,
                    false,
                    vec![num(126.0)],
                ),
            ),
            at(
                19,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), num(128.0)),
                    r#"toEqual"#,
                    false,
                    vec![num(32.0)],
                ),
            ),
            at(
                20,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), num(127.0)),
                    r#"toEqual"#,
                    false,
                    vec![num(5.0)],
                ),
            ),
            at(
                21,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), num(95.0)),
                    r#"toEqual"#,
                    false,
                    vec![num(1.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_001_should_execute_interrupt_handler_native() {
    crate::run_native(case_001_should_execute_interrupt_handler());
}

pub fn case_002_should_push_a_3_byte_return_address_when_running_in_22_bit_pc_mode_issue_58() -> Case
{
    Case {
        source: r#"src/cpu/interrupt.spec.ts"#,
        name: r#"avrInterrupt / should push a 3-byte return address when running in 22-bit PC mode (issue #58)"#,
        line: 24,
        assertions: 8,
        setup: setup_0(),
        body: vec![
            at(
                25,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(524288.0)])]),
                ),
            ),
            at(
                26,
                check(
                    get(var(r#"cpu"#), text(r#"pc22Bits"#)),
                    r#"toEqual"#,
                    false,
                    vec![boolean(true)],
                ),
            ),
            at(
                28,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"pc"#)),
                    num(66848.0),
                    r#"="#,
                )),
            ),
            at(
                29,
                eval(assign(
                    get(get(var(r#"cpu"#), text(r#"data"#)), num(94.0)),
                    num(0.0),
                    r#"="#,
                )),
            ),
            at(
                30,
                eval(assign(
                    get(get(var(r#"cpu"#), text(r#"data"#)), num(93.0)),
                    num(128.0),
                    r#"="#,
                )),
            ),
            at(
                31,
                eval(assign(
                    get(get(var(r#"cpu"#), text(r#"data"#)), num(95.0)),
                    num(129.0),
                    r#"="#,
                )),
            ),
            at(
                33,
                eval(call(var(r#"avrInterrupt"#), vec![var(r#"cpu"#), num(5.0)])),
            ),
            at(
                34,
                check(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(2.0)],
                ),
            ),
            at(
                35,
                check(
                    get(var(r#"cpu"#), text(r#"pc"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(5.0)],
                ),
            ),
            at(
                36,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), num(93.0)),
                    r#"toEqual"#,
                    false,
                    vec![num(125.0)],
                ),
            ),
            at(
                37,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), num(128.0)),
                    r#"toEqual"#,
                    false,
                    vec![num(32.0)],
                ),
            ),
            at(
                38,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), num(127.0)),
                    r#"toEqual"#,
                    false,
                    vec![num(5.0)],
                ),
            ),
            at(
                39,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), num(126.0)),
                    r#"toEqual"#,
                    false,
                    vec![num(1.0)],
                ),
            ),
            at(
                40,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), num(95.0)),
                    r#"toEqual"#,
                    false,
                    vec![num(1.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_002_should_push_a_3_byte_return_address_when_running_in_22_bit_pc_mode_issue_58_native() {
    crate::run_native(
        case_002_should_push_a_3_byte_return_address_when_running_in_22_bit_pc_mode_issue_58(),
    );
}
