// Generated by tools/convert.cjs.
pub mod cpu_cpu;
pub mod cpu_instruction;
pub mod cpu_interrupt;
pub mod peripherals_adc;
pub mod peripherals_clock;
pub mod peripherals_eeprom;
pub mod peripherals_gpio;
pub mod peripherals_spi;
pub mod peripherals_timer;
pub mod peripherals_timer_attiny;
pub mod peripherals_twi;
pub mod peripherals_usart;
pub mod peripherals_watchdog;
pub mod utils_assembler;
pub fn all_cases() -> Vec<crate::Case> {
    let mut result = Vec::new();
    result.extend(cpu_cpu::cases());
    result.extend(cpu_instruction::cases());
    result.extend(cpu_interrupt::cases());
    result.extend(peripherals_adc::cases());
    result.extend(peripherals_clock::cases());
    result.extend(peripherals_eeprom::cases());
    result.extend(peripherals_gpio::cases());
    result.extend(peripherals_spi::cases());
    result.extend(peripherals_timer_attiny::cases());
    result.extend(peripherals_timer::cases());
    result.extend(peripherals_twi::cases());
    result.extend(peripherals_usart::cases());
    result.extend(peripherals_watchdog::cases());
    result.extend(utils_assembler::cases());
    result
}
