// SPDX-License-Identifier: MIT
// Copyright (c) Uri Shaked and contributors
// Generated by tools/convert.cjs. Source: src/peripherals/timer-attiny.spec.ts
use crate::scenario::*;
pub const IMPORTS: &[&str] = &[
    r#"CPU"#,
    r#"AVRIOPort"#,
    r#"ATtinyTimer1"#,
    r#"attinyTimer1Config"#,
];
pub fn cases() -> Vec<Case> {
    vec![
        case_001_should_update_timer_every_tick_when_prescaler_is_1_cs_1(),
        case_002_should_update_timer_every_128_ticks_when_prescaler_is_128_cs_8(),
        case_003_should_not_update_timer_when_disabled_cs_0(),
        case_004_should_clear_timer_on_ocr1c_match_when_ctc1_is_set(),
        case_005_should_set_tov1_when_timer_overflows_past_ocr1c(),
        case_006_should_set_ocf1a_when_timer_matches_ocr1a(),
        case_007_should_set_ocf1b_when_timer_matches_ocr1b(),
        case_008_should_fire_compa_interrupt_when_enabled(),
        case_009_should_overflow_after_a_full_period_with_prescaler_128(),
        case_010_should_clear_tov1_by_writing_1_to_tifr(),
    ]
}

fn setup_0() -> Vec<Step> {
    vec![
        at(
            9,
            bind(
                r#"attinyPortB"#,
                object(vec![
                    entry(r#"PIN"#, num(54.0)),
                    entry(r#"DDR"#, num(55.0)),
                    entry(r#"PORT"#, num(56.0)),
                    entry(r#"externalInterrupts"#, array(vec![])),
                ]),
            ),
        ),
        at(
            16,
            bind(
                r#"TCCR1"#,
                get(var(r#"attinyTimer1Config"#), text(r#"TCCR1"#)),
            ),
        ),
        at(
            17,
            bind(
                r#"TCNT1"#,
                get(var(r#"attinyTimer1Config"#), text(r#"TCNT1"#)),
            ),
        ),
        at(
            18,
            bind(
                r#"OCR1A"#,
                get(var(r#"attinyTimer1Config"#), text(r#"OCR1A"#)),
            ),
        ),
        at(
            19,
            bind(
                r#"OCR1B"#,
                get(var(r#"attinyTimer1Config"#), text(r#"OCR1B"#)),
            ),
        ),
        at(
            20,
            bind(
                r#"OCR1C"#,
                get(var(r#"attinyTimer1Config"#), text(r#"OCR1C"#)),
            ),
        ),
        at(
            21,
            bind(
                r#"TIFR"#,
                get(var(r#"attinyTimer1Config"#), text(r#"TIFR"#)),
            ),
        ),
        at(
            22,
            bind(
                r#"TIMSK"#,
                get(var(r#"attinyTimer1Config"#), text(r#"TIMSK"#)),
            ),
        ),
        at(
            24,
            bind(
                r#"TOV1"#,
                get(var(r#"attinyTimer1Config"#), text(r#"TOV1"#)),
            ),
        ),
        at(
            25,
            bind(
                r#"OCF1A"#,
                get(var(r#"attinyTimer1Config"#), text(r#"OCF1A"#)),
            ),
        ),
        at(
            26,
            bind(
                r#"OCF1B"#,
                get(var(r#"attinyTimer1Config"#), text(r#"OCF1B"#)),
            ),
        ),
        at(
            27,
            bind(
                r#"OCIE1A"#,
                get(var(r#"attinyTimer1Config"#), text(r#"OCIE1A"#)),
            ),
        ),
        at(29, bind(r#"CTC1"#, binary(r#"<<"#, num(1.0), num(7.0)))),
        at(30, bind(r#"CS10"#, num(1.0))),
        at(31, bind(r#"CS13"#, binary(r#"<<"#, num(1.0), num(3.0)))),
        at(33, bind(r#"SREG"#, num(95.0))),
        at(
            35,
            bind(
                r#"createTimer"#,
                function(
                    vec![],
                    vec![
                        at(
                            36,
                            bind(
                                r#"cpu"#,
                                new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(4096.0)])]),
                            ),
                        ),
                        at(
                            37,
                            eval(new(
                                r#"AVRIOPort"#,
                                vec![var(r#"cpu"#), var(r#"attinyPortB"#)],
                            )),
                        ),
                        at(
                            38,
                            bind(
                                r#"timer"#,
                                new(
                                    r#"ATtinyTimer1"#,
                                    vec![var(r#"cpu"#), var(r#"attinyTimer1Config"#)],
                                ),
                            ),
                        ),
                        at(
                            39,
                            ret(object(vec![
                                entry(r#"cpu"#, var(r#"cpu"#)),
                                entry(r#"timer"#, var(r#"timer"#)),
                            ])),
                        ),
                    ],
                ),
            ),
        ),
    ]
}

pub fn case_001_should_update_timer_every_tick_when_prescaler_is_1_cs_1() -> Case {
    Case {
        source: r#"src/peripherals/timer-attiny.spec.ts"#,
        name: r#"ATtiny Timer1 / should update timer every tick when prescaler is 1 (CS=1)"#,
        line: 43,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                44,
                destructure(
                    vec![(r#"cpu"#, r#"cpu"#)],
                    call(var(r#"createTimer"#), vec![]),
                ),
            ),
            at(
                45,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"TCCR1"#), var(r#"CS10"#)],
                )),
            ),
            at(
                46,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(1.0),
                    r#"="#,
                )),
            ),
            at(47, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                48,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(2.0),
                    r#"="#,
                )),
            ),
            at(49, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                50,
                check(
                    call(
                        get(var(r#"cpu"#), text(r#"readData"#)),
                        vec![var(r#"TCNT1"#)],
                    ),
                    r#"toEqual"#,
                    false,
                    vec![num(1.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_001_should_update_timer_every_tick_when_prescaler_is_1_cs_1_native() {
    crate::run_native(case_001_should_update_timer_every_tick_when_prescaler_is_1_cs_1());
}

pub fn case_002_should_update_timer_every_128_ticks_when_prescaler_is_128_cs_8() -> Case {
    Case {
        source: r#"src/peripherals/timer-attiny.spec.ts"#,
        name: r#"ATtiny Timer1 / should update timer every 128 ticks when prescaler is 128 (CS=8)"#,
        line: 53,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                54,
                destructure(
                    vec![(r#"cpu"#, r#"cpu"#)],
                    call(var(r#"createTimer"#), vec![]),
                ),
            ),
            at(
                55,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"TCCR1"#), var(r#"CS13"#)],
                )),
            ),
            at(
                56,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(1.0),
                    r#"="#,
                )),
            ),
            at(57, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                58,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    binary(r#"+"#, num(1.0), num(128.0)),
                    r#"="#,
                )),
            ),
            at(59, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                60,
                check(
                    call(
                        get(var(r#"cpu"#), text(r#"readData"#)),
                        vec![var(r#"TCNT1"#)],
                    ),
                    r#"toEqual"#,
                    false,
                    vec![num(1.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_002_should_update_timer_every_128_ticks_when_prescaler_is_128_cs_8_native() {
    crate::run_native(case_002_should_update_timer_every_128_ticks_when_prescaler_is_128_cs_8());
}

pub fn case_003_should_not_update_timer_when_disabled_cs_0() -> Case {
    Case {
        source: r#"src/peripherals/timer-attiny.spec.ts"#,
        name: r#"ATtiny Timer1 / should not update timer when disabled (CS=0)"#,
        line: 63,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                64,
                destructure(
                    vec![(r#"cpu"#, r#"cpu"#)],
                    call(var(r#"createTimer"#), vec![]),
                ),
            ),
            at(
                65,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"TCCR1"#), num(0.0)],
                )),
            ),
            at(
                66,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(100000.0),
                    r#"="#,
                )),
            ),
            at(67, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                68,
                check(
                    call(
                        get(var(r#"cpu"#), text(r#"readData"#)),
                        vec![var(r#"TCNT1"#)],
                    ),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_003_should_not_update_timer_when_disabled_cs_0_native() {
    crate::run_native(case_003_should_not_update_timer_when_disabled_cs_0());
}

pub fn case_004_should_clear_timer_on_ocr1c_match_when_ctc1_is_set() -> Case {
    Case {
        source: r#"src/peripherals/timer-attiny.spec.ts"#,
        name: r#"ATtiny Timer1 / CTC mode / should clear timer on OCR1C match when CTC1 is set"#,
        line: 72,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                73,
                destructure(
                    vec![(r#"cpu"#, r#"cpu"#)],
                    call(var(r#"createTimer"#), vec![]),
                ),
            ),
            at(
                74,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"OCR1C"#), num(9.0)],
                )),
            ),
            at(
                75,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"TCCR1"#),
                        binary(r#"|"#, var(r#"CTC1"#), var(r#"CS10"#)),
                    ],
                )),
            ),
            at(
                76,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"TCNT1"#), num(8.0)],
                )),
            ),
            at(
                77,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(1.0),
                    r#"="#,
                )),
            ),
            at(78, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                79,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    binary(r#"+"#, num(1.0), num(3.0)),
                    r#"="#,
                )),
            ),
            at(80, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                81,
                check(
                    call(
                        get(var(r#"cpu"#), text(r#"readData"#)),
                        vec![var(r#"TCNT1"#)],
                    ),
                    r#"toEqual"#,
                    false,
                    vec![num(1.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_004_should_clear_timer_on_ocr1c_match_when_ctc1_is_set_native() {
    crate::run_native(case_004_should_clear_timer_on_ocr1c_match_when_ctc1_is_set());
}

pub fn case_005_should_set_tov1_when_timer_overflows_past_ocr1c() -> Case {
    Case {
        source: r#"src/peripherals/timer-attiny.spec.ts"#,
        name: r#"ATtiny Timer1 / CTC mode / should set TOV1 when timer overflows past OCR1C"#,
        line: 84,
        assertions: 2,
        setup: setup_0(),
        body: vec![
            at(
                85,
                destructure(
                    vec![(r#"cpu"#, r#"cpu"#)],
                    call(var(r#"createTimer"#), vec![]),
                ),
            ),
            at(
                86,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"OCR1C"#), num(9.0)],
                )),
            ),
            at(
                87,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"TCNT1"#), num(9.0)],
                )),
            ),
            at(
                88,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"TCCR1"#),
                        binary(r#"|"#, var(r#"CTC1"#), var(r#"CS10"#)),
                    ],
                )),
            ),
            at(
                89,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(1.0),
                    r#"="#,
                )),
            ),
            at(90, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                91,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(2.0),
                    r#"="#,
                )),
            ),
            at(92, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                93,
                check(
                    call(
                        get(var(r#"cpu"#), text(r#"readData"#)),
                        vec![var(r#"TCNT1"#)],
                    ),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
            at(
                94,
                check(
                    binary(
                        r#"&"#,
                        get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"TIFR"#)),
                        var(r#"TOV1"#),
                    ),
                    r#"toEqual"#,
                    false,
                    vec![var(r#"TOV1"#)],
                ),
            ),
        ],
    }
}
#[test]
fn case_005_should_set_tov1_when_timer_overflows_past_ocr1c_native() {
    crate::run_native(case_005_should_set_tov1_when_timer_overflows_past_ocr1c());
}

pub fn case_006_should_set_ocf1a_when_timer_matches_ocr1a() -> Case {
    Case {
        source: r#"src/peripherals/timer-attiny.spec.ts"#,
        name: r#"ATtiny Timer1 / CTC mode / should set OCF1A when timer matches OCR1A"#,
        line: 97,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                98,
                destructure(
                    vec![(r#"cpu"#, r#"cpu"#)],
                    call(var(r#"createTimer"#), vec![]),
                ),
            ),
            at(
                99,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"OCR1C"#), num(249.0)],
                )),
            ),
            at(
                100,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"OCR1A"#), num(5.0)],
                )),
            ),
            at(
                101,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"TCCR1"#),
                        binary(r#"|"#, var(r#"CTC1"#), var(r#"CS10"#)),
                    ],
                )),
            ),
            at(
                102,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"TCNT1"#), num(4.0)],
                )),
            ),
            at(
                103,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(1.0),
                    r#"="#,
                )),
            ),
            at(104, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                105,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(3.0),
                    r#"="#,
                )),
            ),
            at(106, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                107,
                check(
                    binary(
                        r#"&"#,
                        get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"TIFR"#)),
                        var(r#"OCF1A"#),
                    ),
                    r#"toEqual"#,
                    false,
                    vec![var(r#"OCF1A"#)],
                ),
            ),
        ],
    }
}
#[test]
fn case_006_should_set_ocf1a_when_timer_matches_ocr1a_native() {
    crate::run_native(case_006_should_set_ocf1a_when_timer_matches_ocr1a());
}

pub fn case_007_should_set_ocf1b_when_timer_matches_ocr1b() -> Case {
    Case {
        source: r#"src/peripherals/timer-attiny.spec.ts"#,
        name: r#"ATtiny Timer1 / CTC mode / should set OCF1B when timer matches OCR1B"#,
        line: 110,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                111,
                destructure(
                    vec![(r#"cpu"#, r#"cpu"#)],
                    call(var(r#"createTimer"#), vec![]),
                ),
            ),
            at(
                112,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"OCR1C"#), num(249.0)],
                )),
            ),
            at(
                113,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"OCR1B"#), num(10.0)],
                )),
            ),
            at(
                114,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"TCCR1"#),
                        binary(r#"|"#, var(r#"CTC1"#), var(r#"CS10"#)),
                    ],
                )),
            ),
            at(
                115,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"TCNT1"#), num(9.0)],
                )),
            ),
            at(
                116,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(1.0),
                    r#"="#,
                )),
            ),
            at(117, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                118,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(3.0),
                    r#"="#,
                )),
            ),
            at(119, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                120,
                check(
                    binary(
                        r#"&"#,
                        get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"TIFR"#)),
                        var(r#"OCF1B"#),
                    ),
                    r#"toEqual"#,
                    false,
                    vec![var(r#"OCF1B"#)],
                ),
            ),
        ],
    }
}
#[test]
fn case_007_should_set_ocf1b_when_timer_matches_ocr1b_native() {
    crate::run_native(case_007_should_set_ocf1b_when_timer_matches_ocr1b());
}

pub fn case_008_should_fire_compa_interrupt_when_enabled() -> Case {
    Case {
        source: r#"src/peripherals/timer-attiny.spec.ts"#,
        name: r#"ATtiny Timer1 / CTC mode / should fire COMPA interrupt when enabled"#,
        line: 123,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                124,
                destructure(
                    vec![(r#"cpu"#, r#"cpu"#)],
                    call(var(r#"createTimer"#), vec![]),
                ),
            ),
            at(
                125,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"OCR1C"#), num(249.0)],
                )),
            ),
            at(
                126,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"OCR1A"#), num(0.0)],
                )),
            ),
            at(
                127,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"TCCR1"#),
                        binary(r#"|"#, var(r#"CTC1"#), var(r#"CS10"#)),
                    ],
                )),
            ),
            at(
                128,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"TCNT1"#), num(248.0)],
                )),
            ),
            at(
                129,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"TIMSK"#), var(r#"OCIE1A"#)],
                )),
            ),
            at(
                130,
                eval(assign(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"SREG"#)),
                    num(128.0),
                    r#"="#,
                )),
            ),
            at(
                131,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(1.0),
                    r#"="#,
                )),
            ),
            at(132, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                133,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(3.0),
                    r#"="#,
                )),
            ),
            at(134, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                135,
                check(
                    get(var(r#"cpu"#), text(r#"pc"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(3.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_008_should_fire_compa_interrupt_when_enabled_native() {
    crate::run_native(case_008_should_fire_compa_interrupt_when_enabled());
}

pub fn case_009_should_overflow_after_a_full_period_with_prescaler_128() -> Case {
    Case {
        source: r#"src/peripherals/timer-attiny.spec.ts"#,
        name: r#"ATtiny Timer1 / CTC mode / should overflow after a full period with prescaler 128"#,
        line: 138,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                139,
                destructure(
                    vec![(r#"cpu"#, r#"cpu"#)],
                    call(var(r#"createTimer"#), vec![]),
                ),
            ),
            at(
                140,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"TCCR1"#),
                        binary(r#"|"#, var(r#"CTC1"#), var(r#"CS13"#)),
                    ],
                )),
            ),
            at(
                141,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"OCR1C"#), num(249.0)],
                )),
            ),
            at(
                142,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"TIMSK"#), var(r#"OCIE1A"#)],
                )),
            ),
            at(
                143,
                eval(assign(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"SREG"#)),
                    num(128.0),
                    r#"="#,
                )),
            ),
            at(
                146,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(1.0),
                    r#"="#,
                )),
            ),
            at(147, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                148,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(32001.0),
                    r#"="#,
                )),
            ),
            at(149, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                151,
                check(
                    binary(
                        r#"&"#,
                        get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"TIFR"#)),
                        var(r#"TOV1"#),
                    ),
                    r#"toEqual"#,
                    true,
                    vec![num(0.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_009_should_overflow_after_a_full_period_with_prescaler_128_native() {
    crate::run_native(case_009_should_overflow_after_a_full_period_with_prescaler_128());
}

pub fn case_010_should_clear_tov1_by_writing_1_to_tifr() -> Case {
    Case {
        source: r#"src/peripherals/timer-attiny.spec.ts"#,
        name: r#"ATtiny Timer1 / clearing interrupt flags / should clear TOV1 by writing 1 to TIFR"#,
        line: 156,
        assertions: 2,
        setup: setup_0(),
        body: vec![
            at(
                157,
                destructure(
                    vec![(r#"cpu"#, r#"cpu"#)],
                    call(var(r#"createTimer"#), vec![]),
                ),
            ),
            at(
                158,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"OCR1C"#), num(9.0)],
                )),
            ),
            at(
                159,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"TCNT1"#), num(9.0)],
                )),
            ),
            at(
                160,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"TCCR1"#),
                        binary(r#"|"#, var(r#"CTC1"#), var(r#"CS10"#)),
                    ],
                )),
            ),
            at(
                161,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(1.0),
                    r#"="#,
                )),
            ),
            at(162, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                163,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(2.0),
                    r#"="#,
                )),
            ),
            at(164, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                165,
                check(
                    binary(
                        r#"&"#,
                        get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"TIFR"#)),
                        var(r#"TOV1"#),
                    ),
                    r#"toEqual"#,
                    false,
                    vec![var(r#"TOV1"#)],
                ),
            ),
            at(
                166,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"TIFR"#), var(r#"TOV1"#)],
                )),
            ),
            at(
                167,
                check(
                    binary(
                        r#"&"#,
                        get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"TIFR"#)),
                        var(r#"TOV1"#),
                    ),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_010_should_clear_tov1_by_writing_1_to_tifr_native() {
    crate::run_native(case_010_should_clear_tov1_by_writing_1_to_tifr());
}
