// SPDX-License-Identifier: MIT
// Copyright (c) Uri Shaked and contributors
// Generated by tools/convert.cjs. Source: src/peripherals/gpio.spec.ts
use crate::scenario::*;
pub const IMPORTS: &[&str] = &[
    r#"CPU"#,
    r#"asmProgram"#,
    r#"TestProgramRunner"#,
    r#"AVRIOPort"#,
    r#"PinOverrideMode"#,
    r#"PinState"#,
    r#"portBConfig"#,
    r#"portDConfig"#,
];
pub fn cases() -> Vec<Case> {
    vec![case_001_should_invoke_the_listeners_when_the_port_is_written_to(),case_002_should_invoke_the_listeners_when_ddr_changes_issue_28(),case_003_should_invoke_the_listeners_when_pullup_register_enabled_issue_62(),case_004_should_toggle_the_pin_when_writing_to_the_pin_register(),case_005_should_only_affect_one_pin_when_writing_to_pin_using_sbi_issue_103(),case_006_should_update_the_pin_register_on_output_compare_ocr_match_issue_102(),case_007_should_remove_the_given_listener(),case_008_should_return_pinstate_high_when_the_pin_set_to_output_and_high(),case_009_should_return_pinstate_low_when_the_pin_set_to_output_and_low(),case_010_should_return_pinstate_input_by_default_reset_state(),case_011_should_return_pinstate_inputpullup_when_the_pin_is_set_to_input_with_pullup(),case_012_should_reflect_the_current_port_state_when_called_inside_a_listener(),case_013_should_reflect_the_current_port_state_when_called_inside_a_listener_after_ddr_change(),case_014_should_set_the_value_of_the_given_pin(),case_015_should_only_update_pin_register_when_pin_in_input_mode(),case_016_should_generate_int0_interrupt_on_rising_edge(),case_017_should_generate_int0_interrupt_on_falling_edge(),case_018_should_generate_int0_interrupt_on_level_change(),case_019_should_a_sticky_int0_interrupt_while_the_pin_level_is_low(),case_020_should_generate_a_pin_change_interrupt_when_pb3_pcint3_goes_high(),case_021_should_generate_a_pin_change_interrupt_when_pb3_pcint3_goes_low(),case_022_should_clear_the_interrupt_flag_when_writing_to_pcifr()]
}

fn setup_0() -> Vec<Step> {
    vec![
        at(10, bind(r#"SREG"#, num(95.0))),
        at(13, bind(r#"PINB"#, num(35.0))),
        at(14, bind(r#"DDRB"#, num(36.0))),
        at(15, bind(r#"PORTB"#, num(37.0))),
        at(16, bind(r#"PIND"#, num(41.0))),
        at(17, bind(r#"DDRD"#, num(42.0))),
        at(18, bind(r#"PORTD"#, num(43.0))),
        at(19, bind(r#"EIFR"#, num(60.0))),
        at(20, bind(r#"EIMSK"#, num(61.0))),
        at(21, bind(r#"PCICR"#, num(104.0))),
        at(22, bind(r#"EICRA"#, num(105.0))),
        at(23, bind(r#"PCIFR"#, num(59.0))),
        at(24, bind(r#"PCMSK0"#, num(107.0))),
        at(27, bind(r#"INT0"#, num(0.0))),
        at(28, bind(r#"ISC00"#, num(0.0))),
        at(29, bind(r#"ISC01"#, num(1.0))),
        at(30, bind(r#"PCIE0"#, num(0.0))),
        at(31, bind(r#"PCINT3"#, num(3.0))),
        at(34, bind(r#"PB0"#, num(0.0))),
        at(35, bind(r#"PB1"#, num(1.0))),
        at(36, bind(r#"PB3"#, num(3.0))),
        at(37, bind(r#"PB4"#, num(4.0))),
        at(38, bind(r#"PD2"#, num(2.0))),
        at(41, bind(r#"PC_INT_INT0"#, num(2.0))),
        at(42, bind(r#"PC_INT_PCINT0"#, num(6.0))),
    ]
}

pub fn case_001_should_invoke_the_listeners_when_the_port_is_written_to() -> Case {
    Case {
        source: r#"src/peripherals/gpio.spec.ts"#,
        name: r#"GPIO / should invoke the listeners when the port is written to"#,
        line: 45,
        assertions: 2,
        setup: setup_0(),
        body: vec![
            at(
                46,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                47,
                bind(
                    r#"port"#,
                    new(r#"AVRIOPort"#, vec![var(r#"cpu"#), var(r#"portBConfig"#)]),
                ),
            ),
            at(
                48,
                bind(
                    r#"listener"#,
                    call(get(var(r#"vi"#), text(r#"fn"#)), vec![]),
                ),
            ),
            at(
                49,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"DDRB"#), num(15.0)],
                )),
            ),
            at(
                50,
                eval(call(
                    get(var(r#"port"#), text(r#"addListener"#)),
                    vec![var(r#"listener"#)],
                )),
            ),
            at(
                51,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"PORTB"#), num(85.0)],
                )),
            ),
            at(
                52,
                check(
                    var(r#"listener"#),
                    r#"toHaveBeenCalledWith"#,
                    false,
                    vec![num(85.0), num(0.0)],
                ),
            ),
            at(
                53,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), num(35.0)),
                    r#"toEqual"#,
                    false,
                    vec![num(5.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_001_should_invoke_the_listeners_when_the_port_is_written_to_native() {
    crate::run_native(case_001_should_invoke_the_listeners_when_the_port_is_written_to());
}

pub fn case_002_should_invoke_the_listeners_when_ddr_changes_issue_28() -> Case {
    Case {
        source: r#"src/peripherals/gpio.spec.ts"#,
        name: r#"GPIO / should invoke the listeners when DDR changes (issue #28)"#,
        line: 56,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                57,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                58,
                bind(
                    r#"port"#,
                    new(r#"AVRIOPort"#, vec![var(r#"cpu"#), var(r#"portBConfig"#)]),
                ),
            ),
            at(
                59,
                bind(
                    r#"listener"#,
                    call(get(var(r#"vi"#), text(r#"fn"#)), vec![]),
                ),
            ),
            at(
                60,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"PORTB"#), num(85.0)],
                )),
            ),
            at(
                61,
                eval(call(
                    get(var(r#"port"#), text(r#"addListener"#)),
                    vec![var(r#"listener"#)],
                )),
            ),
            at(
                62,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"DDRB"#), num(240.0)],
                )),
            ),
            at(
                63,
                check(
                    var(r#"listener"#),
                    r#"toHaveBeenCalledWith"#,
                    false,
                    vec![num(85.0), num(85.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_002_should_invoke_the_listeners_when_ddr_changes_issue_28_native() {
    crate::run_native(case_002_should_invoke_the_listeners_when_ddr_changes_issue_28());
}

pub fn case_003_should_invoke_the_listeners_when_pullup_register_enabled_issue_62() -> Case {
    Case {
        source: r#"src/peripherals/gpio.spec.ts"#,
        name: r#"GPIO / should invoke the listeners when pullup register enabled (issue #62)"#,
        line: 66,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                67,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                68,
                bind(
                    r#"port"#,
                    new(r#"AVRIOPort"#, vec![var(r#"cpu"#), var(r#"portBConfig"#)]),
                ),
            ),
            at(
                69,
                bind(
                    r#"listener"#,
                    call(get(var(r#"vi"#), text(r#"fn"#)), vec![]),
                ),
            ),
            at(
                70,
                eval(call(
                    get(var(r#"port"#), text(r#"addListener"#)),
                    vec![var(r#"listener"#)],
                )),
            ),
            at(
                71,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"PORTB"#), num(85.0)],
                )),
            ),
            at(
                72,
                check(
                    var(r#"listener"#),
                    r#"toHaveBeenCalledWith"#,
                    false,
                    vec![num(85.0), num(0.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_003_should_invoke_the_listeners_when_pullup_register_enabled_issue_62_native() {
    crate::run_native(case_003_should_invoke_the_listeners_when_pullup_register_enabled_issue_62());
}

pub fn case_004_should_toggle_the_pin_when_writing_to_the_pin_register() -> Case {
    Case {
        source: r#"src/peripherals/gpio.spec.ts"#,
        name: r#"GPIO / should toggle the pin when writing to the PIN register"#,
        line: 75,
        assertions: 2,
        setup: setup_0(),
        body: vec![
            at(
                76,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                77,
                bind(
                    r#"port"#,
                    new(r#"AVRIOPort"#, vec![var(r#"cpu"#), var(r#"portBConfig"#)]),
                ),
            ),
            at(
                78,
                bind(
                    r#"listener"#,
                    call(get(var(r#"vi"#), text(r#"fn"#)), vec![]),
                ),
            ),
            at(
                79,
                eval(call(
                    get(var(r#"port"#), text(r#"addListener"#)),
                    vec![var(r#"listener"#)],
                )),
            ),
            at(
                80,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"DDRB"#), num(15.0)],
                )),
            ),
            at(
                81,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"PORTB"#), num(85.0)],
                )),
            ),
            at(
                82,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"PINB"#), num(1.0)],
                )),
            ),
            at(
                83,
                check(
                    var(r#"listener"#),
                    r#"toHaveBeenCalledWith"#,
                    false,
                    vec![num(84.0), num(85.0)],
                ),
            ),
            at(
                84,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"PINB"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(4.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_004_should_toggle_the_pin_when_writing_to_the_pin_register_native() {
    crate::run_native(case_004_should_toggle_the_pin_when_writing_to_the_pin_register());
}

pub fn case_005_should_only_affect_one_pin_when_writing_to_pin_using_sbi_issue_103() -> Case {
    Case {
        source: r#"src/peripherals/gpio.spec.ts"#,
        name: r#"GPIO / should only affect one pin when writing to PIN using SBI (issue #103)"#,
        line: 87,
        assertions: 4,
        setup: setup_0(),
        body: vec![
            at(
                88,
                destructure(
                    vec![(r#"program"#, r#"program"#)],
                    call(
                        var(r#"asmProgram"#),
                        vec![template(vec![
                            text(
                                r#"
    ; register addresses
    _REPLACE DDRD, "#,
                            ),
                            binary(r#"-"#, var(r#"DDRD"#), num(32.0)),
                            text(
                                r#"
    _REPLACE PIND, "#,
                            ),
                            binary(r#"-"#, var(r#"PIND"#), num(32.0)),
                            text(
                                r#"
    _REPLACE PORTD, "#,
                            ),
                            binary(r#"-"#, var(r#"PORTD"#), num(32.0)),
                            text(
                                r#"

    ; Setup
    ldi r24, 0x48
    out DDRD, r24
    out PORTD, r24

    ; Now toggle pin 6 with SBI
    sbi PIND, 6

    break
  "#,
                            ),
                        ])],
                    ),
                ),
            ),
            at(104, bind(r#"cpu"#, new(r#"CPU"#, vec![var(r#"program"#)]))),
            at(
                105,
                bind(
                    r#"portD"#,
                    new(r#"AVRIOPort"#, vec![var(r#"cpu"#), var(r#"portDConfig"#)]),
                ),
            ),
            at(
                106,
                bind(
                    r#"runner"#,
                    new(r#"TestProgramRunner"#, vec![var(r#"cpu"#)]),
                ),
            ),
            at(
                108,
                bind(
                    r#"listener"#,
                    call(get(var(r#"vi"#), text(r#"fn"#)), vec![]),
                ),
            ),
            at(
                109,
                eval(call(
                    get(var(r#"portD"#), text(r#"addListener"#)),
                    vec![var(r#"listener"#)],
                )),
            ),
            at(
                112,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(3.0)],
                )),
            ),
            at(
                113,
                check(
                    var(r#"listener"#),
                    r#"toHaveBeenCalledWith"#,
                    false,
                    vec![num(72.0), num(0.0)],
                ),
            ),
            at(
                114,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"PORTD"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(72.0)],
                ),
            ),
            at(
                115,
                eval(call(get(var(r#"listener"#), text(r#"mockReset"#)), vec![])),
            ),
            at(
                118,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(1.0)],
                )),
            ),
            at(
                119,
                check(
                    var(r#"listener"#),
                    r#"toHaveBeenCalledWith"#,
                    false,
                    vec![num(8.0), num(72.0)],
                ),
            ),
            at(
                120,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"PORTD"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(8.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_005_should_only_affect_one_pin_when_writing_to_pin_using_sbi_issue_103_native() {
    crate::run_native(
        case_005_should_only_affect_one_pin_when_writing_to_pin_using_sbi_issue_103(),
    );
}

pub fn case_006_should_update_the_pin_register_on_output_compare_ocr_match_issue_102() -> Case {
    Case {
        source: r#"src/peripherals/gpio.spec.ts"#,
        name: r#"GPIO / should update the PIN register on output compare (OCR) match (issue #102)"#,
        line: 123,
        assertions: 4,
        setup: setup_0(),
        body: vec![
            at(
                124,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                125,
                bind(
                    r#"port"#,
                    new(r#"AVRIOPort"#, vec![var(r#"cpu"#), var(r#"portBConfig"#)]),
                ),
            ),
            at(
                126,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"DDRB"#), binary(r#"<<"#, num(1.0), num(1.0))],
                )),
            ),
            at(
                127,
                eval(call(
                    get(var(r#"port"#), text(r#"timerOverridePin"#)),
                    vec![num(1.0), get(var(r#"PinOverrideMode"#), text(r#"Set"#))],
                )),
            ),
            at(
                128,
                check(
                    call(get(var(r#"port"#), text(r#"pinState"#)), vec![num(1.0)]),
                    r#"toBe"#,
                    false,
                    vec![get(var(r#"PinState"#), text(r#"High"#))],
                ),
            ),
            at(
                129,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"PINB"#)),
                    r#"toBe"#,
                    false,
                    vec![binary(r#"<<"#, num(1.0), num(1.0))],
                ),
            ),
            at(
                130,
                eval(call(
                    get(var(r#"port"#), text(r#"timerOverridePin"#)),
                    vec![num(1.0), get(var(r#"PinOverrideMode"#), text(r#"Clear"#))],
                )),
            ),
            at(
                131,
                check(
                    call(get(var(r#"port"#), text(r#"pinState"#)), vec![num(1.0)]),
                    r#"toBe"#,
                    false,
                    vec![get(var(r#"PinState"#), text(r#"Low"#))],
                ),
            ),
            at(
                132,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"PINB"#)),
                    r#"toBe"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_006_should_update_the_pin_register_on_output_compare_ocr_match_issue_102_native() {
    crate::run_native(
        case_006_should_update_the_pin_register_on_output_compare_ocr_match_issue_102(),
    );
}

pub fn case_007_should_remove_the_given_listener() -> Case {
    Case {
        source: r#"src/peripherals/gpio.spec.ts"#,
        name: r#"GPIO / removeListener / should remove the given listener"#,
        line: 136,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                137,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                138,
                bind(
                    r#"port"#,
                    new(r#"AVRIOPort"#, vec![var(r#"cpu"#), var(r#"portBConfig"#)]),
                ),
            ),
            at(
                139,
                bind(
                    r#"listener"#,
                    call(get(var(r#"vi"#), text(r#"fn"#)), vec![]),
                ),
            ),
            at(
                140,
                eval(call(
                    get(var(r#"port"#), text(r#"addListener"#)),
                    vec![var(r#"listener"#)],
                )),
            ),
            at(
                141,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"DDRB"#), num(15.0)],
                )),
            ),
            at(
                142,
                eval(call(
                    get(var(r#"port"#), text(r#"removeListener"#)),
                    vec![var(r#"listener"#)],
                )),
            ),
            at(
                143,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"PORTB"#), num(153.0)],
                )),
            ),
            at(
                144,
                check(
                    var(r#"listener"#),
                    r#"toHaveBeenCalledTimes"#,
                    false,
                    vec![num(1.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_007_should_remove_the_given_listener_native() {
    crate::run_native(case_007_should_remove_the_given_listener());
}

pub fn case_008_should_return_pinstate_high_when_the_pin_set_to_output_and_high() -> Case {
    Case {
        source: r#"src/peripherals/gpio.spec.ts"#,
        name: r#"GPIO / pinState / should return PinState.High when the pin set to output and HIGH"#,
        line: 149,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                150,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                151,
                bind(
                    r#"port"#,
                    new(r#"AVRIOPort"#, vec![var(r#"cpu"#), var(r#"portBConfig"#)]),
                ),
            ),
            at(
                152,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"DDRB"#), num(1.0)],
                )),
            ),
            at(
                153,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"PORTB"#), num(1.0)],
                )),
            ),
            at(
                154,
                check(
                    call(
                        get(var(r#"port"#), text(r#"pinState"#)),
                        vec![var(r#"PB0"#)],
                    ),
                    r#"toEqual"#,
                    false,
                    vec![get(var(r#"PinState"#), text(r#"High"#))],
                ),
            ),
        ],
    }
}
#[test]
fn case_008_should_return_pinstate_high_when_the_pin_set_to_output_and_high_native() {
    crate::run_native(case_008_should_return_pinstate_high_when_the_pin_set_to_output_and_high());
}

pub fn case_009_should_return_pinstate_low_when_the_pin_set_to_output_and_low() -> Case {
    Case {
        source: r#"src/peripherals/gpio.spec.ts"#,
        name: r#"GPIO / pinState / should return PinState.Low when the pin set to output and LOW"#,
        line: 157,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                158,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                159,
                bind(
                    r#"port"#,
                    new(r#"AVRIOPort"#, vec![var(r#"cpu"#), var(r#"portBConfig"#)]),
                ),
            ),
            at(
                160,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"DDRB"#), num(8.0)],
                )),
            ),
            at(
                161,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"PORTB"#), num(247.0)],
                )),
            ),
            at(
                162,
                check(
                    call(
                        get(var(r#"port"#), text(r#"pinState"#)),
                        vec![var(r#"PB3"#)],
                    ),
                    r#"toEqual"#,
                    false,
                    vec![get(var(r#"PinState"#), text(r#"Low"#))],
                ),
            ),
        ],
    }
}
#[test]
fn case_009_should_return_pinstate_low_when_the_pin_set_to_output_and_low_native() {
    crate::run_native(case_009_should_return_pinstate_low_when_the_pin_set_to_output_and_low());
}

pub fn case_010_should_return_pinstate_input_by_default_reset_state() -> Case {
    Case {
        source: r#"src/peripherals/gpio.spec.ts"#,
        name: r#"GPIO / pinState / should return PinState.Input by default (reset state)"#,
        line: 165,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                166,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                167,
                bind(
                    r#"port"#,
                    new(r#"AVRIOPort"#, vec![var(r#"cpu"#), var(r#"portBConfig"#)]),
                ),
            ),
            at(
                168,
                check(
                    call(
                        get(var(r#"port"#), text(r#"pinState"#)),
                        vec![var(r#"PB1"#)],
                    ),
                    r#"toEqual"#,
                    false,
                    vec![get(var(r#"PinState"#), text(r#"Input"#))],
                ),
            ),
        ],
    }
}
#[test]
fn case_010_should_return_pinstate_input_by_default_reset_state_native() {
    crate::run_native(case_010_should_return_pinstate_input_by_default_reset_state());
}

pub fn case_011_should_return_pinstate_inputpullup_when_the_pin_is_set_to_input_with_pullup() -> Case
{
    Case {
        source: r#"src/peripherals/gpio.spec.ts"#,
        name: r#"GPIO / pinState / should return PinState.InputPullUp when the pin is set to input with pullup"#,
        line: 171,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                172,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                173,
                bind(
                    r#"port"#,
                    new(r#"AVRIOPort"#, vec![var(r#"cpu"#), var(r#"portBConfig"#)]),
                ),
            ),
            at(
                174,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"DDRB"#), num(0.0)],
                )),
            ),
            at(
                175,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"PORTB"#), num(2.0)],
                )),
            ),
            at(
                176,
                check(
                    call(
                        get(var(r#"port"#), text(r#"pinState"#)),
                        vec![var(r#"PB1"#)],
                    ),
                    r#"toEqual"#,
                    false,
                    vec![get(var(r#"PinState"#), text(r#"InputPullUp"#))],
                ),
            ),
        ],
    }
}
#[test]
fn case_011_should_return_pinstate_inputpullup_when_the_pin_is_set_to_input_with_pullup_native() {
    crate::run_native(
        case_011_should_return_pinstate_inputpullup_when_the_pin_is_set_to_input_with_pullup(),
    );
}

pub fn case_012_should_reflect_the_current_port_state_when_called_inside_a_listener() -> Case {
    Case {
        source: r#"src/peripherals/gpio.spec.ts"#,
        name: r#"GPIO / pinState / should reflect the current port state when called inside a listener"#,
        line: 179,
        assertions: 3,
        setup: setup_0(),
        body: vec![
            at(
                181,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                182,
                bind(
                    r#"port"#,
                    new(r#"AVRIOPort"#, vec![var(r#"cpu"#), var(r#"portBConfig"#)]),
                ),
            ),
            at(
                183,
                bind(
                    r#"listener"#,
                    call(
                        get(var(r#"vi"#), text(r#"fn"#)),
                        vec![function(
                            vec![],
                            vec![at(
                                184,
                                check(
                                    call(
                                        get(var(r#"port"#), text(r#"pinState"#)),
                                        vec![var(r#"PB0"#)],
                                    ),
                                    r#"toBe"#,
                                    false,
                                    vec![get(var(r#"PinState"#), text(r#"High"#))],
                                ),
                            )],
                        )],
                    ),
                ),
            ),
            at(
                186,
                check(
                    call(
                        get(var(r#"port"#), text(r#"pinState"#)),
                        vec![var(r#"PB0"#)],
                    ),
                    r#"toBe"#,
                    false,
                    vec![get(var(r#"PinState"#), text(r#"Input"#))],
                ),
            ),
            at(
                187,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"DDRB"#), num(1.0)],
                )),
            ),
            at(
                188,
                eval(call(
                    get(var(r#"port"#), text(r#"addListener"#)),
                    vec![var(r#"listener"#)],
                )),
            ),
            at(
                189,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"PORTB"#), num(1.0)],
                )),
            ),
            at(
                190,
                check(var(r#"listener"#), r#"toHaveBeenCalled"#, false, vec![]),
            ),
        ],
    }
}
#[test]
fn case_012_should_reflect_the_current_port_state_when_called_inside_a_listener_native() {
    crate::run_native(
        case_012_should_reflect_the_current_port_state_when_called_inside_a_listener(),
    );
}

pub fn case_013_should_reflect_the_current_port_state_when_called_inside_a_listener_after_ddr_change(
) -> Case {
    Case {
        source: r#"src/peripherals/gpio.spec.ts"#,
        name: r#"GPIO / pinState / should reflect the current port state when called inside a listener after DDR change"#,
        line: 193,
        assertions: 3,
        setup: setup_0(),
        body: vec![
            at(
                195,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                196,
                bind(
                    r#"port"#,
                    new(r#"AVRIOPort"#, vec![var(r#"cpu"#), var(r#"portBConfig"#)]),
                ),
            ),
            at(
                197,
                bind(
                    r#"listener"#,
                    call(
                        get(var(r#"vi"#), text(r#"fn"#)),
                        vec![function(
                            vec![],
                            vec![at(
                                198,
                                check(
                                    call(
                                        get(var(r#"port"#), text(r#"pinState"#)),
                                        vec![var(r#"PB0"#)],
                                    ),
                                    r#"toBe"#,
                                    false,
                                    vec![get(var(r#"PinState"#), text(r#"Low"#))],
                                ),
                            )],
                        )],
                    ),
                ),
            ),
            at(
                200,
                check(
                    call(
                        get(var(r#"port"#), text(r#"pinState"#)),
                        vec![var(r#"PB0"#)],
                    ),
                    r#"toBe"#,
                    false,
                    vec![get(var(r#"PinState"#), text(r#"Input"#))],
                ),
            ),
            at(
                201,
                eval(call(
                    get(var(r#"port"#), text(r#"addListener"#)),
                    vec![var(r#"listener"#)],
                )),
            ),
            at(
                202,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"DDRB"#), num(1.0)],
                )),
            ),
            at(
                203,
                check(var(r#"listener"#), r#"toHaveBeenCalled"#, false, vec![]),
            ),
        ],
    }
}
#[test]
fn case_013_should_reflect_the_current_port_state_when_called_inside_a_listener_after_ddr_change_native(
) {
    crate::run_native(case_013_should_reflect_the_current_port_state_when_called_inside_a_listener_after_ddr_change());
}

pub fn case_014_should_set_the_value_of_the_given_pin() -> Case {
    Case {
        source: r#"src/peripherals/gpio.spec.ts"#,
        name: r#"GPIO / setPin / should set the value of the given pin"#,
        line: 208,
        assertions: 2,
        setup: setup_0(),
        body: vec![
            at(
                209,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                210,
                bind(
                    r#"port"#,
                    new(r#"AVRIOPort"#, vec![var(r#"cpu"#), var(r#"portBConfig"#)]),
                ),
            ),
            at(
                211,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"DDRB"#), num(0.0)],
                )),
            ),
            at(
                212,
                eval(call(
                    get(var(r#"port"#), text(r#"setPin"#)),
                    vec![var(r#"PB4"#), boolean(true)],
                )),
            ),
            at(
                213,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), num(35.0)),
                    r#"toEqual"#,
                    false,
                    vec![num(16.0)],
                ),
            ),
            at(
                214,
                eval(call(
                    get(var(r#"port"#), text(r#"setPin"#)),
                    vec![var(r#"PB4"#), boolean(false)],
                )),
            ),
            at(
                215,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), num(35.0)),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_014_should_set_the_value_of_the_given_pin_native() {
    crate::run_native(case_014_should_set_the_value_of_the_given_pin());
}

pub fn case_015_should_only_update_pin_register_when_pin_in_input_mode() -> Case {
    Case {
        source: r#"src/peripherals/gpio.spec.ts"#,
        name: r#"GPIO / setPin / should only update PIN register when pin in Input mode"#,
        line: 218,
        assertions: 2,
        setup: setup_0(),
        body: vec![
            at(
                219,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                220,
                bind(
                    r#"port"#,
                    new(r#"AVRIOPort"#, vec![var(r#"cpu"#), var(r#"portBConfig"#)]),
                ),
            ),
            at(
                221,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"DDRB"#), num(16.0)],
                )),
            ),
            at(
                222,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"PORTB"#), num(0.0)],
                )),
            ),
            at(
                223,
                eval(call(
                    get(var(r#"port"#), text(r#"setPin"#)),
                    vec![var(r#"PB4"#), boolean(true)],
                )),
            ),
            at(
                224,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"PINB"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
            at(
                225,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"DDRB"#), num(0.0)],
                )),
            ),
            at(
                226,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"PINB"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(16.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_015_should_only_update_pin_register_when_pin_in_input_mode_native() {
    crate::run_native(case_015_should_only_update_pin_register_when_pin_in_input_mode());
}

pub fn case_016_should_generate_int0_interrupt_on_rising_edge() -> Case {
    Case {
        source: r#"src/peripherals/gpio.spec.ts"#,
        name: r#"GPIO / External interrupt / should generate INT0 interrupt on rising edge"#,
        line: 231,
        assertions: 6,
        setup: setup_0(),
        body: vec![
            at(
                232,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                233,
                bind(
                    r#"port"#,
                    new(r#"AVRIOPort"#, vec![var(r#"cpu"#), var(r#"portDConfig"#)]),
                ),
            ),
            at(
                234,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EIMSK"#), binary(r#"<<"#, num(1.0), var(r#"INT0"#))],
                )),
            ),
            at(
                235,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"EICRA"#),
                        binary(
                            r#"|"#,
                            binary(r#"<<"#, num(1.0), var(r#"ISC01"#)),
                            binary(r#"<<"#, num(1.0), var(r#"ISC00"#)),
                        ),
                    ],
                )),
            ),
            at(
                237,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"EIFR"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
            at(
                238,
                eval(call(
                    get(var(r#"port"#), text(r#"setPin"#)),
                    vec![var(r#"PD2"#), boolean(true)],
                )),
            ),
            at(
                239,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"EIFR"#)),
                    r#"toEqual"#,
                    false,
                    vec![binary(r#"<<"#, num(1.0), var(r#"INT0"#))],
                ),
            ),
            at(
                241,
                eval(assign(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"SREG"#)),
                    num(128.0),
                    r#"="#,
                )),
            ),
            at(242, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                243,
                check(
                    get(var(r#"cpu"#), text(r#"pc"#)),
                    r#"toEqual"#,
                    false,
                    vec![var(r#"PC_INT_INT0"#)],
                ),
            ),
            at(
                244,
                check(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(2.0)],
                ),
            ),
            at(
                245,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"EIFR"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
            at(
                247,
                eval(call(
                    get(var(r#"port"#), text(r#"setPin"#)),
                    vec![var(r#"PD2"#), boolean(false)],
                )),
            ),
            at(
                248,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"EIFR"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_016_should_generate_int0_interrupt_on_rising_edge_native() {
    crate::run_native(case_016_should_generate_int0_interrupt_on_rising_edge());
}

pub fn case_017_should_generate_int0_interrupt_on_falling_edge() -> Case {
    Case {
        source: r#"src/peripherals/gpio.spec.ts"#,
        name: r#"GPIO / External interrupt / should generate INT0 interrupt on falling edge"#,
        line: 251,
        assertions: 6,
        setup: setup_0(),
        body: vec![
            at(
                252,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                253,
                bind(
                    r#"port"#,
                    new(r#"AVRIOPort"#, vec![var(r#"cpu"#), var(r#"portDConfig"#)]),
                ),
            ),
            at(
                254,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EIMSK"#), binary(r#"<<"#, num(1.0), var(r#"INT0"#))],
                )),
            ),
            at(
                255,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EICRA"#), binary(r#"<<"#, num(1.0), var(r#"ISC01"#))],
                )),
            ),
            at(
                257,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"EIFR"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
            at(
                258,
                eval(call(
                    get(var(r#"port"#), text(r#"setPin"#)),
                    vec![var(r#"PD2"#), boolean(true)],
                )),
            ),
            at(
                259,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"EIFR"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
            at(
                260,
                eval(call(
                    get(var(r#"port"#), text(r#"setPin"#)),
                    vec![var(r#"PD2"#), boolean(false)],
                )),
            ),
            at(
                261,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"EIFR"#)),
                    r#"toEqual"#,
                    false,
                    vec![binary(r#"<<"#, num(1.0), var(r#"INT0"#))],
                ),
            ),
            at(
                263,
                eval(assign(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"SREG"#)),
                    num(128.0),
                    r#"="#,
                )),
            ),
            at(264, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                265,
                check(
                    get(var(r#"cpu"#), text(r#"pc"#)),
                    r#"toEqual"#,
                    false,
                    vec![var(r#"PC_INT_INT0"#)],
                ),
            ),
            at(
                266,
                check(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(2.0)],
                ),
            ),
            at(
                267,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"EIFR"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_017_should_generate_int0_interrupt_on_falling_edge_native() {
    crate::run_native(case_017_should_generate_int0_interrupt_on_falling_edge());
}

pub fn case_018_should_generate_int0_interrupt_on_level_change() -> Case {
    Case {
        source: r#"src/peripherals/gpio.spec.ts"#,
        name: r#"GPIO / External interrupt / should generate INT0 interrupt on level change"#,
        line: 270,
        assertions: 4,
        setup: setup_0(),
        body: vec![
            at(
                271,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                272,
                bind(
                    r#"port"#,
                    new(r#"AVRIOPort"#, vec![var(r#"cpu"#), var(r#"portDConfig"#)]),
                ),
            ),
            at(
                273,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EIMSK"#), binary(r#"<<"#, num(1.0), var(r#"INT0"#))],
                )),
            ),
            at(
                274,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EICRA"#), binary(r#"<<"#, num(1.0), var(r#"ISC00"#))],
                )),
            ),
            at(
                276,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"EIFR"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
            at(
                277,
                eval(call(
                    get(var(r#"port"#), text(r#"setPin"#)),
                    vec![var(r#"PD2"#), boolean(true)],
                )),
            ),
            at(
                278,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"EIFR"#)),
                    r#"toEqual"#,
                    false,
                    vec![binary(r#"<<"#, num(1.0), var(r#"INT0"#))],
                ),
            ),
            at(
                279,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EIFR"#), binary(r#"<<"#, num(1.0), var(r#"INT0"#))],
                )),
            ),
            at(
                280,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"EIFR"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
            at(
                281,
                eval(call(
                    get(var(r#"port"#), text(r#"setPin"#)),
                    vec![var(r#"PD2"#), boolean(false)],
                )),
            ),
            at(
                282,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"EIFR"#)),
                    r#"toEqual"#,
                    false,
                    vec![binary(r#"<<"#, num(1.0), var(r#"INT0"#))],
                ),
            ),
        ],
    }
}
#[test]
fn case_018_should_generate_int0_interrupt_on_level_change_native() {
    crate::run_native(case_018_should_generate_int0_interrupt_on_level_change());
}

pub fn case_019_should_a_sticky_int0_interrupt_while_the_pin_level_is_low() -> Case {
    Case {
        source: r#"src/peripherals/gpio.spec.ts"#,
        name: r#"GPIO / External interrupt / should a sticky INT0 interrupt while the pin level is low"#,
        line: 285,
        assertions: 8,
        setup: setup_0(),
        body: vec![
            at(
                286,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                287,
                bind(
                    r#"port"#,
                    new(r#"AVRIOPort"#, vec![var(r#"cpu"#), var(r#"portDConfig"#)]),
                ),
            ),
            at(
                288,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EIMSK"#), binary(r#"<<"#, num(1.0), var(r#"INT0"#))],
                )),
            ),
            at(
                289,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EICRA"#), num(0.0)],
                )),
            ),
            at(
                290,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"EIFR"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
            at(
                292,
                eval(call(
                    get(var(r#"port"#), text(r#"setPin"#)),
                    vec![var(r#"PD2"#), boolean(true)],
                )),
            ),
            at(
                293,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"EIFR"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
            at(
                295,
                eval(call(
                    get(var(r#"port"#), text(r#"setPin"#)),
                    vec![var(r#"PD2"#), boolean(false)],
                )),
            ),
            at(
                296,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"EIFR"#)),
                    r#"toEqual"#,
                    false,
                    vec![binary(r#"<<"#, num(1.0), var(r#"INT0"#))],
                ),
            ),
            at(
                299,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EIFR"#), binary(r#"<<"#, num(1.0), var(r#"INT0"#))],
                )),
            ),
            at(
                300,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"EIFR"#)),
                    r#"toEqual"#,
                    false,
                    vec![binary(r#"<<"#, num(1.0), var(r#"INT0"#))],
                ),
            ),
            at(
                302,
                eval(assign(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"SREG"#)),
                    num(128.0),
                    r#"="#,
                )),
            ),
            at(303, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                304,
                check(
                    get(var(r#"cpu"#), text(r#"pc"#)),
                    r#"toEqual"#,
                    false,
                    vec![var(r#"PC_INT_INT0"#)],
                ),
            ),
            at(
                305,
                check(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(2.0)],
                ),
            ),
            at(
                308,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"EIFR"#)),
                    r#"toEqual"#,
                    false,
                    vec![binary(r#"<<"#, num(1.0), var(r#"INT0"#))],
                ),
            ),
            at(
                311,
                eval(call(
                    get(var(r#"port"#), text(r#"setPin"#)),
                    vec![var(r#"PD2"#), boolean(true)],
                )),
            ),
            at(
                312,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"EIFR"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_019_should_a_sticky_int0_interrupt_while_the_pin_level_is_low_native() {
    crate::run_native(case_019_should_a_sticky_int0_interrupt_while_the_pin_level_is_low());
}

pub fn case_020_should_generate_a_pin_change_interrupt_when_pb3_pcint3_goes_high() -> Case {
    Case {
        source: r#"src/peripherals/gpio.spec.ts"#,
        name: r#"GPIO / Pin change interrupts (PCINT) / should generate a pin change interrupt when PB3 (PCINT3) goes high"#,
        line: 317,
        assertions: 4,
        setup: setup_0(),
        body: vec![
            at(
                318,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                319,
                bind(
                    r#"port"#,
                    new(r#"AVRIOPort"#, vec![var(r#"cpu"#), var(r#"portBConfig"#)]),
                ),
            ),
            at(
                320,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"PCICR"#), binary(r#"<<"#, num(1.0), var(r#"PCIE0"#))],
                )),
            ),
            at(
                321,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"PCMSK0"#),
                        binary(r#"<<"#, num(1.0), var(r#"PCINT3"#)),
                    ],
                )),
            ),
            at(
                323,
                eval(call(
                    get(var(r#"port"#), text(r#"setPin"#)),
                    vec![var(r#"PB3"#), boolean(true)],
                )),
            ),
            at(
                324,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"PCIFR"#)),
                    r#"toEqual"#,
                    false,
                    vec![binary(r#"<<"#, num(1.0), var(r#"PCIE0"#))],
                ),
            ),
            at(
                326,
                eval(assign(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"SREG"#)),
                    num(128.0),
                    r#"="#,
                )),
            ),
            at(327, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                328,
                check(
                    get(var(r#"cpu"#), text(r#"pc"#)),
                    r#"toEqual"#,
                    false,
                    vec![var(r#"PC_INT_PCINT0"#)],
                ),
            ),
            at(
                329,
                check(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(2.0)],
                ),
            ),
            at(
                330,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"PCIFR"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_020_should_generate_a_pin_change_interrupt_when_pb3_pcint3_goes_high_native() {
    crate::run_native(case_020_should_generate_a_pin_change_interrupt_when_pb3_pcint3_goes_high());
}

pub fn case_021_should_generate_a_pin_change_interrupt_when_pb3_pcint3_goes_low() -> Case {
    Case {
        source: r#"src/peripherals/gpio.spec.ts"#,
        name: r#"GPIO / Pin change interrupts (PCINT) / should generate a pin change interrupt when PB3 (PCINT3) goes low"#,
        line: 333,
        assertions: 5,
        setup: setup_0(),
        body: vec![
            at(
                334,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                335,
                bind(
                    r#"port"#,
                    new(r#"AVRIOPort"#, vec![var(r#"cpu"#), var(r#"portBConfig"#)]),
                ),
            ),
            at(
                337,
                eval(call(
                    get(var(r#"port"#), text(r#"setPin"#)),
                    vec![var(r#"PB3"#), boolean(true)],
                )),
            ),
            at(
                338,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"PCICR"#), binary(r#"<<"#, num(1.0), var(r#"PCIE0"#))],
                )),
            ),
            at(
                339,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"PCMSK0"#),
                        binary(r#"<<"#, num(1.0), var(r#"PCINT3"#)),
                    ],
                )),
            ),
            at(
                340,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"PCIFR"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
            at(
                342,
                eval(call(
                    get(var(r#"port"#), text(r#"setPin"#)),
                    vec![var(r#"PB3"#), boolean(false)],
                )),
            ),
            at(
                343,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"PCIFR"#)),
                    r#"toEqual"#,
                    false,
                    vec![binary(r#"<<"#, num(1.0), var(r#"PCIE0"#))],
                ),
            ),
            at(
                345,
                eval(assign(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"SREG"#)),
                    num(128.0),
                    r#"="#,
                )),
            ),
            at(346, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                347,
                check(
                    get(var(r#"cpu"#), text(r#"pc"#)),
                    r#"toEqual"#,
                    false,
                    vec![var(r#"PC_INT_PCINT0"#)],
                ),
            ),
            at(
                348,
                check(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(2.0)],
                ),
            ),
            at(
                349,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"PCIFR"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_021_should_generate_a_pin_change_interrupt_when_pb3_pcint3_goes_low_native() {
    crate::run_native(case_021_should_generate_a_pin_change_interrupt_when_pb3_pcint3_goes_low());
}

pub fn case_022_should_clear_the_interrupt_flag_when_writing_to_pcifr() -> Case {
    Case {
        source: r#"src/peripherals/gpio.spec.ts"#,
        name: r#"GPIO / Pin change interrupts (PCINT) / should clear the interrupt flag when writing to PCIFR"#,
        line: 352,
        assertions: 2,
        setup: setup_0(),
        body: vec![
            at(
                353,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                354,
                bind(
                    r#"port"#,
                    new(r#"AVRIOPort"#, vec![var(r#"cpu"#), var(r#"portBConfig"#)]),
                ),
            ),
            at(
                355,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"PCICR"#), binary(r#"<<"#, num(1.0), var(r#"PCIE0"#))],
                )),
            ),
            at(
                356,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"PCMSK0"#),
                        binary(r#"<<"#, num(1.0), var(r#"PCINT3"#)),
                    ],
                )),
            ),
            at(
                358,
                eval(call(
                    get(var(r#"port"#), text(r#"setPin"#)),
                    vec![var(r#"PB3"#), boolean(true)],
                )),
            ),
            at(
                359,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"PCIFR"#)),
                    r#"toEqual"#,
                    false,
                    vec![binary(r#"<<"#, num(1.0), var(r#"PCIE0"#))],
                ),
            ),
            at(
                361,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"PCIFR"#), binary(r#"<<"#, num(1.0), var(r#"PCIE0"#))],
                )),
            ),
            at(
                362,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"PCIFR"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_022_should_clear_the_interrupt_flag_when_writing_to_pcifr_native() {
    crate::run_native(case_022_should_clear_the_interrupt_flag_when_writing_to_pcifr());
}
