// SPDX-License-Identifier: MIT
// Copyright (c) Uri Shaked and contributors
// Generated by tools/convert.cjs. Source: src/peripherals/clock.spec.ts
use crate::scenario::*;
pub const IMPORTS: &[&str] = &[r#"CPU"#, r#"AVRClock"#, r#"clockConfig"#];
pub fn cases() -> Vec<Case> {
    vec![
        case_001_should_set_the_prescaler_when_double_writing_clkpc(),
        case_002_should_not_update_the_prescaler_if_clkpce_was_not_set_clkpc(),
        case_003_should_not_update_the_prescaler_if_more_than_4_cycles_passed_since_setting_clkpce(
        ),
        case_004_should_return_the_current_prescaler_value(),
        case_005_should_return_current_number_of_microseconds_derived_from_base_freq_prescaler(),
        case_006_should_return_current_number_of_milliseconds_derived_from_base_freq_prescaler(),
        case_007_should_return_current_number_of_nanoseconds_derived_from_base_freq_prescaler(),
        case_008_should_correctly_calculate_time_when_changing_the_prescale_value_at_runtime(),
    ]
}

fn setup_0() -> Vec<Step> {
    vec![
        at(9, bind(r#"CLKPC"#, num(97.0))),
        at(12, bind(r#"CLKPCE"#, num(128.0))),
    ]
}

pub fn case_001_should_set_the_prescaler_when_double_writing_clkpc() -> Case {
    Case {
        source: r#"src/peripherals/clock.spec.ts"#,
        name: r#"Clock / should set the prescaler when double-writing CLKPC"#,
        line: 15,
        assertions: 2,
        setup: setup_0(),
        body: vec![
            at(
                16,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(4096.0)])]),
                ),
            ),
            at(
                17,
                bind(
                    r#"clock"#,
                    new(
                        r#"AVRClock"#,
                        vec![var(r#"cpu"#), num(16000000.0), var(r#"clockConfig"#)],
                    ),
                ),
            ),
            at(
                18,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"CLKPC"#), var(r#"CLKPCE"#)],
                )),
            ),
            at(
                19,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"CLKPC"#), num(3.0)],
                )),
            ),
            at(
                20,
                check(
                    get(var(r#"clock"#), text(r#"frequency"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(2000000.0)],
                ),
            ),
            at(
                21,
                check(
                    call(
                        get(var(r#"cpu"#), text(r#"readData"#)),
                        vec![var(r#"CLKPC"#)],
                    ),
                    r#"toEqual"#,
                    false,
                    vec![num(3.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_001_should_set_the_prescaler_when_double_writing_clkpc_native() {
    crate::run_native(case_001_should_set_the_prescaler_when_double_writing_clkpc());
}

pub fn case_002_should_not_update_the_prescaler_if_clkpce_was_not_set_clkpc() -> Case {
    Case {
        source: r#"src/peripherals/clock.spec.ts"#,
        name: r#"Clock / should not update the prescaler if CLKPCE was not set CLKPC"#,
        line: 24,
        assertions: 2,
        setup: setup_0(),
        body: vec![
            at(
                25,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(4096.0)])]),
                ),
            ),
            at(
                26,
                bind(
                    r#"clock"#,
                    new(
                        r#"AVRClock"#,
                        vec![var(r#"cpu"#), num(16000000.0), var(r#"clockConfig"#)],
                    ),
                ),
            ),
            at(
                27,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"CLKPC"#), num(3.0)],
                )),
            ),
            at(
                28,
                check(
                    get(var(r#"clock"#), text(r#"frequency"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(16000000.0)],
                ),
            ),
            at(
                29,
                check(
                    call(
                        get(var(r#"cpu"#), text(r#"readData"#)),
                        vec![var(r#"CLKPC"#)],
                    ),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_002_should_not_update_the_prescaler_if_clkpce_was_not_set_clkpc_native() {
    crate::run_native(case_002_should_not_update_the_prescaler_if_clkpce_was_not_set_clkpc());
}

pub fn case_003_should_not_update_the_prescaler_if_more_than_4_cycles_passed_since_setting_clkpce(
) -> Case {
    Case {
        source: r#"src/peripherals/clock.spec.ts"#,
        name: r#"Clock / should not update the prescaler if more than 4 cycles passed since setting CLKPCE"#,
        line: 32,
        assertions: 2,
        setup: setup_0(),
        body: vec![
            at(
                33,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(4096.0)])]),
                ),
            ),
            at(
                34,
                bind(
                    r#"clock"#,
                    new(
                        r#"AVRClock"#,
                        vec![var(r#"cpu"#), num(16000000.0), var(r#"clockConfig"#)],
                    ),
                ),
            ),
            at(
                35,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"CLKPC"#), var(r#"CLKPCE"#)],
                )),
            ),
            at(
                36,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(6.0),
                    r#"+="#,
                )),
            ),
            at(
                37,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"CLKPC"#), num(3.0)],
                )),
            ),
            at(
                38,
                check(
                    get(var(r#"clock"#), text(r#"frequency"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(16000000.0)],
                ),
            ),
            at(
                39,
                check(
                    call(
                        get(var(r#"cpu"#), text(r#"readData"#)),
                        vec![var(r#"CLKPC"#)],
                    ),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_003_should_not_update_the_prescaler_if_more_than_4_cycles_passed_since_setting_clkpce_native(
) {
    crate::run_native(
        case_003_should_not_update_the_prescaler_if_more_than_4_cycles_passed_since_setting_clkpce(
        ),
    );
}

pub fn case_004_should_return_the_current_prescaler_value() -> Case {
    Case {
        source: r#"src/peripherals/clock.spec.ts"#,
        name: r#"Clock / prescaler property / should return the current prescaler value"#,
        line: 43,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                44,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(4096.0)])]),
                ),
            ),
            at(
                45,
                bind(
                    r#"clock"#,
                    new(
                        r#"AVRClock"#,
                        vec![var(r#"cpu"#), num(16000000.0), var(r#"clockConfig"#)],
                    ),
                ),
            ),
            at(
                46,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"CLKPC"#), var(r#"CLKPCE"#)],
                )),
            ),
            at(
                47,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"CLKPC"#), num(5.0)],
                )),
            ),
            at(
                48,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(16000000.0),
                    r#"="#,
                )),
            ),
            at(
                49,
                check(
                    get(var(r#"clock"#), text(r#"prescaler"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(32.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_004_should_return_the_current_prescaler_value_native() {
    crate::run_native(case_004_should_return_the_current_prescaler_value());
}

pub fn case_005_should_return_current_number_of_microseconds_derived_from_base_freq_prescaler(
) -> Case {
    Case {
        source: r#"src/peripherals/clock.spec.ts"#,
        name: r#"Clock / time properties / should return current number of microseconds, derived from base freq + prescaler"#,
        line: 54,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                55,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(4096.0)])]),
                ),
            ),
            at(
                56,
                bind(
                    r#"clock"#,
                    new(
                        r#"AVRClock"#,
                        vec![var(r#"cpu"#), num(16000000.0), var(r#"clockConfig"#)],
                    ),
                ),
            ),
            at(
                57,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"CLKPC"#), var(r#"CLKPCE"#)],
                )),
            ),
            at(
                58,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"CLKPC"#), num(2.0)],
                )),
            ),
            at(
                59,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(16000000.0),
                    r#"="#,
                )),
            ),
            at(
                60,
                check(
                    get(var(r#"clock"#), text(r#"timeMillis"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(4000.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_005_should_return_current_number_of_microseconds_derived_from_base_freq_prescaler_native() {
    crate::run_native(
        case_005_should_return_current_number_of_microseconds_derived_from_base_freq_prescaler(),
    );
}

pub fn case_006_should_return_current_number_of_milliseconds_derived_from_base_freq_prescaler(
) -> Case {
    Case {
        source: r#"src/peripherals/clock.spec.ts"#,
        name: r#"Clock / time properties / should return current number of milliseconds, derived from base freq + prescaler"#,
        line: 63,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                64,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(4096.0)])]),
                ),
            ),
            at(
                65,
                bind(
                    r#"clock"#,
                    new(
                        r#"AVRClock"#,
                        vec![var(r#"cpu"#), num(16000000.0), var(r#"clockConfig"#)],
                    ),
                ),
            ),
            at(
                66,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"CLKPC"#), var(r#"CLKPCE"#)],
                )),
            ),
            at(
                67,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"CLKPC"#), num(2.0)],
                )),
            ),
            at(
                68,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(16000000.0),
                    r#"="#,
                )),
            ),
            at(
                69,
                check(
                    get(var(r#"clock"#), text(r#"timeMicros"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(4000000.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_006_should_return_current_number_of_milliseconds_derived_from_base_freq_prescaler_native() {
    crate::run_native(
        case_006_should_return_current_number_of_milliseconds_derived_from_base_freq_prescaler(),
    );
}

pub fn case_007_should_return_current_number_of_nanoseconds_derived_from_base_freq_prescaler(
) -> Case {
    Case {
        source: r#"src/peripherals/clock.spec.ts"#,
        name: r#"Clock / time properties / should return current number of nanoseconds, derived from base freq + prescaler"#,
        line: 72,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                73,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(4096.0)])]),
                ),
            ),
            at(
                74,
                bind(
                    r#"clock"#,
                    new(
                        r#"AVRClock"#,
                        vec![var(r#"cpu"#), num(16000000.0), var(r#"clockConfig"#)],
                    ),
                ),
            ),
            at(
                75,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"CLKPC"#), var(r#"CLKPCE"#)],
                )),
            ),
            at(
                76,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"CLKPC"#), num(2.0)],
                )),
            ),
            at(
                77,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(16000000.0),
                    r#"="#,
                )),
            ),
            at(
                78,
                check(
                    get(var(r#"clock"#), text(r#"timeNanos"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(4000000000.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_007_should_return_current_number_of_nanoseconds_derived_from_base_freq_prescaler_native() {
    crate::run_native(
        case_007_should_return_current_number_of_nanoseconds_derived_from_base_freq_prescaler(),
    );
}

pub fn case_008_should_correctly_calculate_time_when_changing_the_prescale_value_at_runtime() -> Case
{
    Case {
        source: r#"src/peripherals/clock.spec.ts"#,
        name: r#"Clock / time properties / should correctly calculate time when changing the prescale value at runtime"#,
        line: 81,
        assertions: 2,
        setup: setup_0(),
        body: vec![
            at(
                82,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(4096.0)])]),
                ),
            ),
            at(
                83,
                bind(
                    r#"clock"#,
                    new(
                        r#"AVRClock"#,
                        vec![var(r#"cpu"#), num(16000000.0), var(r#"clockConfig"#)],
                    ),
                ),
            ),
            at(
                84,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(16000000.0),
                    r#"="#,
                )),
            ),
            at(
                85,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"CLKPC"#), var(r#"CLKPCE"#)],
                )),
            ),
            at(
                86,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"CLKPC"#), num(2.0)],
                )),
            ),
            at(
                87,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    binary(r#"*"#, num(2.0), num(4000000.0)),
                    r#"+="#,
                )),
            ),
            at(
                88,
                check(
                    get(var(r#"clock"#), text(r#"timeMillis"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(3000.0)],
                ),
            ),
            at(
                90,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"CLKPC"#), var(r#"CLKPCE"#)],
                )),
            ),
            at(
                91,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"CLKPC"#), num(1.0)],
                )),
            ),
            at(
                92,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    binary(r#"*"#, num(0.5), num(8000000.0)),
                    r#"+="#,
                )),
            ),
            at(
                93,
                check(
                    get(var(r#"clock"#), text(r#"timeMillis"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(3500.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_008_should_correctly_calculate_time_when_changing_the_prescale_value_at_runtime_native() {
    crate::run_native(
        case_008_should_correctly_calculate_time_when_changing_the_prescale_value_at_runtime(),
    );
}
