// SPDX-License-Identifier: MIT
// Copyright (c) Uri Shaked and contributors
// Generated by tools/convert.cjs. Source: src/peripherals/eeprom.spec.ts
use crate::scenario::*;
pub const IMPORTS: &[&str] = &[
    r#"CPU"#,
    r#"asmProgram"#,
    r#"TestProgramRunner"#,
    r#"AVREEPROM"#,
    r#"EEPROMMemoryBackend"#,
];
pub fn cases() -> Vec<Case> {
    vec![case_001_should_return_0xff_when_reading_from_an_empty_location(),case_002_should_return_the_value_stored_at_the_given_eeprom_address(),case_003_should_write_a_byte_to_the_given_eeprom_address(),case_004_should_not_erase_the_memory_when_writing_if_eepm1_is_high(),case_005_should_clear_the_eepe_bit_and_fire_an_interrupt_when_write_has_been_completed(),case_006_should_clear_the_fire_an_interrupt_when_there_is_a_pending_interrupt_and_the_interrupt_flag_is_enabl(),case_007_should_skip_the_write_if_eempe_is_clear(),case_008_should_skip_the_write_if_another_write_is_already_in_progress(),case_009_should_write_two_bytes_sucessfully(),case_010_should_only_erase_the_memory_when_eepm0_is_high()]
}

fn setup_0() -> Vec<Step> {
    vec![
        at(10, bind(r#"EECR"#, num(63.0))),
        at(11, bind(r#"EEDR"#, num(64.0))),
        at(12, bind(r#"EEARL"#, num(65.0))),
        at(13, bind(r#"EEARH"#, num(66.0))),
        at(14, bind(r#"SREG"#, num(95.0))),
        at(18, bind(r#"EERE"#, num(1.0))),
        at(19, bind(r#"EEPE"#, num(2.0))),
        at(20, bind(r#"EEMPE"#, num(4.0))),
        at(21, bind(r#"EERIE"#, num(8.0))),
        at(22, bind(r#"EEPM0"#, num(16.0))),
        at(23, bind(r#"EEPM1"#, num(32.0))),
    ]
}

pub fn case_001_should_return_0xff_when_reading_from_an_empty_location() -> Case {
    Case {
        source: r#"src/peripherals/eeprom.spec.ts"#,
        name: r#"EEPROM / Reading the EEPROM / should return 0xff when reading from an empty location"#,
        line: 28,
        assertions: 2,
        setup: setup_0(),
        body: vec![
            at(
                29,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(4096.0)])]),
                ),
            ),
            at(
                30,
                eval(new(
                    r#"AVREEPROM"#,
                    vec![
                        var(r#"cpu"#),
                        new(r#"EEPROMMemoryBackend"#, vec![num(1024.0)]),
                    ],
                )),
            ),
            at(
                31,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EEARL"#), num(0.0)],
                )),
            ),
            at(
                32,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EEARH"#), num(0.0)],
                )),
            ),
            at(
                33,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EECR"#), var(r#"EERE"#)],
                )),
            ),
            at(34, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                35,
                check(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(4.0)],
                ),
            ),
            at(
                36,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"EEDR"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(255.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_001_should_return_0xff_when_reading_from_an_empty_location_native() {
    crate::run_native(case_001_should_return_0xff_when_reading_from_an_empty_location());
}

pub fn case_002_should_return_the_value_stored_at_the_given_eeprom_address() -> Case {
    Case {
        source: r#"src/peripherals/eeprom.spec.ts"#,
        name: r#"EEPROM / Reading the EEPROM / should return the value stored at the given EEPROM address"#,
        line: 39,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                40,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(4096.0)])]),
                ),
            ),
            at(
                41,
                bind(
                    r#"eepromBackend"#,
                    new(r#"EEPROMMemoryBackend"#, vec![num(1024.0)]),
                ),
            ),
            at(
                42,
                eval(new(
                    r#"AVREEPROM"#,
                    vec![var(r#"cpu"#), var(r#"eepromBackend"#)],
                )),
            ),
            at(
                43,
                eval(assign(
                    get(get(var(r#"eepromBackend"#), text(r#"memory"#)), num(592.0)),
                    num(66.0),
                    r#"="#,
                )),
            ),
            at(
                44,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EEARL"#), num(80.0)],
                )),
            ),
            at(
                45,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EEARH"#), num(2.0)],
                )),
            ),
            at(
                46,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EECR"#), var(r#"EERE"#)],
                )),
            ),
            at(47, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                48,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"EEDR"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(66.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_002_should_return_the_value_stored_at_the_given_eeprom_address_native() {
    crate::run_native(case_002_should_return_the_value_stored_at_the_given_eeprom_address());
}

pub fn case_003_should_write_a_byte_to_the_given_eeprom_address() -> Case {
    Case {
        source: r#"src/peripherals/eeprom.spec.ts"#,
        name: r#"EEPROM / Writing to the EEPROM / should write a byte to the given EEPROM address"#,
        line: 53,
        assertions: 3,
        setup: setup_0(),
        body: vec![
            at(
                54,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(4096.0)])]),
                ),
            ),
            at(
                55,
                bind(
                    r#"eepromBackend"#,
                    new(r#"EEPROMMemoryBackend"#, vec![num(1024.0)]),
                ),
            ),
            at(
                56,
                eval(new(
                    r#"AVREEPROM"#,
                    vec![var(r#"cpu"#), var(r#"eepromBackend"#)],
                )),
            ),
            at(
                57,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EEDR"#), num(85.0)],
                )),
            ),
            at(
                58,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EEARL"#), num(15.0)],
                )),
            ),
            at(
                59,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EEARH"#), num(0.0)],
                )),
            ),
            at(
                60,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EECR"#), var(r#"EEMPE"#)],
                )),
            ),
            at(
                61,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EECR"#), var(r#"EEPE"#)],
                )),
            ),
            at(62, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                63,
                check(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(2.0)],
                ),
            ),
            at(
                64,
                check(
                    get(get(var(r#"eepromBackend"#), text(r#"memory"#)), num(15.0)),
                    r#"toEqual"#,
                    false,
                    vec![num(85.0)],
                ),
            ),
            at(
                65,
                check(
                    binary(
                        r#"&"#,
                        get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"EECR"#)),
                        var(r#"EEPE"#),
                    ),
                    r#"toEqual"#,
                    false,
                    vec![var(r#"EEPE"#)],
                ),
            ),
        ],
    }
}
#[test]
fn case_003_should_write_a_byte_to_the_given_eeprom_address_native() {
    crate::run_native(case_003_should_write_a_byte_to_the_given_eeprom_address());
}

pub fn case_004_should_not_erase_the_memory_when_writing_if_eepm1_is_high() -> Case {
    Case {
        source: r#"src/peripherals/eeprom.spec.ts"#,
        name: r#"EEPROM / Writing to the EEPROM / should not erase the memory when writing if EEPM1 is high"#,
        line: 68,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                70,
                destructure(
                    vec![
                        (r#"program"#, r#"program"#),
                        (r#"instructionCount"#, r#"instructionCount"#),
                    ],
                    call(
                        var(r#"asmProgram"#),
                        vec![template(vec![
                            text(
                                r#"
        ; register addresses
        _REPLACE TWSR, "#,
                            ),
                            binary(r#"-"#, var(r#"EECR"#), num(32.0)),
                            text(
                                r#"
        _REPLACE EEARL, "#,
                            ),
                            binary(r#"-"#, var(r#"EEARL"#), num(32.0)),
                            text(
                                r#"
        _REPLACE EEDR, "#,
                            ),
                            binary(r#"-"#, var(r#"EEDR"#), num(32.0)),
                            text(
                                r#"
        _REPLACE EECR, "#,
                            ),
                            binary(r#"-"#, var(r#"EECR"#), num(32.0)),
                            text(
                                r#"

        LDI r16, 0x55
        OUT EEDR, r16
        LDI r16, 9
        OUT EEARL, r16
        SBI EECR, 5     ; EECR |= EEPM1
        SBI EECR, 2     ; EECR |= EEMPE
        SBI EECR, 1     ; EECR |= EEPE
      "#,
                            ),
                        ])],
                    ),
                ),
            ),
            at(86, bind(r#"cpu"#, new(r#"CPU"#, vec![var(r#"program"#)]))),
            at(
                87,
                bind(
                    r#"eepromBackend"#,
                    new(r#"EEPROMMemoryBackend"#, vec![num(1024.0)]),
                ),
            ),
            at(
                88,
                eval(new(
                    r#"AVREEPROM"#,
                    vec![var(r#"cpu"#), var(r#"eepromBackend"#)],
                )),
            ),
            at(
                89,
                eval(assign(
                    get(get(var(r#"eepromBackend"#), text(r#"memory"#)), num(9.0)),
                    num(15.0),
                    r#"="#,
                )),
            ),
            at(
                91,
                bind(
                    r#"runner"#,
                    new(r#"TestProgramRunner"#, vec![var(r#"cpu"#)]),
                ),
            ),
            at(
                92,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![var(r#"instructionCount"#)],
                )),
            ),
            at(
                96,
                check(
                    get(get(var(r#"eepromBackend"#), text(r#"memory"#)), num(9.0)),
                    r#"toEqual"#,
                    false,
                    vec![num(5.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_004_should_not_erase_the_memory_when_writing_if_eepm1_is_high_native() {
    crate::run_native(case_004_should_not_erase_the_memory_when_writing_if_eepm1_is_high());
}

pub fn case_005_should_clear_the_eepe_bit_and_fire_an_interrupt_when_write_has_been_completed(
) -> Case {
    Case {
        source: r#"src/peripherals/eeprom.spec.ts"#,
        name: r#"EEPROM / Writing to the EEPROM / should clear the EEPE bit and fire an interrupt when write has been completed"#,
        line: 99,
        assertions: 5,
        setup: setup_0(),
        body: vec![
            at(
                100,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(4096.0)])]),
                ),
            ),
            at(
                101,
                bind(
                    r#"eepromBackend"#,
                    new(r#"EEPROMMemoryBackend"#, vec![num(1024.0)]),
                ),
            ),
            at(
                102,
                eval(new(
                    r#"AVREEPROM"#,
                    vec![var(r#"cpu"#), var(r#"eepromBackend"#)],
                )),
            ),
            at(
                103,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EEDR"#), num(85.0)],
                )),
            ),
            at(
                104,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EEARL"#), num(15.0)],
                )),
            ),
            at(
                105,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EEARH"#), num(0.0)],
                )),
            ),
            at(
                106,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EECR"#), var(r#"EEMPE"#)],
                )),
            ),
            at(
                107,
                eval(assign(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"SREG"#)),
                    num(128.0),
                    r#"="#,
                )),
            ),
            at(
                108,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"EECR"#),
                        binary(r#"|"#, var(r#"EEPE"#), var(r#"EERIE"#)),
                    ],
                )),
            ),
            at(
                109,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(1000.0),
                    r#"+="#,
                )),
            ),
            at(110, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                112,
                check(
                    binary(
                        r#"&"#,
                        get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"EECR"#)),
                        var(r#"EEPE"#),
                    ),
                    r#"toEqual"#,
                    false,
                    vec![var(r#"EEPE"#)],
                ),
            ),
            at(
                113,
                check(
                    get(var(r#"cpu"#), text(r#"pc"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
            at(
                114,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(10000000.0),
                    r#"+="#,
                )),
            ),
            at(116, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                117,
                check(
                    get(get(var(r#"eepromBackend"#), text(r#"memory"#)), num(15.0)),
                    r#"toEqual"#,
                    false,
                    vec![num(85.0)],
                ),
            ),
            at(
                118,
                check(
                    binary(
                        r#"&"#,
                        get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"EECR"#)),
                        var(r#"EEPE"#),
                    ),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
            at(
                119,
                check(
                    get(var(r#"cpu"#), text(r#"pc"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(44.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_005_should_clear_the_eepe_bit_and_fire_an_interrupt_when_write_has_been_completed_native() {
    crate::run_native(
        case_005_should_clear_the_eepe_bit_and_fire_an_interrupt_when_write_has_been_completed(),
    );
}

pub fn case_006_should_clear_the_fire_an_interrupt_when_there_is_a_pending_interrupt_and_the_interrupt_flag_is_enabl(
) -> Case {
    Case {
        source: r#"src/peripherals/eeprom.spec.ts"#,
        name: r#"EEPROM / Writing to the EEPROM / should clear the fire an interrupt when there is a pending interrupt and the interrupt flag is enabled (issue #110)"#,
        line: 122,
        assertions: 5,
        setup: setup_0(),
        body: vec![
            at(
                123,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(4096.0)])]),
                ),
            ),
            at(
                124,
                bind(
                    r#"eepromBackend"#,
                    new(r#"EEPROMMemoryBackend"#, vec![num(1024.0)]),
                ),
            ),
            at(
                125,
                eval(new(
                    r#"AVREEPROM"#,
                    vec![var(r#"cpu"#), var(r#"eepromBackend"#)],
                )),
            ),
            at(
                126,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EEDR"#), num(85.0)],
                )),
            ),
            at(
                127,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EEARL"#), num(15.0)],
                )),
            ),
            at(
                128,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EEARH"#), num(0.0)],
                )),
            ),
            at(
                129,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EECR"#), var(r#"EEMPE"#)],
                )),
            ),
            at(
                130,
                eval(assign(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"SREG"#)),
                    num(128.0),
                    r#"="#,
                )),
            ),
            at(
                131,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EECR"#), var(r#"EEPE"#)],
                )),
            ),
            at(
                132,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(1000.0),
                    r#"+="#,
                )),
            ),
            at(133, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                135,
                check(
                    binary(
                        r#"&"#,
                        get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"EECR"#)),
                        var(r#"EEPE"#),
                    ),
                    r#"toEqual"#,
                    false,
                    vec![var(r#"EEPE"#)],
                ),
            ),
            at(
                136,
                check(
                    get(var(r#"cpu"#), text(r#"pc"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
            at(
                137,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(10000000.0),
                    r#"+="#,
                )),
            ),
            at(139, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                140,
                check(
                    get(get(var(r#"eepromBackend"#), text(r#"memory"#)), num(15.0)),
                    r#"toEqual"#,
                    false,
                    vec![num(85.0)],
                ),
            ),
            at(
                141,
                check(
                    binary(
                        r#"&"#,
                        get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"EECR"#)),
                        var(r#"EEPE"#),
                    ),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
            at(
                142,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EECR"#), var(r#"EERIE"#)],
                )),
            ),
            at(143, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                144,
                check(
                    get(var(r#"cpu"#), text(r#"pc"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(44.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_006_should_clear_the_fire_an_interrupt_when_there_is_a_pending_interrupt_and_the_interrupt_flag_is_enabl_native(
) {
    crate::run_native(case_006_should_clear_the_fire_an_interrupt_when_there_is_a_pending_interrupt_and_the_interrupt_flag_is_enabl());
}

pub fn case_007_should_skip_the_write_if_eempe_is_clear() -> Case {
    Case {
        source: r#"src/peripherals/eeprom.spec.ts"#,
        name: r#"EEPROM / Writing to the EEPROM / should skip the write if EEMPE is clear"#,
        line: 147,
        assertions: 3,
        setup: setup_0(),
        body: vec![
            at(
                148,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(4096.0)])]),
                ),
            ),
            at(
                149,
                bind(
                    r#"eepromBackend"#,
                    new(r#"EEPROMMemoryBackend"#, vec![num(1024.0)]),
                ),
            ),
            at(
                150,
                eval(new(
                    r#"AVREEPROM"#,
                    vec![var(r#"cpu"#), var(r#"eepromBackend"#)],
                )),
            ),
            at(
                151,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EEDR"#), num(85.0)],
                )),
            ),
            at(
                152,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EEARL"#), num(15.0)],
                )),
            ),
            at(
                153,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EEARH"#), num(0.0)],
                )),
            ),
            at(
                154,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EECR"#), var(r#"EEMPE"#)],
                )),
            ),
            at(
                155,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(8.0),
                    r#"="#,
                )),
            ),
            at(156, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                157,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EECR"#), var(r#"EEPE"#)],
                )),
            ),
            at(158, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                160,
                check(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(8.0)],
                ),
            ),
            at(
                161,
                check(
                    get(get(var(r#"eepromBackend"#), text(r#"memory"#)), num(15.0)),
                    r#"toEqual"#,
                    false,
                    vec![num(255.0)],
                ),
            ),
            at(
                162,
                check(
                    binary(
                        r#"&"#,
                        get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"EECR"#)),
                        var(r#"EEPE"#),
                    ),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_007_should_skip_the_write_if_eempe_is_clear_native() {
    crate::run_native(case_007_should_skip_the_write_if_eempe_is_clear());
}

pub fn case_008_should_skip_the_write_if_another_write_is_already_in_progress() -> Case {
    Case {
        source: r#"src/peripherals/eeprom.spec.ts"#,
        name: r#"EEPROM / Writing to the EEPROM / should skip the write if another write is already in progress"#,
        line: 165,
        assertions: 4,
        setup: setup_0(),
        body: vec![
            at(
                166,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(4096.0)])]),
                ),
            ),
            at(
                167,
                bind(
                    r#"eepromBackend"#,
                    new(r#"EEPROMMemoryBackend"#, vec![num(1024.0)]),
                ),
            ),
            at(
                168,
                eval(new(
                    r#"AVREEPROM"#,
                    vec![var(r#"cpu"#), var(r#"eepromBackend"#)],
                )),
            ),
            at(
                171,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EEDR"#), num(85.0)],
                )),
            ),
            at(
                172,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EEARL"#), num(15.0)],
                )),
            ),
            at(
                173,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EEARH"#), num(0.0)],
                )),
            ),
            at(
                174,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EECR"#), var(r#"EEMPE"#)],
                )),
            ),
            at(
                175,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EECR"#), var(r#"EEPE"#)],
                )),
            ),
            at(176, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                177,
                check(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(2.0)],
                ),
            ),
            at(
                180,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EEDR"#), num(102.0)],
                )),
            ),
            at(
                181,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EEARL"#), num(16.0)],
                )),
            ),
            at(
                182,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EEARH"#), num(0.0)],
                )),
            ),
            at(
                183,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EECR"#), var(r#"EEMPE"#)],
                )),
            ),
            at(
                184,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EECR"#), var(r#"EEPE"#)],
                )),
            ),
            at(185, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                188,
                check(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(2.0)],
                ),
            ),
            at(
                189,
                check(
                    get(get(var(r#"eepromBackend"#), text(r#"memory"#)), num(15.0)),
                    r#"toEqual"#,
                    false,
                    vec![num(85.0)],
                ),
            ),
            at(
                190,
                check(
                    get(get(var(r#"eepromBackend"#), text(r#"memory"#)), num(16.0)),
                    r#"toEqual"#,
                    false,
                    vec![num(255.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_008_should_skip_the_write_if_another_write_is_already_in_progress_native() {
    crate::run_native(case_008_should_skip_the_write_if_another_write_is_already_in_progress());
}

pub fn case_009_should_write_two_bytes_sucessfully() -> Case {
    Case {
        source: r#"src/peripherals/eeprom.spec.ts"#,
        name: r#"EEPROM / Writing to the EEPROM / should write two bytes sucessfully"#,
        line: 193,
        assertions: 4,
        setup: setup_0(),
        body: vec![
            at(
                194,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(4096.0)])]),
                ),
            ),
            at(
                195,
                bind(
                    r#"eepromBackend"#,
                    new(r#"EEPROMMemoryBackend"#, vec![num(1024.0)]),
                ),
            ),
            at(
                196,
                eval(new(
                    r#"AVREEPROM"#,
                    vec![var(r#"cpu"#), var(r#"eepromBackend"#)],
                )),
            ),
            at(
                199,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EEDR"#), num(85.0)],
                )),
            ),
            at(
                200,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EEARL"#), num(15.0)],
                )),
            ),
            at(
                201,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EEARH"#), num(0.0)],
                )),
            ),
            at(
                202,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EECR"#), var(r#"EEMPE"#)],
                )),
            ),
            at(
                203,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EECR"#), var(r#"EEPE"#)],
                )),
            ),
            at(204, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                205,
                check(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(2.0)],
                ),
            ),
            at(
                208,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(10000000.0),
                    r#"+="#,
                )),
            ),
            at(209, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                212,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EEDR"#), num(102.0)],
                )),
            ),
            at(
                213,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EEARL"#), num(16.0)],
                )),
            ),
            at(
                214,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EEARH"#), num(0.0)],
                )),
            ),
            at(
                215,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EECR"#), var(r#"EEMPE"#)],
                )),
            ),
            at(
                216,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"EECR"#), var(r#"EEPE"#)],
                )),
            ),
            at(217, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                220,
                check(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(10000004.0)],
                ),
            ),
            at(
                221,
                check(
                    get(get(var(r#"eepromBackend"#), text(r#"memory"#)), num(15.0)),
                    r#"toEqual"#,
                    false,
                    vec![num(85.0)],
                ),
            ),
            at(
                222,
                check(
                    get(get(var(r#"eepromBackend"#), text(r#"memory"#)), num(16.0)),
                    r#"toEqual"#,
                    false,
                    vec![num(102.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_009_should_write_two_bytes_sucessfully_native() {
    crate::run_native(case_009_should_write_two_bytes_sucessfully());
}

pub fn case_010_should_only_erase_the_memory_when_eepm0_is_high() -> Case {
    Case {
        source: r#"src/peripherals/eeprom.spec.ts"#,
        name: r#"EEPROM / EEPROM erase / should only erase the memory when EEPM0 is high"#,
        line: 227,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                229,
                destructure(
                    vec![
                        (r#"program"#, r#"program"#),
                        (r#"instructionCount"#, r#"instructionCount"#),
                    ],
                    call(
                        var(r#"asmProgram"#),
                        vec![template(vec![
                            text(
                                r#"
          ; register addresses
          _REPLACE EEARL, "#,
                            ),
                            binary(r#"-"#, var(r#"EEARL"#), num(32.0)),
                            text(
                                r#"
          _REPLACE EEDR, "#,
                            ),
                            binary(r#"-"#, var(r#"EEDR"#), num(32.0)),
                            text(
                                r#"
          _REPLACE EECR, "#,
                            ),
                            binary(r#"-"#, var(r#"EECR"#), num(32.0)),
                            text(
                                r#"

          LDI r16, 0x55
          OUT EEDR, r16
          LDI r16, 9
          OUT EEARL, r16
          SBI EECR, 4     ; EECR |= EEPM0
          SBI EECR, 2     ; EECR |= EEMPE
          SBI EECR, 1     ; EECR |= EEPE
        "#,
                            ),
                        ])],
                    ),
                ),
            ),
            at(244, bind(r#"cpu"#, new(r#"CPU"#, vec![var(r#"program"#)]))),
            at(
                245,
                bind(
                    r#"eepromBackend"#,
                    new(r#"EEPROMMemoryBackend"#, vec![num(1024.0)]),
                ),
            ),
            at(
                246,
                eval(new(
                    r#"AVREEPROM"#,
                    vec![var(r#"cpu"#), var(r#"eepromBackend"#)],
                )),
            ),
            at(
                247,
                eval(assign(
                    get(get(var(r#"eepromBackend"#), text(r#"memory"#)), num(9.0)),
                    num(34.0),
                    r#"="#,
                )),
            ),
            at(
                249,
                bind(
                    r#"runner"#,
                    new(r#"TestProgramRunner"#, vec![var(r#"cpu"#)]),
                ),
            ),
            at(
                250,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![var(r#"instructionCount"#)],
                )),
            ),
            at(
                252,
                check(
                    get(get(var(r#"eepromBackend"#), text(r#"memory"#)), num(9.0)),
                    r#"toEqual"#,
                    false,
                    vec![num(255.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_010_should_only_erase_the_memory_when_eepm0_is_high_native() {
    crate::run_native(case_010_should_only_erase_the_memory_when_eepm0_is_high());
}
