// SPDX-License-Identifier: MIT
// Copyright (c) Uri Shaked and contributors
// Generated by tools/convert.cjs. Source: src/peripherals/spi.spec.ts
use crate::scenario::*;
pub const IMPORTS: &[&str] = &[
    r#"CPU"#,
    r#"asmProgram"#,
    r#"TestProgramRunner"#,
    r#"AVRSPI"#,
    r#"spiConfig"#,
];
pub fn cases() -> Vec<Case> {
    vec![case_001_should_correctly_calculate_the_frequency_based_on_spcr_spst_values(),case_002_should_correctly_report_the_data_order_msb_lsb_first_based_on_spcr_value(),case_003_should_correctly_report_the_spi_mode_based_on_spcr_value(),case_004_should_indicate_slave_master_operation_based_on_spcr_value(),case_005_should_call_the_onbytetransfer_callback_when_initiating_an_spi_trasfer_by_writing_to_spdr(),case_006_should_ignore_spdr_writes_when_the_spe_bit_in_spcr_is_clear(),case_007_should_transmit_a_byte_successfully_integration(),case_008_should_set_the_wcol_bit_in_spsr_if_writing_to_spdr_while_spi_is_already_transmitting(),case_009_should_clear_the_spif_bit_and_fire_an_interrupt_when_spi_transfer_completes(),case_010_should_fire_a_pending_spi_interrupt_when_spie_flag_is_set(),case_011_should_should_only_update_spdr_when_tranfer_finishes_double_buffering()]
}

fn setup_0() -> Vec<Step> {
    vec![
        at(9, bind(r#"FREQ_16MHZ"#, num(16000000.0))),
        at(12, bind(r#"R17"#, num(17.0))),
        at(13, bind(r#"SREG"#, num(95.0))),
        at(16, bind(r#"SPCR"#, num(76.0))),
        at(17, bind(r#"SPSR"#, num(77.0))),
        at(18, bind(r#"SPDR"#, num(78.0))),
        at(21, bind(r#"SPR0"#, num(1.0))),
        at(22, bind(r#"SPR1"#, num(2.0))),
        at(23, bind(r#"CPOL"#, num(4.0))),
        at(24, bind(r#"CPHA"#, num(8.0))),
        at(25, bind(r#"MSTR"#, num(16.0))),
        at(26, bind(r#"DORD"#, num(32.0))),
        at(27, bind(r#"SPE"#, num(64.0))),
        at(28, bind(r#"SPIE"#, num(128.0))),
        at(29, bind(r#"WCOL"#, num(64.0))),
        at(30, bind(r#"SPIF"#, num(128.0))),
        at(31, bind(r#"SPI2X"#, num(1.0))),
    ]
}

pub fn case_001_should_correctly_calculate_the_frequency_based_on_spcr_spst_values() -> Case {
    Case {
        source: r#"src/peripherals/spi.spec.ts"#,
        name: r#"SPI / should correctly calculate the frequency based on SPCR/SPST values"#,
        line: 34,
        assertions: 8,
        setup: setup_0(),
        body: vec![
            at(
                35,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                36,
                bind(
                    r#"spi"#,
                    new(
                        r#"AVRSPI"#,
                        vec![var(r#"cpu"#), var(r#"spiConfig"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                42,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"SPSR"#), num(0.0)],
                )),
            ),
            at(
                43,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"SPCR"#), num(0.0)],
                )),
            ),
            at(
                44,
                check(
                    get(var(r#"spi"#), text(r#"spiFrequency"#)),
                    r#"toEqual"#,
                    false,
                    vec![binary(r#"/"#, var(r#"FREQ_16MHZ"#), num(4.0))],
                ),
            ),
            at(
                45,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"SPCR"#), var(r#"SPR0"#)],
                )),
            ),
            at(
                46,
                check(
                    get(var(r#"spi"#), text(r#"spiFrequency"#)),
                    r#"toEqual"#,
                    false,
                    vec![binary(r#"/"#, var(r#"FREQ_16MHZ"#), num(16.0))],
                ),
            ),
            at(
                47,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"SPCR"#), var(r#"SPR1"#)],
                )),
            ),
            at(
                48,
                check(
                    get(var(r#"spi"#), text(r#"spiFrequency"#)),
                    r#"toEqual"#,
                    false,
                    vec![binary(r#"/"#, var(r#"FREQ_16MHZ"#), num(64.0))],
                ),
            ),
            at(
                49,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"SPCR"#),
                        binary(r#"|"#, var(r#"SPR1"#), var(r#"SPR0"#)),
                    ],
                )),
            ),
            at(
                50,
                check(
                    get(var(r#"spi"#), text(r#"spiFrequency"#)),
                    r#"toEqual"#,
                    false,
                    vec![binary(r#"/"#, var(r#"FREQ_16MHZ"#), num(128.0))],
                ),
            ),
            at(
                53,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"SPSR"#), var(r#"SPI2X"#)],
                )),
            ),
            at(
                54,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"SPCR"#), num(0.0)],
                )),
            ),
            at(
                55,
                check(
                    get(var(r#"spi"#), text(r#"spiFrequency"#)),
                    r#"toEqual"#,
                    false,
                    vec![binary(r#"/"#, var(r#"FREQ_16MHZ"#), num(2.0))],
                ),
            ),
            at(
                56,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"SPCR"#), var(r#"SPR0"#)],
                )),
            ),
            at(
                57,
                check(
                    get(var(r#"spi"#), text(r#"spiFrequency"#)),
                    r#"toEqual"#,
                    false,
                    vec![binary(r#"/"#, var(r#"FREQ_16MHZ"#), num(8.0))],
                ),
            ),
            at(
                58,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"SPCR"#), var(r#"SPR1"#)],
                )),
            ),
            at(
                59,
                check(
                    get(var(r#"spi"#), text(r#"spiFrequency"#)),
                    r#"toEqual"#,
                    false,
                    vec![binary(r#"/"#, var(r#"FREQ_16MHZ"#), num(32.0))],
                ),
            ),
            at(
                60,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"SPCR"#),
                        binary(r#"|"#, var(r#"SPR1"#), var(r#"SPR0"#)),
                    ],
                )),
            ),
            at(
                61,
                check(
                    get(var(r#"spi"#), text(r#"spiFrequency"#)),
                    r#"toEqual"#,
                    false,
                    vec![binary(r#"/"#, var(r#"FREQ_16MHZ"#), num(64.0))],
                ),
            ),
        ],
    }
}
#[test]
fn case_001_should_correctly_calculate_the_frequency_based_on_spcr_spst_values_native() {
    crate::run_native(
        case_001_should_correctly_calculate_the_frequency_based_on_spcr_spst_values(),
    );
}

pub fn case_002_should_correctly_report_the_data_order_msb_lsb_first_based_on_spcr_value() -> Case {
    Case {
        source: r#"src/peripherals/spi.spec.ts"#,
        name: r#"SPI / should correctly report the data order (MSB/LSB first), based on SPCR value"#,
        line: 64,
        assertions: 2,
        setup: setup_0(),
        body: vec![
            at(
                65,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                66,
                bind(
                    r#"spi"#,
                    new(
                        r#"AVRSPI"#,
                        vec![var(r#"cpu"#), var(r#"spiConfig"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                68,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"SPCR"#), num(0.0)],
                )),
            ),
            at(
                69,
                check(
                    get(var(r#"spi"#), text(r#"dataOrder"#)),
                    r#"toBe"#,
                    false,
                    vec![text(r#"msbFirst"#)],
                ),
            ),
            at(
                71,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"SPCR"#), var(r#"DORD"#)],
                )),
            ),
            at(
                72,
                check(
                    get(var(r#"spi"#), text(r#"dataOrder"#)),
                    r#"toBe"#,
                    false,
                    vec![text(r#"lsbFirst"#)],
                ),
            ),
        ],
    }
}
#[test]
fn case_002_should_correctly_report_the_data_order_msb_lsb_first_based_on_spcr_value_native() {
    crate::run_native(
        case_002_should_correctly_report_the_data_order_msb_lsb_first_based_on_spcr_value(),
    );
}

pub fn case_003_should_correctly_report_the_spi_mode_based_on_spcr_value() -> Case {
    Case {
        source: r#"src/peripherals/spi.spec.ts"#,
        name: r#"SPI / should correctly report the SPI mode, based on SPCR value"#,
        line: 75,
        assertions: 4,
        setup: setup_0(),
        body: vec![
            at(
                76,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                77,
                bind(
                    r#"spi"#,
                    new(
                        r#"AVRSPI"#,
                        vec![var(r#"cpu"#), var(r#"spiConfig"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                80,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"SPCR"#), num(0.0)],
                )),
            ),
            at(
                81,
                check(
                    get(var(r#"spi"#), text(r#"spiMode"#)),
                    r#"toBe"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
            at(
                83,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"SPCR"#), var(r#"CPHA"#)],
                )),
            ),
            at(
                84,
                check(
                    get(var(r#"spi"#), text(r#"spiMode"#)),
                    r#"toBe"#,
                    false,
                    vec![num(1.0)],
                ),
            ),
            at(
                86,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"SPCR"#), var(r#"CPOL"#)],
                )),
            ),
            at(
                87,
                check(
                    get(var(r#"spi"#), text(r#"spiMode"#)),
                    r#"toBe"#,
                    false,
                    vec![num(2.0)],
                ),
            ),
            at(
                89,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"SPCR"#),
                        binary(r#"|"#, var(r#"CPOL"#), var(r#"CPHA"#)),
                    ],
                )),
            ),
            at(
                90,
                check(
                    get(var(r#"spi"#), text(r#"spiMode"#)),
                    r#"toBe"#,
                    false,
                    vec![num(3.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_003_should_correctly_report_the_spi_mode_based_on_spcr_value_native() {
    crate::run_native(case_003_should_correctly_report_the_spi_mode_based_on_spcr_value());
}

pub fn case_004_should_indicate_slave_master_operation_based_on_spcr_value() -> Case {
    Case {
        source: r#"src/peripherals/spi.spec.ts"#,
        name: r#"SPI / should indicate slave/master operation, based on SPCR value"#,
        line: 93,
        assertions: 2,
        setup: setup_0(),
        body: vec![
            at(
                94,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                95,
                bind(
                    r#"spi"#,
                    new(
                        r#"AVRSPI"#,
                        vec![var(r#"cpu"#), var(r#"spiConfig"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                97,
                check(
                    get(var(r#"spi"#), text(r#"isMaster"#)),
                    r#"toBe"#,
                    false,
                    vec![boolean(false)],
                ),
            ),
            at(
                99,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"SPCR"#), var(r#"MSTR"#)],
                )),
            ),
            at(
                100,
                check(
                    get(var(r#"spi"#), text(r#"isMaster"#)),
                    r#"toBe"#,
                    false,
                    vec![boolean(true)],
                ),
            ),
        ],
    }
}
#[test]
fn case_004_should_indicate_slave_master_operation_based_on_spcr_value_native() {
    crate::run_native(case_004_should_indicate_slave_master_operation_based_on_spcr_value());
}

pub fn case_005_should_call_the_onbytetransfer_callback_when_initiating_an_spi_trasfer_by_writing_to_spdr(
) -> Case {
    Case {
        source: r#"src/peripherals/spi.spec.ts"#,
        name: r#"SPI / should call the `onByteTransfer` callback when initiating an SPI trasfer by writing to SPDR"#,
        line: 103,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                104,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                105,
                bind(
                    r#"spi"#,
                    new(
                        r#"AVRSPI"#,
                        vec![var(r#"cpu"#), var(r#"spiConfig"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                106,
                eval(assign(
                    get(var(r#"spi"#), text(r#"onByte"#)),
                    call(get(var(r#"vi"#), text(r#"fn"#)), vec![]),
                    r#"="#,
                )),
            ),
            at(
                108,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"SPCR"#),
                        binary(r#"|"#, var(r#"SPE"#), var(r#"MSTR"#)),
                    ],
                )),
            ),
            at(
                109,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"SPDR"#), num(143.0)],
                )),
            ),
            at(
                111,
                check(
                    get(var(r#"spi"#), text(r#"onByte"#)),
                    r#"toHaveBeenCalledWith"#,
                    false,
                    vec![num(143.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_005_should_call_the_onbytetransfer_callback_when_initiating_an_spi_trasfer_by_writing_to_spdr_native(
) {
    crate::run_native(case_005_should_call_the_onbytetransfer_callback_when_initiating_an_spi_trasfer_by_writing_to_spdr());
}

pub fn case_006_should_ignore_spdr_writes_when_the_spe_bit_in_spcr_is_clear() -> Case {
    Case {
        source: r#"src/peripherals/spi.spec.ts"#,
        name: r#"SPI / should ignore SPDR writes when the SPE bit in SPCR is clear"#,
        line: 114,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                115,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                116,
                bind(
                    r#"spi"#,
                    new(
                        r#"AVRSPI"#,
                        vec![var(r#"cpu"#), var(r#"spiConfig"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                117,
                eval(assign(
                    get(var(r#"spi"#), text(r#"onByte"#)),
                    call(get(var(r#"vi"#), text(r#"fn"#)), vec![]),
                    r#"="#,
                )),
            ),
            at(
                119,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"SPCR"#), var(r#"MSTR"#)],
                )),
            ),
            at(
                120,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"SPDR"#), num(143.0)],
                )),
            ),
            at(
                122,
                check(
                    get(var(r#"spi"#), text(r#"onByte"#)),
                    r#"toHaveBeenCalled"#,
                    true,
                    vec![],
                ),
            ),
        ],
    }
}
#[test]
fn case_006_should_ignore_spdr_writes_when_the_spe_bit_in_spcr_is_clear_native() {
    crate::run_native(case_006_should_ignore_spdr_writes_when_the_spe_bit_in_spcr_is_clear());
}

pub fn case_007_should_transmit_a_byte_successfully_integration() -> Case {
    Case {
        source: r#"src/peripherals/spi.spec.ts"#,
        name: r#"SPI / should transmit a byte successfully (integration)"#,
        line: 125,
        assertions: 3,
        setup: setup_0(),
        body: vec![
            at(
                127,
                destructure(
                    vec![(r#"program"#, r#"program"#)],
                    call(
                        var(r#"asmProgram"#),
                        vec![template(vec![
                            text(
                                r#"
      ; register addresses
      _REPLACE SPCR, "#,
                            ),
                            binary(r#"-"#, var(r#"SPCR"#), num(32.0)),
                            text(
                                r#"
      _REPLACE SPDR, "#,
                            ),
                            binary(r#"-"#, var(r#"SPDR"#), num(32.0)),
                            text(
                                r#"
      _REPLACE SPSR, "#,
                            ),
                            binary(r#"-"#, var(r#"SPSR"#), num(32.0)),
                            text(
                                r#"
      _REPLACE DDR_SPI, 0x4 ; PORTB

      SPI_MasterInit:
        ; Set MOSI and SCK output, all others input
        LDI r17, 0x28
        OUT DDR_SPI, r17
    
        ; Enable SPI, Master, set clock rate fck/16
        LDI r17, 0x51   ; (1<<SPE)|(1<<MSTR)|(1<<SPR0)
        OUT SPCR, r17

      SPI_MasterTransmit:
        LDI r16, 0xb8 ; byte to transmit
        OUT SPDR, r16

      Wait_Transmit:
        IN r16, SPSR
        SBRS r16, 7
        RJMP Wait_Transmit
      
      ; Now read the result into r17
        IN r17, SPDR
        BREAK
    "#,
                            ),
                        ])],
                    ),
                ),
            ),
            at(157, bind(r#"cpu"#, new(r#"CPU"#, vec![var(r#"program"#)]))),
            at(
                158,
                bind(
                    r#"spi"#,
                    new(
                        r#"AVRSPI"#,
                        vec![var(r#"cpu"#), var(r#"spiConfig"#), num(16000000.0)],
                    ),
                ),
            ),
            at(160, bind(r#"byteReceivedFromAsmCode"#, Expr::Null)),
            at(
                162,
                eval(assign(
                    get(var(r#"spi"#), text(r#"onByte"#)),
                    function(
                        vec![param(r#"value"#, false)],
                        vec![
                            at(
                                163,
                                eval(assign(
                                    var(r#"byteReceivedFromAsmCode"#),
                                    var(r#"value"#),
                                    r#"="#,
                                )),
                            ),
                            at(
                                164,
                                eval(call(
                                    get(var(r#"cpu"#), text(r#"addClockEvent"#)),
                                    vec![
                                        function(
                                            vec![],
                                            vec![at(
                                                164,
                                                ret(call(
                                                    get(var(r#"spi"#), text(r#"completeTransfer"#)),
                                                    vec![num(91.0)],
                                                )),
                                            )],
                                        ),
                                        get(var(r#"spi"#), text(r#"transferCycles"#)),
                                    ],
                                )),
                            ),
                        ],
                    ),
                    r#"="#,
                )),
            ),
            at(
                167,
                bind(
                    r#"runner"#,
                    new(
                        r#"TestProgramRunner"#,
                        vec![
                            var(r#"cpu"#),
                            function(vec![], vec![at(167, ret(num(0.0)))]),
                        ],
                    ),
                ),
            ),
            at(
                168,
                eval(call(get(var(r#"runner"#), text(r#"runToBreak"#)), vec![])),
            ),
            at(
                171,
                check(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    r#"toBeGreaterThanOrEqual"#,
                    false,
                    vec![num(128.0)],
                ),
            ),
            at(
                173,
                check(
                    var(r#"byteReceivedFromAsmCode"#),
                    r#"toEqual"#,
                    false,
                    vec![num(184.0)],
                ),
            ),
            at(
                174,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"R17"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(91.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_007_should_transmit_a_byte_successfully_integration_native() {
    crate::run_native(case_007_should_transmit_a_byte_successfully_integration());
}

pub fn case_008_should_set_the_wcol_bit_in_spsr_if_writing_to_spdr_while_spi_is_already_transmitting(
) -> Case {
    Case {
        source: r#"src/peripherals/spi.spec.ts"#,
        name: r#"SPI / should set the WCOL bit in SPSR if writing to SPDR while SPI is already transmitting"#,
        line: 177,
        assertions: 2,
        setup: setup_0(),
        body: vec![
            at(
                178,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                179,
                eval(new(
                    r#"AVRSPI"#,
                    vec![var(r#"cpu"#), var(r#"spiConfig"#), var(r#"FREQ_16MHZ"#)],
                )),
            ),
            at(
                181,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"SPCR"#),
                        binary(r#"|"#, var(r#"SPE"#), var(r#"MSTR"#)),
                    ],
                )),
            ),
            at(
                182,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"SPDR"#), num(80.0)],
                )),
            ),
            at(183, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                184,
                check(
                    binary(
                        r#"&"#,
                        call(
                            get(var(r#"cpu"#), text(r#"readData"#)),
                            vec![var(r#"SPSR"#)],
                        ),
                        var(r#"WCOL"#),
                    ),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
            at(
                186,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"SPDR"#), num(81.0)],
                )),
            ),
            at(
                187,
                check(
                    binary(
                        r#"&"#,
                        call(
                            get(var(r#"cpu"#), text(r#"readData"#)),
                            vec![var(r#"SPSR"#)],
                        ),
                        var(r#"WCOL"#),
                    ),
                    r#"toEqual"#,
                    false,
                    vec![var(r#"WCOL"#)],
                ),
            ),
        ],
    }
}
#[test]
fn case_008_should_set_the_wcol_bit_in_spsr_if_writing_to_spdr_while_spi_is_already_transmitting_native(
) {
    crate::run_native(case_008_should_set_the_wcol_bit_in_spsr_if_writing_to_spdr_while_spi_is_already_transmitting());
}

pub fn case_009_should_clear_the_spif_bit_and_fire_an_interrupt_when_spi_transfer_completes() -> Case
{
    Case {
        source: r#"src/peripherals/spi.spec.ts"#,
        name: r#"SPI / should clear the SPIF bit and fire an interrupt when SPI transfer completes"#,
        line: 190,
        assertions: 3,
        setup: setup_0(),
        body: vec![
            at(
                191,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                192,
                eval(new(
                    r#"AVRSPI"#,
                    vec![var(r#"cpu"#), var(r#"spiConfig"#), var(r#"FREQ_16MHZ"#)],
                )),
            ),
            at(
                194,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"SPCR"#),
                        binary(
                            r#"|"#,
                            binary(r#"|"#, var(r#"SPE"#), var(r#"SPIE"#)),
                            var(r#"MSTR"#),
                        ),
                    ],
                )),
            ),
            at(
                195,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"SPDR"#), num(80.0)],
                )),
            ),
            at(
                196,
                eval(assign(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"SREG"#)),
                    num(128.0),
                    r#"="#,
                )),
            ),
            at(
                199,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(10.0),
                    r#"+="#,
                )),
            ),
            at(200, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                201,
                check(
                    get(var(r#"cpu"#), text(r#"pc"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
            at(
                204,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(100.0),
                    r#"+="#,
                )),
            ),
            at(205, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                206,
                check(
                    binary(
                        r#"&"#,
                        get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"SPSR"#)),
                        var(r#"SPIF"#),
                    ),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
            at(
                207,
                check(
                    get(var(r#"cpu"#), text(r#"pc"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(34.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_009_should_clear_the_spif_bit_and_fire_an_interrupt_when_spi_transfer_completes_native() {
    crate::run_native(
        case_009_should_clear_the_spif_bit_and_fire_an_interrupt_when_spi_transfer_completes(),
    );
}

pub fn case_010_should_fire_a_pending_spi_interrupt_when_spie_flag_is_set() -> Case {
    Case {
        source: r#"src/peripherals/spi.spec.ts"#,
        name: r#"SPI / should fire a pending SPI interrupt when SPIE flag is set"#,
        line: 210,
        assertions: 4,
        setup: setup_0(),
        body: vec![
            at(
                211,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                212,
                eval(new(
                    r#"AVRSPI"#,
                    vec![var(r#"cpu"#), var(r#"spiConfig"#), var(r#"FREQ_16MHZ"#)],
                )),
            ),
            at(
                214,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"SPCR"#),
                        binary(r#"|"#, var(r#"SPE"#), var(r#"MSTR"#)),
                    ],
                )),
            ),
            at(
                215,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"SPDR"#), num(80.0)],
                )),
            ),
            at(
                216,
                eval(assign(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"SREG"#)),
                    num(128.0),
                    r#"="#,
                )),
            ),
            at(
                219,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(64.0),
                    r#"+="#,
                )),
            ),
            at(220, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                222,
                check(
                    binary(
                        r#"&"#,
                        get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"SPSR"#)),
                        var(r#"SPIF"#),
                    ),
                    r#"toEqual"#,
                    false,
                    vec![var(r#"SPIF"#)],
                ),
            ),
            at(
                223,
                check(
                    get(var(r#"cpu"#), text(r#"pc"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
            at(
                226,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"SPCR"#),
                        binary(
                            r#"|"#,
                            binary(r#"|"#, var(r#"SPE"#), var(r#"MSTR"#)),
                            var(r#"SPIE"#),
                        ),
                    ],
                )),
            ),
            at(227, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                228,
                check(
                    get(var(r#"cpu"#), text(r#"pc"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(34.0)],
                ),
            ),
            at(
                229,
                check(
                    binary(
                        r#"&"#,
                        get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"SPSR"#)),
                        var(r#"SPIF"#),
                    ),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_010_should_fire_a_pending_spi_interrupt_when_spie_flag_is_set_native() {
    crate::run_native(case_010_should_fire_a_pending_spi_interrupt_when_spie_flag_is_set());
}

pub fn case_011_should_should_only_update_spdr_when_tranfer_finishes_double_buffering() -> Case {
    Case {
        source: r#"src/peripherals/spi.spec.ts"#,
        name: r#"SPI / should should only update SPDR when tranfer finishes (double buffering)"#,
        line: 232,
        assertions: 2,
        setup: setup_0(),
        body: vec![
            at(
                233,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                234,
                bind(
                    r#"spi"#,
                    new(
                        r#"AVRSPI"#,
                        vec![var(r#"cpu"#), var(r#"spiConfig"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                235,
                eval(assign(
                    get(var(r#"spi"#), text(r#"onByte"#)),
                    function(
                        vec![],
                        vec![at(
                            236,
                            eval(call(
                                get(var(r#"cpu"#), text(r#"addClockEvent"#)),
                                vec![
                                    function(
                                        vec![],
                                        vec![at(
                                            236,
                                            ret(call(
                                                get(var(r#"spi"#), text(r#"completeTransfer"#)),
                                                vec![num(136.0)],
                                            )),
                                        )],
                                    ),
                                    get(var(r#"spi"#), text(r#"transferCycles"#)),
                                ],
                            )),
                        )],
                    ),
                    r#"="#,
                )),
            ),
            at(
                239,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"SPCR"#),
                        binary(r#"|"#, var(r#"SPE"#), var(r#"MSTR"#)),
                    ],
                )),
            ),
            at(
                240,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"SPDR"#), num(143.0)],
                )),
            ),
            at(
                242,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(10.0),
                    r#"="#,
                )),
            ),
            at(243, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                244,
                check(
                    call(
                        get(var(r#"cpu"#), text(r#"readData"#)),
                        vec![var(r#"SPDR"#)],
                    ),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
            at(
                246,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(32.0),
                    r#"="#,
                )),
            ),
            at(247, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                248,
                check(
                    call(
                        get(var(r#"cpu"#), text(r#"readData"#)),
                        vec![var(r#"SPDR"#)],
                    ),
                    r#"toEqual"#,
                    false,
                    vec![num(136.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_011_should_should_only_update_spdr_when_tranfer_finishes_double_buffering_native() {
    crate::run_native(
        case_011_should_should_only_update_spdr_when_tranfer_finishes_double_buffering(),
    );
}
