// SPDX-License-Identifier: MIT
// Copyright (c) Uri Shaked and contributors
// Generated by tools/convert.cjs. Source: src/peripherals/twi.spec.ts
use crate::scenario::*;
pub const IMPORTS: &[&str] = &[
    r#"CPU"#,
    r#"asmProgram"#,
    r#"TestProgramRunner"#,
    r#"AVRTWI"#,
    r#"twiConfig"#,
];
pub fn cases() -> Vec<Case> {
    vec![
        case_001_should_correctly_calculate_the_sclfrequency_from_twbr(),
        case_002_should_take_the_prescaler_into_consideration_when_calculating_sclfrequency(),
        case_003_should_trigger_data_an_interrupt_if_twint_is_set(),
        case_004_should_call_the_startevent_handler_when_twsta_bit_is_written_1(),
        case_005_should_connect_successfully_in_case_of_repeated_start_issue_91(),
        case_006_should_successfully_transmit_a_byte_to_a_slave(),
        case_007_should_successfully_receive_a_byte_from_a_slave(),
    ]
}

fn setup_0() -> Vec<Step> {
    vec![
        at(9, bind(r#"FREQ_16MHZ"#, num(16000000.0))),
        at(12, bind(r#"R16"#, num(16.0))),
        at(13, bind(r#"R17"#, num(17.0))),
        at(14, bind(r#"SREG"#, num(95.0))),
        at(17, bind(r#"TWBR"#, num(184.0))),
        at(18, bind(r#"TWSR"#, num(185.0))),
        at(19, bind(r#"TWDR"#, num(187.0))),
        at(20, bind(r#"TWCR"#, num(188.0))),
        at(23, bind(r#"TWIE"#, num(1.0))),
        at(24, bind(r#"TWEN"#, num(4.0))),
        at(25, bind(r#"TWSTO"#, num(16.0))),
        at(26, bind(r#"TWSTA"#, num(32.0))),
        at(27, bind(r#"TWEA"#, num(64.0))),
        at(28, bind(r#"TWINT"#, num(128.0))),
        at(
            30,
            bind(
                r#"onTestBreak"#,
                function(
                    vec![param(r#"cpu"#, false)],
                    vec![
                        at(
                            31,
                            eval(call(
                                get(var(r#"console"#), text(r#"log"#)),
                                vec![call(
                                    get(
                                        get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"TWCR"#)),
                                        text(r#"toString"#),
                                    ),
                                    vec![num(16.0)],
                                )],
                            )),
                        ),
                        at(
                            32,
                            eval(call(
                                get(var(r#"console"#), text(r#"log"#)),
                                vec![get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"R16"#))],
                            )),
                        ),
                    ],
                ),
            ),
        ),
    ]
}

pub fn case_001_should_correctly_calculate_the_sclfrequency_from_twbr() -> Case {
    Case {
        source: r#"src/peripherals/twi.spec.ts"#,
        name: r#"TWI / should correctly calculate the sclFrequency from TWBR"#,
        line: 36,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                37,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                38,
                bind(
                    r#"twi"#,
                    new(
                        r#"AVRTWI"#,
                        vec![var(r#"cpu"#), var(r#"twiConfig"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                39,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"TWBR"#), num(72.0)],
                )),
            ),
            at(
                40,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"TWSR"#), num(0.0)],
                )),
            ),
            at(
                41,
                check(
                    get(var(r#"twi"#), text(r#"sclFrequency"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(100000.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_001_should_correctly_calculate_the_sclfrequency_from_twbr_native() {
    crate::run_native(case_001_should_correctly_calculate_the_sclfrequency_from_twbr());
}

pub fn case_002_should_take_the_prescaler_into_consideration_when_calculating_sclfrequency() -> Case
{
    Case {
        source: r#"src/peripherals/twi.spec.ts"#,
        name: r#"TWI / should take the prescaler into consideration when calculating sclFrequency"#,
        line: 44,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                45,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                46,
                bind(
                    r#"twi"#,
                    new(
                        r#"AVRTWI"#,
                        vec![var(r#"cpu"#), var(r#"twiConfig"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                47,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"TWBR"#), num(3.0)],
                )),
            ),
            at(
                48,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"TWSR"#), num(1.0)],
                )),
            ),
            at(
                49,
                check(
                    get(var(r#"twi"#), text(r#"sclFrequency"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(400000.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_002_should_take_the_prescaler_into_consideration_when_calculating_sclfrequency_native() {
    crate::run_native(
        case_002_should_take_the_prescaler_into_consideration_when_calculating_sclfrequency(),
    );
}

pub fn case_003_should_trigger_data_an_interrupt_if_twint_is_set() -> Case {
    Case {
        source: r#"src/peripherals/twi.spec.ts"#,
        name: r#"TWI / should trigger data an interrupt if TWINT is set"#,
        line: 52,
        assertions: 3,
        setup: setup_0(),
        body: vec![
            at(
                53,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                54,
                bind(
                    r#"twi"#,
                    new(
                        r#"AVRTWI"#,
                        vec![var(r#"cpu"#), var(r#"twiConfig"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                55,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"TWCR"#), var(r#"TWIE"#)],
                )),
            ),
            at(
                56,
                eval(assign(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"SREG"#)),
                    num(128.0),
                    r#"="#,
                )),
            ),
            at(
                57,
                eval(call(get(var(r#"twi"#), text(r#"completeStart"#)), vec![])),
            ),
            at(58, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                59,
                check(
                    get(var(r#"cpu"#), text(r#"pc"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(48.0)],
                ),
            ),
            at(
                60,
                check(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(2.0)],
                ),
            ),
            at(
                61,
                check(
                    binary(
                        r#"&"#,
                        get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"TWCR"#)),
                        var(r#"TWINT"#),
                    ),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_003_should_trigger_data_an_interrupt_if_twint_is_set_native() {
    crate::run_native(case_003_should_trigger_data_an_interrupt_if_twint_is_set());
}

pub fn case_004_should_call_the_startevent_handler_when_twsta_bit_is_written_1() -> Case {
    Case {
        source: r#"src/peripherals/twi.spec.ts"#,
        name: r#"TWI / Master mode / should call the startEvent handler when TWSTA bit is written 1"#,
        line: 65,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                66,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                67,
                bind(
                    r#"twi"#,
                    new(
                        r#"AVRTWI"#,
                        vec![var(r#"cpu"#), var(r#"twiConfig"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                68,
                eval(call(
                    get(var(r#"vi"#), text(r#"spyOn"#)),
                    vec![
                        get(var(r#"twi"#), text(r#"eventHandler"#)),
                        text(r#"start"#),
                    ],
                )),
            ),
            at(
                69,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"TWCR"#),
                        binary(
                            r#"|"#,
                            binary(r#"|"#, var(r#"TWINT"#), var(r#"TWSTA"#)),
                            var(r#"TWEN"#),
                        ),
                    ],
                )),
            ),
            at(
                70,
                eval(update(get(var(r#"cpu"#), text(r#"cycles"#)), 1, false)),
            ),
            at(71, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                72,
                check(
                    get(
                        get(var(r#"twi"#), text(r#"eventHandler"#)),
                        text(r#"start"#),
                    ),
                    r#"toHaveBeenCalledWith"#,
                    false,
                    vec![boolean(false)],
                ),
            ),
        ],
    }
}
#[test]
fn case_004_should_call_the_startevent_handler_when_twsta_bit_is_written_1_native() {
    crate::run_native(case_004_should_call_the_startevent_handler_when_twsta_bit_is_written_1());
}

pub fn case_005_should_connect_successfully_in_case_of_repeated_start_issue_91() -> Case {
    Case {
        source: r#"src/peripherals/twi.spec.ts"#,
        name: r#"TWI / Master mode / should connect successfully in case of repeated start (issue #91)"#,
        line: 75,
        assertions: 2,
        setup: setup_0(),
        body: vec![
            at(
                76,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                77,
                bind(
                    r#"twi"#,
                    new(
                        r#"AVRTWI"#,
                        vec![var(r#"cpu"#), var(r#"twiConfig"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                80,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"TWCR"#),
                        binary(
                            r#"|"#,
                            binary(r#"|"#, var(r#"TWINT"#), var(r#"TWSTA"#)),
                            var(r#"TWEN"#),
                        ),
                    ],
                )),
            ),
            at(
                81,
                eval(update(get(var(r#"cpu"#), text(r#"cycles"#)), 1, false)),
            ),
            at(82, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                85,
                eval(call(
                    get(var(r#"vi"#), text(r#"spyOn"#)),
                    vec![
                        get(var(r#"twi"#), text(r#"eventHandler"#)),
                        text(r#"start"#),
                    ],
                )),
            ),
            at(
                86,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"TWCR"#),
                        binary(
                            r#"|"#,
                            binary(r#"|"#, var(r#"TWINT"#), var(r#"TWSTA"#)),
                            var(r#"TWEN"#),
                        ),
                    ],
                )),
            ),
            at(
                87,
                eval(update(get(var(r#"cpu"#), text(r#"cycles"#)), 1, false)),
            ),
            at(88, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                89,
                check(
                    get(
                        get(var(r#"twi"#), text(r#"eventHandler"#)),
                        text(r#"start"#),
                    ),
                    r#"toHaveBeenCalledWith"#,
                    false,
                    vec![boolean(true)],
                ),
            ),
            at(
                92,
                eval(call(
                    get(var(r#"vi"#), text(r#"spyOn"#)),
                    vec![
                        get(var(r#"twi"#), text(r#"eventHandler"#)),
                        text(r#"connectToSlave"#),
                    ],
                )),
            ),
            at(
                93,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"TWDR"#), num(128.0)],
                )),
            ),
            at(
                94,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"TWCR"#),
                        binary(r#"|"#, var(r#"TWINT"#), var(r#"TWEN"#)),
                    ],
                )),
            ),
            at(
                95,
                eval(update(get(var(r#"cpu"#), text(r#"cycles"#)), 1, false)),
            ),
            at(96, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                97,
                check(
                    get(
                        get(var(r#"twi"#), text(r#"eventHandler"#)),
                        text(r#"connectToSlave"#),
                    ),
                    r#"toHaveBeenCalledWith"#,
                    false,
                    vec![num(64.0), boolean(true)],
                ),
            ),
        ],
    }
}
#[test]
fn case_005_should_connect_successfully_in_case_of_repeated_start_issue_91_native() {
    crate::run_native(case_005_should_connect_successfully_in_case_of_repeated_start_issue_91());
}

pub fn case_006_should_successfully_transmit_a_byte_to_a_slave() -> Case {
    Case {
        source: r#"src/peripherals/twi.spec.ts"#,
        name: r#"TWI / Master mode / should successfully transmit a byte to a slave"#,
        line: 100,
        assertions: 5,
        setup: setup_0(),
        body: vec![
            at(
                103,
                destructure(
                    vec![(r#"program"#, r#"program"#)],
                    call(
                        var(r#"asmProgram"#),
                        vec![template(vec![
                            text(
                                r#"
        ; register addresses
        _REPLACE TWSR, "#,
                            ),
                            var(r#"TWSR"#),
                            text(
                                r#"
        _REPLACE TWDR, "#,
                            ),
                            var(r#"TWDR"#),
                            text(
                                r#"
        _REPLACE TWCR, "#,
                            ),
                            var(r#"TWCR"#),
                            text(
                                r#"

        ; TWCR bits
        _REPLACE TWEN, "#,
                            ),
                            var(r#"TWEN"#),
                            text(
                                r#"
        _REPLACE TWSTO, "#,
                            ),
                            var(r#"TWSTO"#),
                            text(
                                r#"
        _REPLACE TWSTA, "#,
                            ),
                            var(r#"TWSTA"#),
                            text(
                                r#"
        _REPLACE TWINT, "#,
                            ),
                            var(r#"TWINT"#),
                            text(
                                r#"

        ; TWSR states
        _REPLACE START, 0x8         ; TWI start
        _REPLACE MT_SLA_ACK, 0x18   ; Slave Adresss ACK has been received
        _REPLACE MT_DATA_ACK, 0x28  ; Data ACK has been received

        ; Send start condition
        ldi r16, TWEN
        sbr r16, TWSTA
        sbr r16, TWINT
        sts TWCR, r16

        ; Wait for TWINT Flag set. This indicates that the START condition has been transmitted
        call wait_for_twint
        
        ; Check value of TWI Status Register. Mask prescaler bits. If status different from START go to ERROR
        lds r16, TWSR
        andi r16, 0xf8
        cpi r16, START
        brne error

        ; Load SLA_W into TWDR Register. Clear TWINT bit in TWCR to start transmission of address
        ; 0x44 = Address 0x22, write mode (R/W bit clear)
        _REPLACE SLA_W, 0x44
        ldi r16, SLA_W
        sts TWDR, r16
        ldi r16, TWINT
        sbr r16, TWEN
        sts TWCR, r16

        ; Wait for TWINT Flag set. This indicates that the SLA+W has been transmitted, and ACK/NACK has been received.
        call wait_for_twint

        ; Check value of TWI Status Register. Mask prescaler bits. If status different from MT_SLA_ACK go to ERROR
        lds r16, TWSR
        andi r16, 0xf8
        cpi r16, MT_SLA_ACK
        brne error

        ; Load DATA into TWDR Register. Clear TWINT bit in TWCR to start transmission of data
        _replace DATA, 0x55
        ldi r16, DATA
        sts TWDR, r16
        ldi r16, TWINT
        sbr r16, TWEN
        sts TWCR, r16

        ; Wait for TWINT Flag set. This indicates that the DATA has been transmitted, and ACK/NACK has been received
        call wait_for_twint

        ; Check value of TWI Status Register. Mask prescaler bits. If status different from MT_DATA_ACK go to ERROR
        lds r16, TWSR
        andi r16, 0xf8
        cpi r16, MT_DATA_ACK
        brne error

        ; Transmit STOP condition
        ldi r16, TWINT
        sbr r16, TWEN
        sbr r16, TWSTO
        sts TWCR, r16

        ; Wait for TWINT Flag set. This indicates that the STOP condition has been sent
        call wait_for_twint

        ; Check value of TWI Status Register. The masked value should be 0xf8 once done
        lds r16, TWSR
        andi r16, 0xf8
        cpi r16, 0xf8
        brne error

        ; Indicate success by loading 0x42 into r17
        ldi r17, 0x42

        loop:
        jmp loop

        ; Busy-waits for the TWINT flag to be set
        wait_for_twint:
        lds r16, TWCR
        andi r16, TWINT
        breq wait_for_twint
        ret

        ; In case of an error, toggle a breakpoint
        error:
        break
      "#,
                            ),
                        ])],
                    ),
                ),
            ),
            at(202, bind(r#"cpu"#, new(r#"CPU"#, vec![var(r#"program"#)]))),
            at(
                203,
                bind(
                    r#"twi"#,
                    new(
                        r#"AVRTWI"#,
                        vec![var(r#"cpu"#), var(r#"twiConfig"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                204,
                bind(
                    r#"runner"#,
                    new(
                        r#"TestProgramRunner"#,
                        vec![var(r#"cpu"#), var(r#"onTestBreak"#)],
                    ),
                ),
            ),
            at(
                205,
                eval(assign(
                    get(var(r#"twi"#), text(r#"eventHandler"#)),
                    object(vec![
                        entry(r#"start"#, call(get(var(r#"vi"#), text(r#"fn"#)), vec![])),
                        entry(r#"stop"#, call(get(var(r#"vi"#), text(r#"fn"#)), vec![])),
                        entry(
                            r#"connectToSlave"#,
                            call(get(var(r#"vi"#), text(r#"fn"#)), vec![]),
                        ),
                        entry(
                            r#"writeByte"#,
                            call(get(var(r#"vi"#), text(r#"fn"#)), vec![]),
                        ),
                        entry(
                            r#"readByte"#,
                            call(get(var(r#"vi"#), text(r#"fn"#)), vec![]),
                        ),
                    ]),
                    r#"="#,
                )),
            ),
            at(
                214,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(4.0)],
                )),
            ),
            at(
                215,
                check(
                    get(
                        get(var(r#"twi"#), text(r#"eventHandler"#)),
                        text(r#"start"#),
                    ),
                    r#"toHaveBeenCalledWith"#,
                    false,
                    vec![boolean(false)],
                ),
            ),
            at(
                217,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(16.0)],
                )),
            ),
            at(
                218,
                eval(call(get(var(r#"twi"#), text(r#"completeStart"#)), vec![])),
            ),
            at(
                221,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(16.0)],
                )),
            ),
            at(
                222,
                check(
                    get(
                        get(var(r#"twi"#), text(r#"eventHandler"#)),
                        text(r#"connectToSlave"#),
                    ),
                    r#"toHaveBeenCalledWith"#,
                    false,
                    vec![num(34.0), boolean(true)],
                ),
            ),
            at(
                224,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(16.0)],
                )),
            ),
            at(
                225,
                eval(call(
                    get(var(r#"twi"#), text(r#"completeConnect"#)),
                    vec![boolean(true)],
                )),
            ),
            at(
                228,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(16.0)],
                )),
            ),
            at(
                229,
                check(
                    get(
                        get(var(r#"twi"#), text(r#"eventHandler"#)),
                        text(r#"writeByte"#),
                    ),
                    r#"toHaveBeenCalledWith"#,
                    false,
                    vec![num(85.0)],
                ),
            ),
            at(
                231,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(16.0)],
                )),
            ),
            at(
                232,
                eval(call(
                    get(var(r#"twi"#), text(r#"completeWrite"#)),
                    vec![boolean(true)],
                )),
            ),
            at(
                235,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(16.0)],
                )),
            ),
            at(
                236,
                check(
                    get(get(var(r#"twi"#), text(r#"eventHandler"#)), text(r#"stop"#)),
                    r#"toHaveBeenCalled"#,
                    false,
                    vec![],
                ),
            ),
            at(
                238,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(16.0)],
                )),
            ),
            at(
                239,
                eval(call(get(var(r#"twi"#), text(r#"completeStop"#)), vec![])),
            ),
            at(
                242,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(16.0)],
                )),
            ),
            at(
                243,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"R17"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(66.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_006_should_successfully_transmit_a_byte_to_a_slave_native() {
    crate::run_native(case_006_should_successfully_transmit_a_byte_to_a_slave());
}

pub fn case_007_should_successfully_receive_a_byte_from_a_slave() -> Case {
    Case {
        source: r#"src/peripherals/twi.spec.ts"#,
        name: r#"TWI / Master mode / should successfully receive a byte from a slave"#,
        line: 246,
        assertions: 6,
        setup: setup_0(),
        body: vec![
            at(
                247,
                destructure(
                    vec![(r#"program"#, r#"program"#)],
                    call(
                        var(r#"asmProgram"#),
                        vec![template(vec![
                            text(
                                r#"
        ; register addresses
        _REPLACE TWSR, "#,
                            ),
                            var(r#"TWSR"#),
                            text(
                                r#"
        _REPLACE TWDR, "#,
                            ),
                            var(r#"TWDR"#),
                            text(
                                r#"
        _REPLACE TWCR, "#,
                            ),
                            var(r#"TWCR"#),
                            text(
                                r#"
        
        ; TWCR bits
        _REPLACE TWEN, "#,
                            ),
                            var(r#"TWEN"#),
                            text(
                                r#"
        _REPLACE TWSTO, "#,
                            ),
                            var(r#"TWSTO"#),
                            text(
                                r#"
        _REPLACE TWSTA, "#,
                            ),
                            var(r#"TWSTA"#),
                            text(
                                r#"
        _REPLACE TWEA, "#,
                            ),
                            var(r#"TWEA"#),
                            text(
                                r#"
        _REPLACE TWINT, "#,
                            ),
                            var(r#"TWINT"#),
                            text(
                                r#"

        ; TWSR states
        _REPLACE START, 0x8         ; TWI start
        _REPLACE MT_SLAR_ACK, 0x40  ; Slave Adresss ACK has been received
        _REPLACE MT_DATA_RECV, 0x50 ; Data has been received
        _REPLACE MT_DATA_RECV_NACK, 0x58 ; Data has been received, NACK has been returned

        ; Send start condition
        ldi r16, TWEN
        sbr r16, TWSTA
        sbr r16, TWINT
        sts TWCR, r16

        ; Wait for TWINT Flag set. This indicates that the START condition has been transmitted
        call wait_for_twint
        
        ; Check value of TWI Status Register. Mask prescaler bits. If status different from START go to ERROR
        lds r16, TWSR
        andi r16, 0xf8
        ldi r18, START
        cpse r16, r18
        jmp error   ; only jump if r16 != r18 (START)

        ; Load SLA_R into TWDR Register. Clear TWINT bit in TWCR to start transmission of address
        ; 0xa1 = Address 0x50, read mode (R/W bit set)
        _REPLACE SLA_R, 0xa1
        ldi r16, SLA_R
        sts TWDR, r16
        ldi r16, TWINT
        sbr r16, TWEN
        sts TWCR, r16

        ; Wait for TWINT Flag set. This indicates that the SLA+W has been transmitted, and ACK/NACK has been received.
        call wait_for_twint

        ; Check value of TWI Status Register. Mask prescaler bits. If status different from MT_SLA_ACK go to ERROR
        lds r16, TWSR
        andi r16, 0xf8
        cpi r16, MT_SLAR_ACK
        brne error

        ; Clear TWINT bit in TWCR to receive the next byte, set TWEA to send ACK
        ldi r16, TWINT
        sbr r16, TWEA
        sbr r16, TWEN
        sts TWCR, r16

        ; Wait for TWINT Flag set. This indicates that the DATA has been received, and ACK has been transmitted
        call wait_for_twint

        ; Check value of TWI Status Register. Mask prescaler bits. If status different from MT_DATA_RECV go to ERROR
        lds r16, TWSR
        andi r16, 0xf8
        cpi r16, MT_DATA_RECV
        brne error

        ; Validate that we recieved the desired data - first byte should be 0x66
        lds r16, TWDR
        cpi r16, 0x66
        brne error

        ; Clear TWINT bit in TWCR to receive the next byte, this time we don't ACK
        ldi r16, TWINT
        sbr r16, TWEN
        sts TWCR, r16

        ; Wait for TWINT Flag set. This indicates that the DATA has been received, and NACK has been transmitted
        call wait_for_twint

        ; Check value of TWI Status Register. Mask prescaler bits. If status different from MT_DATA_RECV_NACK go to ERROR
        lds r16, TWSR
        andi r16, 0xf8
        cpi r16, MT_DATA_RECV_NACK
        brne error

        ; Validate that we recieved the desired data - second byte should be 0x77
        lds r16, TWDR
        cpi r16, 0x77
        brne error

        ; Transmit STOP condition
        ldi r16, TWINT
        sbr r16, TWEN
        sbr r16, TWSTO
        sts TWCR, r16

        ; Wait for TWINT Flag set. This indicates that the STOP condition has been sent
        call wait_for_twint

        ; Check value of TWI Status Register. The masked value should be 0xf8 once done
        lds r16, TWSR
        andi r16, 0xf8
        cpi r16, 0xf8
        brne error

        ; Indicate success by loading 0x42 into r17
        ldi r17, 0x42

        loop:
        jmp loop

        ; Busy-waits for the TWINT flag to be set
        wait_for_twint:
        lds r16, TWCR
        andi r16, TWINT
        breq wait_for_twint
        ret

        ; In case of an error, toggle a breakpoint
        error:
        break
      "#,
                            ),
                        ])],
                    ),
                ),
            ),
            at(371, bind(r#"cpu"#, new(r#"CPU"#, vec![var(r#"program"#)]))),
            at(
                372,
                bind(
                    r#"twi"#,
                    new(
                        r#"AVRTWI"#,
                        vec![var(r#"cpu"#), var(r#"twiConfig"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                373,
                bind(
                    r#"runner"#,
                    new(
                        r#"TestProgramRunner"#,
                        vec![var(r#"cpu"#), var(r#"onTestBreak"#)],
                    ),
                ),
            ),
            at(
                374,
                eval(assign(
                    get(var(r#"twi"#), text(r#"eventHandler"#)),
                    object(vec![
                        entry(r#"start"#, call(get(var(r#"vi"#), text(r#"fn"#)), vec![])),
                        entry(r#"stop"#, call(get(var(r#"vi"#), text(r#"fn"#)), vec![])),
                        entry(
                            r#"connectToSlave"#,
                            call(get(var(r#"vi"#), text(r#"fn"#)), vec![]),
                        ),
                        entry(
                            r#"writeByte"#,
                            call(get(var(r#"vi"#), text(r#"fn"#)), vec![]),
                        ),
                        entry(
                            r#"readByte"#,
                            call(get(var(r#"vi"#), text(r#"fn"#)), vec![]),
                        ),
                    ]),
                    r#"="#,
                )),
            ),
            at(
                383,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(4.0)],
                )),
            ),
            at(
                384,
                check(
                    get(
                        get(var(r#"twi"#), text(r#"eventHandler"#)),
                        text(r#"start"#),
                    ),
                    r#"toHaveBeenCalledWith"#,
                    false,
                    vec![boolean(false)],
                ),
            ),
            at(
                386,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(16.0)],
                )),
            ),
            at(
                387,
                eval(call(get(var(r#"twi"#), text(r#"completeStart"#)), vec![])),
            ),
            at(
                390,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(16.0)],
                )),
            ),
            at(
                391,
                check(
                    get(
                        get(var(r#"twi"#), text(r#"eventHandler"#)),
                        text(r#"connectToSlave"#),
                    ),
                    r#"toHaveBeenCalledWith"#,
                    false,
                    vec![num(80.0), boolean(false)],
                ),
            ),
            at(
                393,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(16.0)],
                )),
            ),
            at(
                394,
                eval(call(
                    get(var(r#"twi"#), text(r#"completeConnect"#)),
                    vec![boolean(true)],
                )),
            ),
            at(
                397,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(16.0)],
                )),
            ),
            at(
                398,
                check(
                    get(
                        get(var(r#"twi"#), text(r#"eventHandler"#)),
                        text(r#"readByte"#),
                    ),
                    r#"toHaveBeenCalledWith"#,
                    false,
                    vec![boolean(true)],
                ),
            ),
            at(
                400,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(16.0)],
                )),
            ),
            at(
                401,
                eval(call(
                    get(var(r#"twi"#), text(r#"completeRead"#)),
                    vec![num(102.0)],
                )),
            ),
            at(
                404,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(16.0)],
                )),
            ),
            at(
                405,
                check(
                    get(
                        get(var(r#"twi"#), text(r#"eventHandler"#)),
                        text(r#"readByte"#),
                    ),
                    r#"toHaveBeenCalledWith"#,
                    false,
                    vec![boolean(false)],
                ),
            ),
            at(
                407,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(16.0)],
                )),
            ),
            at(
                408,
                eval(call(
                    get(var(r#"twi"#), text(r#"completeRead"#)),
                    vec![num(119.0)],
                )),
            ),
            at(
                411,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(24.0)],
                )),
            ),
            at(
                412,
                check(
                    get(get(var(r#"twi"#), text(r#"eventHandler"#)), text(r#"stop"#)),
                    r#"toHaveBeenCalled"#,
                    false,
                    vec![],
                ),
            ),
            at(
                414,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(16.0)],
                )),
            ),
            at(
                415,
                eval(call(get(var(r#"twi"#), text(r#"completeStop"#)), vec![])),
            ),
            at(
                418,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(16.0)],
                )),
            ),
            at(
                419,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"R17"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(66.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_007_should_successfully_receive_a_byte_from_a_slave_native() {
    crate::run_native(case_007_should_successfully_receive_a_byte_from_a_slave());
}
