// SPDX-License-Identifier: MIT
// Copyright (c) Uri Shaked and contributors
// Generated by tools/convert.cjs. Source: src/peripherals/watchdog.spec.ts
use crate::scenario::*;
pub const IMPORTS: &[&str] = &[
    r#"AVRClock"#,
    r#"clockConfig"#,
    r#"CPU"#,
    r#"asmProgram"#,
    r#"TestProgramRunner"#,
    r#"AVRWatchdog"#,
    r#"watchdogConfig"#,
];
pub fn cases() -> Vec<Case> {
    vec![
        case_001_should_correctly_calculate_the_prescaler_from_wdtcsr(),
        case_002_should_not_change_the_prescaler_unless_wdce_is_set(),
        case_003_should_reset_the_cpu_when_the_timer_expires(),
        case_004_should_extend_the_watchdog_timeout_when_executing_a_wdr_instruction(),
        case_005_should_fire_an_interrupt_when_the_watchdog_expires_and_wdie_is_set(),
        case_006_should_not_reset_the_cpu_if_the_watchdog_has_been_disabled(),
    ]
}

fn setup_0() -> Vec<Step> {
    vec![
        at(17, bind(r#"R20"#, num(20.0))),
        at(19, bind(r#"MCUSR"#, num(84.0))),
        at(20, bind(r#"WDRF"#, binary(r#"<<"#, num(1.0), num(3.0)))),
        at(22, bind(r#"WDTCSR"#, num(96.0))),
        at(23, bind(r#"WDP0"#, binary(r#"<<"#, num(1.0), num(0.0)))),
        at(24, bind(r#"WDP1"#, binary(r#"<<"#, num(1.0), num(1.0)))),
        at(25, bind(r#"WDP2"#, binary(r#"<<"#, num(1.0), num(2.0)))),
        at(26, bind(r#"WDE"#, binary(r#"<<"#, num(1.0), num(3.0)))),
        at(27, bind(r#"WDCE"#, binary(r#"<<"#, num(1.0), num(4.0)))),
        at(28, bind(r#"WDP3"#, binary(r#"<<"#, num(1.0), num(5.0)))),
        at(29, bind(r#"WDIE"#, binary(r#"<<"#, num(1.0), num(6.0)))),
        at(31, bind(r#"INT_WDT"#, num(12.0))),
    ]
}

pub fn case_001_should_correctly_calculate_the_prescaler_from_wdtcsr() -> Case {
    Case {
        source: r#"src/peripherals/watchdog.spec.ts"#,
        name: r#"Watchdog / should correctly calculate the prescaler from WDTCSR"#,
        line: 34,
        assertions: 3,
        setup: setup_0(),
        body: vec![
            at(
                35,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                36,
                bind(
                    r#"clock"#,
                    new(
                        r#"AVRClock"#,
                        vec![var(r#"cpu"#), num(16000000.0), var(r#"clockConfig"#)],
                    ),
                ),
            ),
            at(
                37,
                bind(
                    r#"watchdog"#,
                    new(
                        r#"AVRWatchdog"#,
                        vec![var(r#"cpu"#), var(r#"watchdogConfig"#), var(r#"clock"#)],
                    ),
                ),
            ),
            at(
                38,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"WDTCSR"#),
                        binary(r#"|"#, var(r#"WDCE"#), var(r#"WDE"#)),
                    ],
                )),
            ),
            at(
                39,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"WDTCSR"#), num(0.0)],
                )),
            ),
            at(
                40,
                check(
                    get(var(r#"watchdog"#), text(r#"prescaler"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(2048.0)],
                ),
            ),
            at(
                41,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"WDTCSR"#),
                        binary(
                            r#"|"#,
                            binary(r#"|"#, var(r#"WDP2"#), var(r#"WDP1"#)),
                            var(r#"WDP0"#),
                        ),
                    ],
                )),
            ),
            at(
                42,
                check(
                    get(var(r#"watchdog"#), text(r#"prescaler"#)),
                    r#"toEqual"#,
                    false,
                    vec![binary(r#"*"#, num(256.0), num(1024.0))],
                ),
            ),
            at(
                43,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"WDTCSR"#),
                        binary(r#"|"#, var(r#"WDP3"#), var(r#"WDP0"#)),
                    ],
                )),
            ),
            at(
                44,
                check(
                    get(var(r#"watchdog"#), text(r#"prescaler"#)),
                    r#"toEqual"#,
                    false,
                    vec![binary(r#"*"#, num(1024.0), num(1024.0))],
                ),
            ),
        ],
    }
}
#[test]
fn case_001_should_correctly_calculate_the_prescaler_from_wdtcsr_native() {
    crate::run_native(case_001_should_correctly_calculate_the_prescaler_from_wdtcsr());
}

pub fn case_002_should_not_change_the_prescaler_unless_wdce_is_set() -> Case {
    Case {
        source: r#"src/peripherals/watchdog.spec.ts"#,
        name: r#"Watchdog / should not change the prescaler unless WDCE is set"#,
        line: 47,
        assertions: 3,
        setup: setup_0(),
        body: vec![
            at(
                48,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                49,
                bind(
                    r#"clock"#,
                    new(
                        r#"AVRClock"#,
                        vec![var(r#"cpu"#), num(16000000.0), var(r#"clockConfig"#)],
                    ),
                ),
            ),
            at(
                50,
                bind(
                    r#"watchdog"#,
                    new(
                        r#"AVRWatchdog"#,
                        vec![var(r#"cpu"#), var(r#"watchdogConfig"#), var(r#"clock"#)],
                    ),
                ),
            ),
            at(
                51,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"WDTCSR"#), num(0.0)],
                )),
            ),
            at(
                52,
                check(
                    get(var(r#"watchdog"#), text(r#"prescaler"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(2048.0)],
                ),
            ),
            at(
                53,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"WDTCSR"#),
                        binary(
                            r#"|"#,
                            binary(r#"|"#, var(r#"WDP2"#), var(r#"WDP1"#)),
                            var(r#"WDP0"#),
                        ),
                    ],
                )),
            ),
            at(
                54,
                check(
                    get(var(r#"watchdog"#), text(r#"prescaler"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(2048.0)],
                ),
            ),
            at(
                56,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"WDTCSR"#),
                        binary(r#"|"#, var(r#"WDCE"#), var(r#"WDE"#)),
                    ],
                )),
            ),
            at(
                57,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(5.0),
                    r#"+="#,
                )),
            ),
            at(
                58,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"WDTCSR"#),
                        binary(
                            r#"|"#,
                            binary(r#"|"#, var(r#"WDP2"#), var(r#"WDP1"#)),
                            var(r#"WDP0"#),
                        ),
                    ],
                )),
            ),
            at(
                59,
                check(
                    get(var(r#"watchdog"#), text(r#"prescaler"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(2048.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_002_should_not_change_the_prescaler_unless_wdce_is_set_native() {
    crate::run_native(case_002_should_not_change_the_prescaler_unless_wdce_is_set());
}

pub fn case_003_should_reset_the_cpu_when_the_timer_expires() -> Case {
    Case {
        source: r#"src/peripherals/watchdog.spec.ts"#,
        name: r#"Watchdog / should reset the CPU when the timer expires"#,
        line: 62,
        assertions: 3,
        setup: setup_0(),
        body: vec![
            at(
                63,
                destructure(
                    vec![(r#"program"#, r#"program"#)],
                    call(
                        var(r#"asmProgram"#),
                        vec![template(vec![
                            text(
                                r#"
    ; register addresses
    _REPLACE WDTCSR, "#,
                            ),
                            var(r#"WDTCSR"#),
                            text(
                                r#"

    ; Setup watchdog
    ldi r16, "#,
                            ),
                            binary(r#"|"#, var(r#"WDE"#), var(r#"WDCE"#)),
                            text(
                                r#"
    sts WDTCSR, r16
    ldi r16, "#,
                            ),
                            var(r#"WDE"#),
                            text(
                                r#"
    sts WDTCSR, r16
    
    nop

    break
  "#,
                            ),
                        ])],
                    ),
                ),
            ),
            at(77, bind(r#"cpu"#, new(r#"CPU"#, vec![var(r#"program"#)]))),
            at(
                78,
                bind(
                    r#"clock"#,
                    new(
                        r#"AVRClock"#,
                        vec![var(r#"cpu"#), num(16000000.0), var(r#"clockConfig"#)],
                    ),
                ),
            ),
            at(
                79,
                bind(
                    r#"watchdog"#,
                    new(
                        r#"AVRWatchdog"#,
                        vec![var(r#"cpu"#), var(r#"watchdogConfig"#), var(r#"clock"#)],
                    ),
                ),
            ),
            at(
                80,
                bind(
                    r#"runner"#,
                    new(r#"TestProgramRunner"#, vec![var(r#"cpu"#)]),
                ),
            ),
            at(
                83,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(4.0)],
                )),
            ),
            at(
                84,
                check(
                    get(var(r#"watchdog"#), text(r#"enabled"#)),
                    r#"toBe"#,
                    false,
                    vec![boolean(true)],
                ),
            ),
            at(
                87,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    binary(r#"*"#, num(16000.0), num(8.0)),
                    r#"+="#,
                )),
            ),
            at(
                88,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(1.0)],
                )),
            ),
            at(
                91,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    binary(r#"*"#, num(16000.0), num(8.0)),
                    r#"+="#,
                )),
            ),
            at(92, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                93,
                check(
                    get(var(r#"cpu"#), text(r#"pc"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
            at(
                94,
                check(
                    call(
                        get(var(r#"cpu"#), text(r#"readData"#)),
                        vec![var(r#"MCUSR"#)],
                    ),
                    r#"toEqual"#,
                    false,
                    vec![var(r#"WDRF"#)],
                ),
            ),
        ],
    }
}
#[test]
fn case_003_should_reset_the_cpu_when_the_timer_expires_native() {
    crate::run_native(case_003_should_reset_the_cpu_when_the_timer_expires());
}

pub fn case_004_should_extend_the_watchdog_timeout_when_executing_a_wdr_instruction() -> Case {
    Case {
        source: r#"src/peripherals/watchdog.spec.ts"#,
        name: r#"Watchdog / should extend the watchdog timeout when executing a WDR instruction"#,
        line: 97,
        assertions: 4,
        setup: setup_0(),
        body: vec![
            at(
                98,
                destructure(
                    vec![(r#"program"#, r#"program"#)],
                    call(
                        var(r#"asmProgram"#),
                        vec![template(vec![
                            text(
                                r#"
    ; register addresses
    _REPLACE WDTCSR, "#,
                            ),
                            var(r#"WDTCSR"#),
                            text(
                                r#"

    ; Setup watchdog
    ldi r16, "#,
                            ),
                            binary(r#"|"#, var(r#"WDE"#), var(r#"WDCE"#)),
                            text(
                                r#"
    sts WDTCSR, r16
    ldi r16, "#,
                            ),
                            var(r#"WDE"#),
                            text(
                                r#"
    sts WDTCSR, r16
    
    wdr
    nop

    break
  "#,
                            ),
                        ])],
                    ),
                ),
            ),
            at(113, bind(r#"cpu"#, new(r#"CPU"#, vec![var(r#"program"#)]))),
            at(
                114,
                bind(
                    r#"clock"#,
                    new(
                        r#"AVRClock"#,
                        vec![var(r#"cpu"#), num(16000000.0), var(r#"clockConfig"#)],
                    ),
                ),
            ),
            at(
                115,
                bind(
                    r#"watchdog"#,
                    new(
                        r#"AVRWatchdog"#,
                        vec![var(r#"cpu"#), var(r#"watchdogConfig"#), var(r#"clock"#)],
                    ),
                ),
            ),
            at(
                116,
                bind(
                    r#"runner"#,
                    new(r#"TestProgramRunner"#, vec![var(r#"cpu"#)]),
                ),
            ),
            at(
                119,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(4.0)],
                )),
            ),
            at(
                120,
                check(
                    get(var(r#"watchdog"#), text(r#"enabled"#)),
                    r#"toBe"#,
                    false,
                    vec![boolean(true)],
                ),
            ),
            at(
                123,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    binary(r#"*"#, num(16000.0), num(8.0)),
                    r#"+="#,
                )),
            ),
            at(
                124,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(1.0)],
                )),
            ),
            at(
                125,
                check(
                    get(var(r#"cpu"#), text(r#"pc"#)),
                    r#"toEqual"#,
                    true,
                    vec![num(0.0)],
                ),
            ),
            at(
                128,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    binary(r#"*"#, num(16000.0), num(8.0)),
                    r#"+="#,
                )),
            ),
            at(
                129,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(1.0)],
                )),
            ),
            at(
                130,
                check(
                    get(var(r#"cpu"#), text(r#"pc"#)),
                    r#"toEqual"#,
                    true,
                    vec![num(0.0)],
                ),
            ),
            at(
                133,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    binary(r#"*"#, num(16000.0), num(8.0)),
                    r#"+="#,
                )),
            ),
            at(134, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                135,
                check(
                    get(var(r#"cpu"#), text(r#"pc"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_004_should_extend_the_watchdog_timeout_when_executing_a_wdr_instruction_native() {
    crate::run_native(
        case_004_should_extend_the_watchdog_timeout_when_executing_a_wdr_instruction(),
    );
}

pub fn case_005_should_fire_an_interrupt_when_the_watchdog_expires_and_wdie_is_set() -> Case {
    Case {
        source: r#"src/peripherals/watchdog.spec.ts"#,
        name: r#"Watchdog / should fire an interrupt when the watchdog expires and WDIE is set"#,
        line: 138,
        assertions: 3,
        setup: setup_0(),
        body: vec![
            at(
                139,
                destructure(
                    vec![(r#"program"#, r#"program"#)],
                    call(
                        var(r#"asmProgram"#),
                        vec![template(vec![
                            text(
                                r#"
    ; register addresses
    _REPLACE WDTCSR, "#,
                            ),
                            var(r#"WDTCSR"#),
                            text(
                                r#"

    ; Setup watchdog
    ldi r16, "#,
                            ),
                            binary(r#"|"#, var(r#"WDE"#), var(r#"WDCE"#)),
                            text(
                                r#"
    sts WDTCSR, r16
    ldi r16, "#,
                            ),
                            binary(r#"|"#, var(r#"WDE"#), var(r#"WDIE"#)),
                            text(
                                r#"
    sts WDTCSR, r16
    
    nop
    sei

    break
  "#,
                            ),
                        ])],
                    ),
                ),
            ),
            at(154, bind(r#"cpu"#, new(r#"CPU"#, vec![var(r#"program"#)]))),
            at(
                155,
                bind(
                    r#"clock"#,
                    new(
                        r#"AVRClock"#,
                        vec![var(r#"cpu"#), num(16000000.0), var(r#"clockConfig"#)],
                    ),
                ),
            ),
            at(
                156,
                bind(
                    r#"watchdog"#,
                    new(
                        r#"AVRWatchdog"#,
                        vec![var(r#"cpu"#), var(r#"watchdogConfig"#), var(r#"clock"#)],
                    ),
                ),
            ),
            at(
                157,
                bind(
                    r#"runner"#,
                    new(r#"TestProgramRunner"#, vec![var(r#"cpu"#)]),
                ),
            ),
            at(
                160,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(4.0)],
                )),
            ),
            at(
                161,
                check(
                    get(var(r#"watchdog"#), text(r#"enabled"#)),
                    r#"toBe"#,
                    false,
                    vec![boolean(true)],
                ),
            ),
            at(
                164,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    binary(r#"*"#, num(16000.0), num(8.0)),
                    r#"+="#,
                )),
            ),
            at(
                165,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(1.0)],
                )),
            ),
            at(
                168,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    binary(r#"*"#, num(16000.0), num(8.0)),
                    r#"+="#,
                )),
            ),
            at(
                169,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(1.0)],
                )),
            ),
            at(
                171,
                check(
                    get(var(r#"cpu"#), text(r#"pc"#)),
                    r#"toEqual"#,
                    false,
                    vec![var(r#"INT_WDT"#)],
                ),
            ),
            at(
                173,
                check(
                    binary(
                        r#"&"#,
                        call(
                            get(var(r#"cpu"#), text(r#"readData"#)),
                            vec![var(r#"WDTCSR"#)],
                        ),
                        var(r#"WDIE"#),
                    ),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_005_should_fire_an_interrupt_when_the_watchdog_expires_and_wdie_is_set_native() {
    crate::run_native(
        case_005_should_fire_an_interrupt_when_the_watchdog_expires_and_wdie_is_set(),
    );
}

pub fn case_006_should_not_reset_the_cpu_if_the_watchdog_has_been_disabled() -> Case {
    Case {
        source: r#"src/peripherals/watchdog.spec.ts"#,
        name: r#"Watchdog / should not reset the CPU if the watchdog has been disabled"#,
        line: 176,
        assertions: 3,
        setup: setup_0(),
        body: vec![
            at(
                177,
                destructure(
                    vec![(r#"program"#, r#"program"#)],
                    call(
                        var(r#"asmProgram"#),
                        vec![template(vec![
                            text(
                                r#"
    ; register addresses
    _REPLACE WDTCSR, "#,
                            ),
                            var(r#"WDTCSR"#),
                            text(
                                r#"

    ; Setup watchdog
    ldi r16, "#,
                            ),
                            binary(r#"|"#, var(r#"WDE"#), var(r#"WDCE"#)),
                            text(
                                r#"
    sts WDTCSR, r16
    ldi r16, "#,
                            ),
                            var(r#"WDE"#),
                            text(
                                r#"
    sts WDTCSR, r16
    
    ; disable watchdog
    ldi r16, "#,
                            ),
                            binary(r#"|"#, var(r#"WDE"#), var(r#"WDCE"#)),
                            text(
                                r#"
    sts WDTCSR, r16
    ldi r16, 0
    sts WDTCSR, r16

    ldi r20, 55

    break
  "#,
                            ),
                        ])],
                    ),
                ),
            ),
            at(197, bind(r#"cpu"#, new(r#"CPU"#, vec![var(r#"program"#)]))),
            at(
                198,
                bind(
                    r#"clock"#,
                    new(
                        r#"AVRClock"#,
                        vec![var(r#"cpu"#), num(16000000.0), var(r#"clockConfig"#)],
                    ),
                ),
            ),
            at(
                199,
                bind(
                    r#"watchdog"#,
                    new(
                        r#"AVRWatchdog"#,
                        vec![var(r#"cpu"#), var(r#"watchdogConfig"#), var(r#"clock"#)],
                    ),
                ),
            ),
            at(
                200,
                bind(
                    r#"runner"#,
                    new(r#"TestProgramRunner"#, vec![var(r#"cpu"#)]),
                ),
            ),
            at(
                203,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(4.0)],
                )),
            ),
            at(
                204,
                check(
                    get(var(r#"watchdog"#), text(r#"enabled"#)),
                    r#"toBe"#,
                    false,
                    vec![boolean(true)],
                ),
            ),
            at(
                207,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    binary(r#"*"#, num(16000.0), num(8.0)),
                    r#"+="#,
                )),
            ),
            at(
                208,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(4.0)],
                )),
            ),
            at(
                211,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    binary(r#"*"#, num(16000.0), num(20.0)),
                    r#"+="#,
                )),
            ),
            at(
                212,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(1.0)],
                )),
            ),
            at(
                213,
                check(
                    get(var(r#"cpu"#), text(r#"pc"#)),
                    r#"toEqual"#,
                    true,
                    vec![num(0.0)],
                ),
            ),
            at(
                214,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"R20"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(55.0)],
                ),
            ),
        ],
    }
}
#[test]
fn case_006_should_not_reset_the_cpu_if_the_watchdog_has_been_disabled_native() {
    crate::run_native(case_006_should_not_reset_the_cpu_if_the_watchdog_has_been_disabled());
}
