// SPDX-License-Identifier: MIT
// Copyright (c) Uri Shaked and contributors
// Generated by tools/convert.cjs. Source: src/peripherals/adc.spec.ts
use crate::scenario::*;
pub const IMPORTS: &[&str] = &[
    r#"CPU"#,
    r#"asmProgram"#,
    r#"TestProgramRunner"#,
    r#"adcConfig"#,
    r#"ADCMuxInputType"#,
    r#"AVRADC"#,
];
pub fn cases() -> Vec<Case> {
    vec![
        case_001_should_successfuly_perform_an_adc_conversion(),
        case_002_should_read_0_when_the_adc_peripheral_is_not_enabled(),
    ]
}

fn setup_0() -> Vec<Step> {
    vec![
        at(6, bind(r#"R16"#, num(16.0))),
        at(7, bind(r#"R17"#, num(17.0))),
        at(9, bind(r#"ADMUX"#, num(124.0))),
        at(10, bind(r#"REFS0"#, binary(r#"<<"#, num(1.0), num(6.0)))),
        at(12, bind(r#"ADCSRA"#, num(122.0))),
        at(13, bind(r#"ADEN"#, binary(r#"<<"#, num(1.0), num(7.0)))),
        at(14, bind(r#"ADSC"#, binary(r#"<<"#, num(1.0), num(6.0)))),
        at(15, bind(r#"ADPS0"#, binary(r#"<<"#, num(1.0), num(0.0)))),
        at(16, bind(r#"ADPS1"#, binary(r#"<<"#, num(1.0), num(1.0)))),
        at(17, bind(r#"ADPS2"#, binary(r#"<<"#, num(1.0), num(2.0)))),
        at(19, bind(r#"ADCH"#, num(121.0))),
        at(20, bind(r#"ADCL"#, num(120.0))),
    ]
}

pub fn case_001_should_successfuly_perform_an_adc_conversion() -> Case {
    Case {
        source: r#"src/peripherals/adc.spec.ts"#,
        name: r#"ADC / should successfuly perform an ADC conversion"#,
        line: 23,
        assertions: 2,
        setup: setup_0(),
        body: vec![
            at(
                24,
                destructure(
                    vec![(r#"program"#, r#"program"#)],
                    call(
                        var(r#"asmProgram"#),
                        vec![template(vec![
                            text(
                                r#"
    ; register addresses
    _REPLACE ADMUX, "#,
                            ),
                            var(r#"ADMUX"#),
                            text(
                                r#"
    _REPLACE ADCSRA, "#,
                            ),
                            var(r#"ADCSRA"#),
                            text(
                                r#"
    _REPLACE ADCH, "#,
                            ),
                            var(r#"ADCH"#),
                            text(
                                r#"
    _REPLACE ADCL, "#,
                            ),
                            var(r#"ADCL"#),
                            text(
                                r#"

    ; Configure mux - channel 0, reference: AVCC with external capacitor at AREF pin
    ldi r24, "#,
                            ),
                            var(r#"REFS0"#),
                            text(
                                r#"
    sts ADMUX, r24

    ; Start conversion with 128 prescaler
    ldi r24, "#,
                            ),
                            binary(
                                r#"|"#,
                                binary(
                                    r#"|"#,
                                    binary(
                                        r#"|"#,
                                        binary(r#"|"#, var(r#"ADEN"#), var(r#"ADSC"#)),
                                        var(r#"ADPS0"#),
                                    ),
                                    var(r#"ADPS1"#),
                                ),
                                var(r#"ADPS2"#),
                            ),
                            text(
                                r#"
    sts ADCSRA, r24

    ; Wait until conversion is complete
  waitComplete:
    lds r24, "#,
                            ),
                            var(r#"ADCSRA"#),
                            text(
                                r#"
    andi r24, "#,
                            ),
                            var(r#"ADSC"#),
                            text(
                                r#"
    brne waitComplete

    ; Read the result
    lds r16, "#,
                            ),
                            var(r#"ADCL"#),
                            text(
                                r#"
    lds r17, "#,
                            ),
                            var(r#"ADCH"#),
                            text(
                                r#"

    break
  "#,
                            ),
                        ])],
                    ),
                ),
            ),
            at(51, bind(r#"cpu"#, new(r#"CPU"#, vec![var(r#"program"#)]))),
            at(
                52,
                bind(
                    r#"adc"#,
                    new(r#"AVRADC"#, vec![var(r#"cpu"#), var(r#"adcConfig"#)]),
                ),
            ),
            at(
                53,
                bind(
                    r#"runner"#,
                    new(r#"TestProgramRunner"#, vec![var(r#"cpu"#)]),
                ),
            ),
            at(
                55,
                bind(
                    r#"adcReadSpy"#,
                    call(
                        get(var(r#"vi"#), text(r#"spyOn"#)),
                        vec![var(r#"adc"#), text(r#"onADCRead"#)],
                    ),
                ),
            ),
            at(
                56,
                eval(assign(
                    get(get(var(r#"adc"#), text(r#"channelValues"#)), num(0.0)),
                    num(2.56),
                    r#"="#,
                )),
            ),
            at(
                59,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(4.0)],
                )),
            ),
            at(
                60,
                check(
                    var(r#"adcReadSpy"#),
                    r#"toHaveBeenCalledWith"#,
                    false,
                    vec![object(vec![
                        entry(r#"channel"#, num(0.0)),
                        entry(
                            r#"type"#,
                            get(var(r#"ADCMuxInputType"#), text(r#"SingleEnded"#)),
                        ),
                    ])],
                ),
            ),
            at(
                63,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(12.0)],
                )),
            ),
            at(
                65,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    binary(r#"*"#, num(128.0), num(25.0)),
                    r#"+="#,
                )),
            ),
            at(66, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                69,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(5.0)],
                )),
            ),
            at(
                71,
                bind(
                    r#"low"#,
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"R16"#)),
                ),
            ),
            at(
                72,
                bind(
                    r#"high"#,
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"R17"#)),
                ),
            ),
            at(
                73,
                check(
                    binary(
                        r#"|"#,
                        binary(r#"<<"#, var(r#"high"#), num(8.0)),
                        var(r#"low"#),
                    ),
                    r#"toEqual"#,
                    false,
                    vec![num(524.0)],
                ),
            ),
        ],
    }
}
#[test]
#[ignore = "native peripheral implementation pending"]
fn case_001_should_successfuly_perform_an_adc_conversion_native() {
    crate::run_native(case_001_should_successfuly_perform_an_adc_conversion());
}

pub fn case_002_should_read_0_when_the_adc_peripheral_is_not_enabled() -> Case {
    Case {
        source: r#"src/peripherals/adc.spec.ts"#,
        name: r#"ADC / should read 0 when the ADC peripheral is not enabled"#,
        line: 76,
        assertions: 2,
        setup: setup_0(),
        body: vec![
            at(
                81,
                destructure(
                    vec![(r#"program"#, r#"program"#)],
                    call(
                        var(r#"asmProgram"#),
                        vec![template(vec![
                            text(
                                r#"
    ; register addresses
    _REPLACE ADMUX, "#,
                            ),
                            var(r#"ADMUX"#),
                            text(
                                r#"
    _REPLACE ADCSRA, "#,
                            ),
                            var(r#"ADCSRA"#),
                            text(
                                r#"
    _REPLACE ADCH, "#,
                            ),
                            var(r#"ADCH"#),
                            text(
                                r#"
    _REPLACE ADCL, "#,
                            ),
                            var(r#"ADCL"#),
                            text(
                                r#"

    ; Load some initial value into r16/r17 to make sure we actually read 0 later
    ldi r16, 0xff
    ldi r17, 0xff

    ; Configure mux - channel 0, reference: AVCC with external capacitor at AREF pin
    ldi r24, "#,
                            ),
                            var(r#"REFS0"#),
                            text(
                                r#"
    sts ADMUX, r24

    ; Start conversion with 128 prescaler, but without enabling the ADC
    ldi r24, "#,
                            ),
                            binary(
                                r#"|"#,
                                binary(
                                    r#"|"#,
                                    binary(r#"|"#, var(r#"ADSC"#), var(r#"ADPS0"#)),
                                    var(r#"ADPS1"#),
                                ),
                                var(r#"ADPS2"#),
                            ),
                            text(
                                r#"
    sts ADCSRA, r24

    ; Wait until conversion is complete
  waitComplete:
    lds r24, "#,
                            ),
                            var(r#"ADCSRA"#),
                            text(
                                r#"
    andi r24, "#,
                            ),
                            var(r#"ADSC"#),
                            text(
                                r#"
    brne waitComplete

    ; Read the result
    lds r16, "#,
                            ),
                            var(r#"ADCL"#),
                            text(
                                r#"
    lds r17, "#,
                            ),
                            var(r#"ADCH"#),
                            text(
                                r#"

    break
  "#,
                            ),
                        ])],
                    ),
                ),
            ),
            at(112, bind(r#"cpu"#, new(r#"CPU"#, vec![var(r#"program"#)]))),
            at(
                113,
                bind(
                    r#"adc"#,
                    new(r#"AVRADC"#, vec![var(r#"cpu"#), var(r#"adcConfig"#)]),
                ),
            ),
            at(
                114,
                bind(
                    r#"runner"#,
                    new(
                        r#"TestProgramRunner"#,
                        vec![var(r#"cpu"#), function(vec![], vec![])],
                    ),
                ),
            ),
            at(
                118,
                bind(
                    r#"adcReadSpy"#,
                    call(
                        get(var(r#"vi"#), text(r#"spyOn"#)),
                        vec![var(r#"adc"#), text(r#"onADCRead"#)],
                    ),
                ),
            ),
            at(
                119,
                eval(assign(
                    get(get(var(r#"adc"#), text(r#"channelValues"#)), num(0.0)),
                    num(2.56),
                    r#"="#,
                )),
            ),
            at(
                122,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(6.0)],
                )),
            ),
            at(
                123,
                check(var(r#"adcReadSpy"#), r#"toHaveBeenCalled"#, true, vec![]),
            ),
            at(
                126,
                eval(call(
                    get(var(r#"runner"#), text(r#"runInstructions"#)),
                    vec![num(12.0)],
                )),
            ),
            at(
                128,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    binary(r#"*"#, num(128.0), num(25.0)),
                    r#"+="#,
                )),
            ),
            at(129, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                132,
                eval(call(get(var(r#"runner"#), text(r#"runToBreak"#)), vec![])),
            ),
            at(
                134,
                bind(
                    r#"low"#,
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"R16"#)),
                ),
            ),
            at(
                135,
                bind(
                    r#"high"#,
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"R17"#)),
                ),
            ),
            at(
                136,
                check(
                    binary(
                        r#"|"#,
                        binary(r#"<<"#, var(r#"high"#), num(8.0)),
                        var(r#"low"#),
                    ),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
        ],
    }
}
#[test]
#[ignore = "native peripheral implementation pending"]
fn case_002_should_read_0_when_the_adc_peripheral_is_not_enabled_native() {
    crate::run_native(case_002_should_read_0_when_the_adc_peripheral_is_not_enabled());
}
