// SPDX-License-Identifier: MIT
// Copyright (c) Uri Shaked and contributors
// Generated by tools/convert.cjs. Source: src/peripherals/usart.spec.ts
use crate::scenario::*;
pub const IMPORTS: &[&str] = &[r#"CPU"#, r#"AVRUSART"#, r#"usart0Config"#];
pub fn cases() -> Vec<Case> {
    vec![
        case_001_should_correctly_calculate_the_baudrate_from_ubrr(),
        case_002_should_correctly_calculate_the_baudrate_from_ubrr_in_double_speed_mode(),
        case_003_should_call_onconfigurationchange_when_the_baudrate_changes(),
        case_004_should_return_5_bits_per_byte_when_ucsz_0(),
        case_005_should_return_6_bits_per_byte_when_ucsz_1(),
        case_006_should_return_7_bits_per_byte_when_ucsz_2(),
        case_007_should_return_8_bits_per_byte_when_ucsz_3(),
        case_008_should_return_9_bits_per_byte_when_ucsz_7(),
        case_009_should_call_onconfigurationchange_when_bitsperchar_change(),
        case_010_should_return_1_when_usbs_0(),
        case_011_should_return_2_when_usbs_1(),
        case_012_should_return_false_when_upm1_0(),
        case_013_should_return_true_when_upm1_1(),
        case_014_should_return_false_when_upm0_0(),
        case_015_should_return_true_when_upm0_1(),
        case_016_should_invoke_onbytetransmit_when_udr0_is_written_to(),
        case_017_txenable_should_equal_true_when_the_transitter_is_enabled(),
        case_018_rxenable_should_equal_true_when_the_transitter_is_enabled(),
        case_019_should_trigger_data_register_empty_interrupt_if_udre_is_set(),
        case_020_should_trigger_data_tx_complete_interrupt_if_txcie_is_set(),
        case_021_should_not_trigger_data_tx_complete_interrupt_if_udr_was_not_written_to(),
        case_022_should_not_trigger_any_interrupt_if_interrupts_are_disabled(),
        case_023_should_call_onlinetransmit_with_the_current_line_buffer_after_every_newline(),
        case_024_should_not_call_onlinetransmit_if_no_newline_was_received(),
        case_025_should_clear_the_line_buffer_after_each_call_to_onlinetransmit(),
        case_026_should_return_false_if_called_when_rx_is_busy(),
        case_027_should_set_the_txc_bit_after_1_04ms_when_baud_rate_set_to_9600(),
        case_028_should_be_ready_to_recieve_the_next_byte_after_1_04ms_when_baudrate_set_to_9600(),
    ]
}

fn setup_0() -> Vec<Step> {
    vec![
        at(8, bind(r#"FREQ_16MHZ"#, num(16000000.0))),
        at(9, bind(r#"FREQ_11_0529MHZ"#, num(11059200.0))),
        at(12, bind(r#"SREG"#, num(95.0))),
        at(15, bind(r#"UCSR0A"#, num(192.0))),
        at(16, bind(r#"UCSR0B"#, num(193.0))),
        at(17, bind(r#"UCSR0C"#, num(194.0))),
        at(18, bind(r#"UBRR0L"#, num(196.0))),
        at(19, bind(r#"UBRR0H"#, num(197.0))),
        at(20, bind(r#"UDR0"#, num(198.0))),
        at(23, bind(r#"U2X0"#, num(2.0))),
        at(24, bind(r#"TXEN"#, num(8.0))),
        at(25, bind(r#"RXEN"#, num(16.0))),
        at(26, bind(r#"UDRIE"#, num(32.0))),
        at(27, bind(r#"TXCIE"#, num(64.0))),
        at(28, bind(r#"RXC"#, num(128.0))),
        at(29, bind(r#"TXC"#, num(64.0))),
        at(30, bind(r#"UDRE"#, num(32.0))),
        at(31, bind(r#"USBS"#, num(8.0))),
        at(32, bind(r#"UPM0"#, num(16.0))),
        at(33, bind(r#"UPM1"#, num(32.0))),
        at(36, bind(r#"PC_INT_UDRE"#, num(38.0))),
        at(37, bind(r#"PC_INT_TXC"#, num(40.0))),
        at(38, bind(r#"UCSZ0"#, num(2.0))),
        at(39, bind(r#"UCSZ1"#, num(4.0))),
        at(40, bind(r#"UCSZ2"#, num(4.0))),
    ]
}

pub fn case_001_should_correctly_calculate_the_baudrate_from_ubrr() -> Case {
    Case {
        source: r#"src/peripherals/usart.spec.ts"#,
        name: r#"USART / should correctly calculate the baudRate from UBRR"#,
        line: 43,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                44,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                45,
                bind(
                    r#"usart"#,
                    new(
                        r#"AVRUSART"#,
                        vec![
                            var(r#"cpu"#),
                            var(r#"usart0Config"#),
                            var(r#"FREQ_11_0529MHZ"#),
                        ],
                    ),
                ),
            ),
            at(
                46,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UBRR0H"#), num(0.0)],
                )),
            ),
            at(
                47,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UBRR0L"#), num(5.0)],
                )),
            ),
            at(
                48,
                check(
                    get(var(r#"usart"#), text(r#"baudRate"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(115200.0)],
                ),
            ),
        ],
    }
}
#[test]
#[ignore = "native peripheral implementation pending"]
fn case_001_should_correctly_calculate_the_baudrate_from_ubrr_native() {
    crate::run_native(case_001_should_correctly_calculate_the_baudrate_from_ubrr());
}

pub fn case_002_should_correctly_calculate_the_baudrate_from_ubrr_in_double_speed_mode() -> Case {
    Case {
        source: r#"src/peripherals/usart.spec.ts"#,
        name: r#"USART / should correctly calculate the baudRate from UBRR in double-speed mode"#,
        line: 51,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                52,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                53,
                bind(
                    r#"usart"#,
                    new(
                        r#"AVRUSART"#,
                        vec![var(r#"cpu"#), var(r#"usart0Config"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                54,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UBRR0H"#), num(3.0)],
                )),
            ),
            at(
                55,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UBRR0L"#), num(64.0)],
                )),
            ),
            at(
                56,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UCSR0A"#), var(r#"U2X0"#)],
                )),
            ),
            at(
                57,
                check(
                    get(var(r#"usart"#), text(r#"baudRate"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(2400.0)],
                ),
            ),
        ],
    }
}
#[test]
#[ignore = "native peripheral implementation pending"]
fn case_002_should_correctly_calculate_the_baudrate_from_ubrr_in_double_speed_mode_native() {
    crate::run_native(
        case_002_should_correctly_calculate_the_baudrate_from_ubrr_in_double_speed_mode(),
    );
}

pub fn case_003_should_call_onconfigurationchange_when_the_baudrate_changes() -> Case {
    Case {
        source: r#"src/peripherals/usart.spec.ts"#,
        name: r#"USART / should call onConfigurationChange when the baudRate changes"#,
        line: 60,
        assertions: 3,
        setup: setup_0(),
        body: vec![
            at(
                61,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                62,
                bind(
                    r#"usart"#,
                    new(
                        r#"AVRUSART"#,
                        vec![var(r#"cpu"#), var(r#"usart0Config"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                63,
                bind(
                    r#"onConfigurationChange"#,
                    call(get(var(r#"vi"#), text(r#"fn"#)), vec![]),
                ),
            ),
            at(
                64,
                eval(assign(
                    get(var(r#"usart"#), text(r#"onConfigurationChange"#)),
                    var(r#"onConfigurationChange"#),
                    r#"="#,
                )),
            ),
            at(
                66,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UBRR0H"#), num(0.0)],
                )),
            ),
            at(
                67,
                check(
                    var(r#"onConfigurationChange"#),
                    r#"toHaveBeenCalled"#,
                    false,
                    vec![],
                ),
            ),
            at(
                69,
                eval(call(
                    get(var(r#"onConfigurationChange"#), text(r#"mockClear"#)),
                    vec![],
                )),
            ),
            at(
                70,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UBRR0L"#), num(5.0)],
                )),
            ),
            at(
                71,
                check(
                    var(r#"onConfigurationChange"#),
                    r#"toHaveBeenCalled"#,
                    false,
                    vec![],
                ),
            ),
            at(
                73,
                eval(call(
                    get(var(r#"onConfigurationChange"#), text(r#"mockClear"#)),
                    vec![],
                )),
            ),
            at(
                74,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UCSR0A"#), var(r#"U2X0"#)],
                )),
            ),
            at(
                75,
                check(
                    var(r#"onConfigurationChange"#),
                    r#"toHaveBeenCalled"#,
                    false,
                    vec![],
                ),
            ),
        ],
    }
}
#[test]
#[ignore = "native peripheral implementation pending"]
fn case_003_should_call_onconfigurationchange_when_the_baudrate_changes_native() {
    crate::run_native(case_003_should_call_onconfigurationchange_when_the_baudrate_changes());
}

pub fn case_004_should_return_5_bits_per_byte_when_ucsz_0() -> Case {
    Case {
        source: r#"src/peripherals/usart.spec.ts"#,
        name: r#"USART / bitsPerChar / should return 5-bits per byte when UCSZ = 0"#,
        line: 79,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                80,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                81,
                bind(
                    r#"usart"#,
                    new(
                        r#"AVRUSART"#,
                        vec![var(r#"cpu"#), var(r#"usart0Config"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                82,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UCSR0C"#), num(0.0)],
                )),
            ),
            at(
                83,
                check(
                    get(var(r#"usart"#), text(r#"bitsPerChar"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(5.0)],
                ),
            ),
        ],
    }
}
#[test]
#[ignore = "native peripheral implementation pending"]
fn case_004_should_return_5_bits_per_byte_when_ucsz_0_native() {
    crate::run_native(case_004_should_return_5_bits_per_byte_when_ucsz_0());
}

pub fn case_005_should_return_6_bits_per_byte_when_ucsz_1() -> Case {
    Case {
        source: r#"src/peripherals/usart.spec.ts"#,
        name: r#"USART / bitsPerChar / should return 6-bits per byte when UCSZ = 1"#,
        line: 86,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                87,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                88,
                bind(
                    r#"usart"#,
                    new(
                        r#"AVRUSART"#,
                        vec![var(r#"cpu"#), var(r#"usart0Config"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                89,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UCSR0C"#), var(r#"UCSZ0"#)],
                )),
            ),
            at(
                90,
                check(
                    get(var(r#"usart"#), text(r#"bitsPerChar"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(6.0)],
                ),
            ),
        ],
    }
}
#[test]
#[ignore = "native peripheral implementation pending"]
fn case_005_should_return_6_bits_per_byte_when_ucsz_1_native() {
    crate::run_native(case_005_should_return_6_bits_per_byte_when_ucsz_1());
}

pub fn case_006_should_return_7_bits_per_byte_when_ucsz_2() -> Case {
    Case {
        source: r#"src/peripherals/usart.spec.ts"#,
        name: r#"USART / bitsPerChar / should return 7-bits per byte when UCSZ = 2"#,
        line: 93,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                94,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                95,
                bind(
                    r#"usart"#,
                    new(
                        r#"AVRUSART"#,
                        vec![var(r#"cpu"#), var(r#"usart0Config"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                96,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UCSR0C"#), var(r#"UCSZ1"#)],
                )),
            ),
            at(
                97,
                check(
                    get(var(r#"usart"#), text(r#"bitsPerChar"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(7.0)],
                ),
            ),
        ],
    }
}
#[test]
#[ignore = "native peripheral implementation pending"]
fn case_006_should_return_7_bits_per_byte_when_ucsz_2_native() {
    crate::run_native(case_006_should_return_7_bits_per_byte_when_ucsz_2());
}

pub fn case_007_should_return_8_bits_per_byte_when_ucsz_3() -> Case {
    Case {
        source: r#"src/peripherals/usart.spec.ts"#,
        name: r#"USART / bitsPerChar / should return 8-bits per byte when UCSZ = 3"#,
        line: 100,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                101,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                102,
                bind(
                    r#"usart"#,
                    new(
                        r#"AVRUSART"#,
                        vec![var(r#"cpu"#), var(r#"usart0Config"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                103,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"UCSR0C"#),
                        binary(r#"|"#, var(r#"UCSZ0"#), var(r#"UCSZ1"#)),
                    ],
                )),
            ),
            at(
                104,
                check(
                    get(var(r#"usart"#), text(r#"bitsPerChar"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(8.0)],
                ),
            ),
        ],
    }
}
#[test]
#[ignore = "native peripheral implementation pending"]
fn case_007_should_return_8_bits_per_byte_when_ucsz_3_native() {
    crate::run_native(case_007_should_return_8_bits_per_byte_when_ucsz_3());
}

pub fn case_008_should_return_9_bits_per_byte_when_ucsz_7() -> Case {
    Case {
        source: r#"src/peripherals/usart.spec.ts"#,
        name: r#"USART / bitsPerChar / should return 9-bits per byte when UCSZ = 7"#,
        line: 107,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                108,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                109,
                bind(
                    r#"usart"#,
                    new(
                        r#"AVRUSART"#,
                        vec![var(r#"cpu"#), var(r#"usart0Config"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                110,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"UCSR0C"#),
                        binary(r#"|"#, var(r#"UCSZ0"#), var(r#"UCSZ1"#)),
                    ],
                )),
            ),
            at(
                111,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UCSR0B"#), var(r#"UCSZ2"#)],
                )),
            ),
            at(
                112,
                check(
                    get(var(r#"usart"#), text(r#"bitsPerChar"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(9.0)],
                ),
            ),
        ],
    }
}
#[test]
#[ignore = "native peripheral implementation pending"]
fn case_008_should_return_9_bits_per_byte_when_ucsz_7_native() {
    crate::run_native(case_008_should_return_9_bits_per_byte_when_ucsz_7());
}

pub fn case_009_should_call_onconfigurationchange_when_bitsperchar_change() -> Case {
    Case {
        source: r#"src/peripherals/usart.spec.ts"#,
        name: r#"USART / bitsPerChar / should call onConfigurationChange when bitsPerChar change"#,
        line: 115,
        assertions: 3,
        setup: setup_0(),
        body: vec![
            at(
                116,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                117,
                bind(
                    r#"usart"#,
                    new(
                        r#"AVRUSART"#,
                        vec![var(r#"cpu"#), var(r#"usart0Config"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                118,
                bind(
                    r#"onConfigurationChange"#,
                    call(get(var(r#"vi"#), text(r#"fn"#)), vec![]),
                ),
            ),
            at(
                119,
                eval(assign(
                    get(var(r#"usart"#), text(r#"onConfigurationChange"#)),
                    var(r#"onConfigurationChange"#),
                    r#"="#,
                )),
            ),
            at(
                121,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"UCSR0C"#),
                        binary(r#"|"#, var(r#"UCSZ0"#), var(r#"UCSZ1"#)),
                    ],
                )),
            ),
            at(
                122,
                check(
                    var(r#"onConfigurationChange"#),
                    r#"toHaveBeenCalled"#,
                    false,
                    vec![],
                ),
            ),
            at(
                124,
                eval(call(
                    get(var(r#"onConfigurationChange"#), text(r#"mockClear"#)),
                    vec![],
                )),
            ),
            at(
                125,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UCSR0B"#), var(r#"UCSZ2"#)],
                )),
            ),
            at(
                126,
                check(
                    var(r#"onConfigurationChange"#),
                    r#"toHaveBeenCalled"#,
                    false,
                    vec![],
                ),
            ),
            at(
                128,
                eval(call(
                    get(var(r#"onConfigurationChange"#), text(r#"mockClear"#)),
                    vec![],
                )),
            ),
            at(
                129,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UCSR0B"#), var(r#"UCSZ2"#)],
                )),
            ),
            at(
                130,
                check(
                    var(r#"onConfigurationChange"#),
                    r#"toHaveBeenCalled"#,
                    true,
                    vec![],
                ),
            ),
        ],
    }
}
#[test]
#[ignore = "native peripheral implementation pending"]
fn case_009_should_call_onconfigurationchange_when_bitsperchar_change_native() {
    crate::run_native(case_009_should_call_onconfigurationchange_when_bitsperchar_change());
}

pub fn case_010_should_return_1_when_usbs_0() -> Case {
    Case {
        source: r#"src/peripherals/usart.spec.ts"#,
        name: r#"USART / stopBits / should return 1 when USBS = 0"#,
        line: 135,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                136,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                137,
                bind(
                    r#"usart"#,
                    new(
                        r#"AVRUSART"#,
                        vec![var(r#"cpu"#), var(r#"usart0Config"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                138,
                check(
                    get(var(r#"usart"#), text(r#"stopBits"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(1.0)],
                ),
            ),
        ],
    }
}
#[test]
#[ignore = "native peripheral implementation pending"]
fn case_010_should_return_1_when_usbs_0_native() {
    crate::run_native(case_010_should_return_1_when_usbs_0());
}

pub fn case_011_should_return_2_when_usbs_1() -> Case {
    Case {
        source: r#"src/peripherals/usart.spec.ts"#,
        name: r#"USART / stopBits / should return 2 when USBS = 1"#,
        line: 141,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                142,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                143,
                bind(
                    r#"usart"#,
                    new(
                        r#"AVRUSART"#,
                        vec![var(r#"cpu"#), var(r#"usart0Config"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                144,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UCSR0C"#), var(r#"USBS"#)],
                )),
            ),
            at(
                145,
                check(
                    get(var(r#"usart"#), text(r#"stopBits"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(2.0)],
                ),
            ),
        ],
    }
}
#[test]
#[ignore = "native peripheral implementation pending"]
fn case_011_should_return_2_when_usbs_1_native() {
    crate::run_native(case_011_should_return_2_when_usbs_1());
}

pub fn case_012_should_return_false_when_upm1_0() -> Case {
    Case {
        source: r#"src/peripherals/usart.spec.ts"#,
        name: r#"USART / parityEnabled / should return false when UPM1 = 0"#,
        line: 150,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                151,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                152,
                bind(
                    r#"usart"#,
                    new(
                        r#"AVRUSART"#,
                        vec![var(r#"cpu"#), var(r#"usart0Config"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                153,
                check(
                    get(var(r#"usart"#), text(r#"parityEnabled"#)),
                    r#"toEqual"#,
                    false,
                    vec![boolean(false)],
                ),
            ),
        ],
    }
}
#[test]
#[ignore = "native peripheral implementation pending"]
fn case_012_should_return_false_when_upm1_0_native() {
    crate::run_native(case_012_should_return_false_when_upm1_0());
}

pub fn case_013_should_return_true_when_upm1_1() -> Case {
    Case {
        source: r#"src/peripherals/usart.spec.ts"#,
        name: r#"USART / parityEnabled / should return true when UPM1 = 1"#,
        line: 156,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                157,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                158,
                bind(
                    r#"usart"#,
                    new(
                        r#"AVRUSART"#,
                        vec![var(r#"cpu"#), var(r#"usart0Config"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                159,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UCSR0C"#), var(r#"UPM1"#)],
                )),
            ),
            at(
                160,
                check(
                    get(var(r#"usart"#), text(r#"parityEnabled"#)),
                    r#"toEqual"#,
                    false,
                    vec![boolean(true)],
                ),
            ),
        ],
    }
}
#[test]
#[ignore = "native peripheral implementation pending"]
fn case_013_should_return_true_when_upm1_1_native() {
    crate::run_native(case_013_should_return_true_when_upm1_1());
}

pub fn case_014_should_return_false_when_upm0_0() -> Case {
    Case {
        source: r#"src/peripherals/usart.spec.ts"#,
        name: r#"USART / parityOdd / should return false when UPM0 = 0"#,
        line: 165,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                166,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                167,
                bind(
                    r#"usart"#,
                    new(
                        r#"AVRUSART"#,
                        vec![var(r#"cpu"#), var(r#"usart0Config"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                168,
                check(
                    get(var(r#"usart"#), text(r#"parityOdd"#)),
                    r#"toEqual"#,
                    false,
                    vec![boolean(false)],
                ),
            ),
        ],
    }
}
#[test]
#[ignore = "native peripheral implementation pending"]
fn case_014_should_return_false_when_upm0_0_native() {
    crate::run_native(case_014_should_return_false_when_upm0_0());
}

pub fn case_015_should_return_true_when_upm0_1() -> Case {
    Case {
        source: r#"src/peripherals/usart.spec.ts"#,
        name: r#"USART / parityOdd / should return true when UPM0 = 1"#,
        line: 171,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                172,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                173,
                bind(
                    r#"usart"#,
                    new(
                        r#"AVRUSART"#,
                        vec![var(r#"cpu"#), var(r#"usart0Config"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                174,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UCSR0C"#), var(r#"UPM0"#)],
                )),
            ),
            at(
                175,
                check(
                    get(var(r#"usart"#), text(r#"parityOdd"#)),
                    r#"toEqual"#,
                    false,
                    vec![boolean(true)],
                ),
            ),
        ],
    }
}
#[test]
#[ignore = "native peripheral implementation pending"]
fn case_015_should_return_true_when_upm0_1_native() {
    crate::run_native(case_015_should_return_true_when_upm0_1());
}

pub fn case_016_should_invoke_onbytetransmit_when_udr0_is_written_to() -> Case {
    Case {
        source: r#"src/peripherals/usart.spec.ts"#,
        name: r#"USART / should invoke onByteTransmit when UDR0 is written to"#,
        line: 179,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                180,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                181,
                bind(
                    r#"usart"#,
                    new(
                        r#"AVRUSART"#,
                        vec![var(r#"cpu"#), var(r#"usart0Config"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                182,
                eval(assign(
                    get(var(r#"usart"#), text(r#"onByteTransmit"#)),
                    call(get(var(r#"vi"#), text(r#"fn"#)), vec![]),
                    r#"="#,
                )),
            ),
            at(
                183,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UCSR0B"#), var(r#"TXEN"#)],
                )),
            ),
            at(
                184,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UDR0"#), num(97.0)],
                )),
            ),
            at(
                185,
                check(
                    get(var(r#"usart"#), text(r#"onByteTransmit"#)),
                    r#"toHaveBeenCalledWith"#,
                    false,
                    vec![num(97.0)],
                ),
            ),
        ],
    }
}
#[test]
#[ignore = "native peripheral implementation pending"]
fn case_016_should_invoke_onbytetransmit_when_udr0_is_written_to_native() {
    crate::run_native(case_016_should_invoke_onbytetransmit_when_udr0_is_written_to());
}

pub fn case_017_txenable_should_equal_true_when_the_transitter_is_enabled() -> Case {
    Case {
        source: r#"src/peripherals/usart.spec.ts"#,
        name: r#"USART / txEnable/rxEnable / txEnable should equal true when the transitter is enabled"#,
        line: 189,
        assertions: 2,
        setup: setup_0(),
        body: vec![
            at(
                190,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                191,
                bind(
                    r#"usart"#,
                    new(
                        r#"AVRUSART"#,
                        vec![var(r#"cpu"#), var(r#"usart0Config"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                192,
                eval(assign(
                    get(var(r#"usart"#), text(r#"onByteTransmit"#)),
                    call(get(var(r#"vi"#), text(r#"fn"#)), vec![]),
                    r#"="#,
                )),
            ),
            at(
                193,
                check(
                    get(var(r#"usart"#), text(r#"txEnable"#)),
                    r#"toEqual"#,
                    false,
                    vec![boolean(false)],
                ),
            ),
            at(
                194,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UCSR0B"#), var(r#"TXEN"#)],
                )),
            ),
            at(
                195,
                check(
                    get(var(r#"usart"#), text(r#"txEnable"#)),
                    r#"toEqual"#,
                    false,
                    vec![boolean(true)],
                ),
            ),
        ],
    }
}
#[test]
#[ignore = "native peripheral implementation pending"]
fn case_017_txenable_should_equal_true_when_the_transitter_is_enabled_native() {
    crate::run_native(case_017_txenable_should_equal_true_when_the_transitter_is_enabled());
}

pub fn case_018_rxenable_should_equal_true_when_the_transitter_is_enabled() -> Case {
    Case {
        source: r#"src/peripherals/usart.spec.ts"#,
        name: r#"USART / txEnable/rxEnable / rxEnable should equal true when the transitter is enabled"#,
        line: 198,
        assertions: 2,
        setup: setup_0(),
        body: vec![
            at(
                199,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                200,
                bind(
                    r#"usart"#,
                    new(
                        r#"AVRUSART"#,
                        vec![var(r#"cpu"#), var(r#"usart0Config"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                201,
                eval(assign(
                    get(var(r#"usart"#), text(r#"onByteTransmit"#)),
                    call(get(var(r#"vi"#), text(r#"fn"#)), vec![]),
                    r#"="#,
                )),
            ),
            at(
                202,
                check(
                    get(var(r#"usart"#), text(r#"rxEnable"#)),
                    r#"toEqual"#,
                    false,
                    vec![boolean(false)],
                ),
            ),
            at(
                203,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UCSR0B"#), var(r#"RXEN"#)],
                )),
            ),
            at(
                204,
                check(
                    get(var(r#"usart"#), text(r#"rxEnable"#)),
                    r#"toEqual"#,
                    false,
                    vec![boolean(true)],
                ),
            ),
        ],
    }
}
#[test]
#[ignore = "native peripheral implementation pending"]
fn case_018_rxenable_should_equal_true_when_the_transitter_is_enabled_native() {
    crate::run_native(case_018_rxenable_should_equal_true_when_the_transitter_is_enabled());
}

pub fn case_019_should_trigger_data_register_empty_interrupt_if_udre_is_set() -> Case {
    Case {
        source: r#"src/peripherals/usart.spec.ts"#,
        name: r#"USART / tick() / should trigger data register empty interrupt if UDRE is set"#,
        line: 209,
        assertions: 3,
        setup: setup_0(),
        body: vec![
            at(
                210,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                211,
                eval(new(
                    r#"AVRUSART"#,
                    vec![var(r#"cpu"#), var(r#"usart0Config"#), var(r#"FREQ_16MHZ"#)],
                )),
            ),
            at(
                212,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"UCSR0B"#),
                        binary(r#"|"#, var(r#"UDRIE"#), var(r#"TXEN"#)),
                    ],
                )),
            ),
            at(
                213,
                eval(assign(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"SREG"#)),
                    num(128.0),
                    r#"="#,
                )),
            ),
            at(214, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                215,
                check(
                    get(var(r#"cpu"#), text(r#"pc"#)),
                    r#"toEqual"#,
                    false,
                    vec![var(r#"PC_INT_UDRE"#)],
                ),
            ),
            at(
                216,
                check(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(2.0)],
                ),
            ),
            at(
                217,
                check(
                    binary(
                        r#"&"#,
                        get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"UCSR0A"#)),
                        var(r#"UDRE"#),
                    ),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
        ],
    }
}
#[test]
#[ignore = "native peripheral implementation pending"]
fn case_019_should_trigger_data_register_empty_interrupt_if_udre_is_set_native() {
    crate::run_native(case_019_should_trigger_data_register_empty_interrupt_if_udre_is_set());
}

pub fn case_020_should_trigger_data_tx_complete_interrupt_if_txcie_is_set() -> Case {
    Case {
        source: r#"src/peripherals/usart.spec.ts"#,
        name: r#"USART / tick() / should trigger data TX Complete interrupt if TXCIE is set"#,
        line: 220,
        assertions: 3,
        setup: setup_0(),
        body: vec![
            at(
                221,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                222,
                eval(new(
                    r#"AVRUSART"#,
                    vec![var(r#"cpu"#), var(r#"usart0Config"#), var(r#"FREQ_16MHZ"#)],
                )),
            ),
            at(
                223,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"UCSR0B"#),
                        binary(r#"|"#, var(r#"TXCIE"#), var(r#"TXEN"#)),
                    ],
                )),
            ),
            at(
                224,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UDR0"#), num(97.0)],
                )),
            ),
            at(
                225,
                eval(assign(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"SREG"#)),
                    num(128.0),
                    r#"="#,
                )),
            ),
            at(
                226,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(1000000.0),
                    r#"="#,
                )),
            ),
            at(227, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                228,
                check(
                    get(var(r#"cpu"#), text(r#"pc"#)),
                    r#"toEqual"#,
                    false,
                    vec![var(r#"PC_INT_TXC"#)],
                ),
            ),
            at(
                229,
                check(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    r#"toEqual"#,
                    false,
                    vec![binary(r#"+"#, num(1000000.0), num(2.0))],
                ),
            ),
            at(
                230,
                check(
                    binary(
                        r#"&"#,
                        get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"UCSR0A"#)),
                        var(r#"TXC"#),
                    ),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
        ],
    }
}
#[test]
#[ignore = "native peripheral implementation pending"]
fn case_020_should_trigger_data_tx_complete_interrupt_if_txcie_is_set_native() {
    crate::run_native(case_020_should_trigger_data_tx_complete_interrupt_if_txcie_is_set());
}

pub fn case_021_should_not_trigger_data_tx_complete_interrupt_if_udr_was_not_written_to() -> Case {
    Case {
        source: r#"src/peripherals/usart.spec.ts"#,
        name: r#"USART / tick() / should not trigger data TX Complete interrupt if UDR was not written to"#,
        line: 233,
        assertions: 2,
        setup: setup_0(),
        body: vec![
            at(
                234,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                235,
                eval(new(
                    r#"AVRUSART"#,
                    vec![var(r#"cpu"#), var(r#"usart0Config"#), var(r#"FREQ_16MHZ"#)],
                )),
            ),
            at(
                236,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"UCSR0B"#),
                        binary(r#"|"#, var(r#"TXCIE"#), var(r#"TXEN"#)),
                    ],
                )),
            ),
            at(
                237,
                eval(assign(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"SREG"#)),
                    num(128.0),
                    r#"="#,
                )),
            ),
            at(238, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                239,
                check(
                    get(var(r#"cpu"#), text(r#"pc"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
            at(
                240,
                check(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
        ],
    }
}
#[test]
#[ignore = "native peripheral implementation pending"]
fn case_021_should_not_trigger_data_tx_complete_interrupt_if_udr_was_not_written_to_native() {
    crate::run_native(
        case_021_should_not_trigger_data_tx_complete_interrupt_if_udr_was_not_written_to(),
    );
}

pub fn case_022_should_not_trigger_any_interrupt_if_interrupts_are_disabled() -> Case {
    Case {
        source: r#"src/peripherals/usart.spec.ts"#,
        name: r#"USART / tick() / should not trigger any interrupt if interrupts are disabled"#,
        line: 243,
        assertions: 3,
        setup: setup_0(),
        body: vec![
            at(
                244,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                245,
                eval(new(
                    r#"AVRUSART"#,
                    vec![var(r#"cpu"#), var(r#"usart0Config"#), var(r#"FREQ_16MHZ"#)],
                )),
            ),
            at(
                246,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![
                        var(r#"UCSR0B"#),
                        binary(r#"|"#, var(r#"UDRIE"#), var(r#"TXEN"#)),
                    ],
                )),
            ),
            at(
                247,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UDR0"#), num(97.0)],
                )),
            ),
            at(
                248,
                eval(assign(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"SREG"#)),
                    num(0.0),
                    r#"="#,
                )),
            ),
            at(
                249,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(1000000.0),
                    r#"="#,
                )),
            ),
            at(250, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                251,
                check(
                    get(var(r#"cpu"#), text(r#"pc"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
            at(
                252,
                check(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    r#"toEqual"#,
                    false,
                    vec![num(1000000.0)],
                ),
            ),
            at(
                253,
                check(
                    get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"UCSR0A"#)),
                    r#"toEqual"#,
                    false,
                    vec![binary(r#"|"#, var(r#"TXC"#), var(r#"UDRE"#))],
                ),
            ),
        ],
    }
}
#[test]
#[ignore = "native peripheral implementation pending"]
fn case_022_should_not_trigger_any_interrupt_if_interrupts_are_disabled_native() {
    crate::run_native(case_022_should_not_trigger_any_interrupt_if_interrupts_are_disabled());
}

pub fn case_023_should_call_onlinetransmit_with_the_current_line_buffer_after_every_newline() -> Case
{
    Case {
        source: r#"src/peripherals/usart.spec.ts"#,
        name: r#"USART / onLineTransmit / should call onLineTransmit with the current line buffer after every newline"#,
        line: 258,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                259,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                260,
                bind(
                    r#"usart"#,
                    new(
                        r#"AVRUSART"#,
                        vec![var(r#"cpu"#), var(r#"usart0Config"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                261,
                eval(assign(
                    get(var(r#"usart"#), text(r#"onLineTransmit"#)),
                    call(get(var(r#"vi"#), text(r#"fn"#)), vec![]),
                    r#"="#,
                )),
            ),
            at(
                262,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UCSR0B"#), var(r#"TXEN"#)],
                )),
            ),
            at(
                263,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UDR0"#), num(72.0)],
                )),
            ),
            at(
                264,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UDR0"#), num(101.0)],
                )),
            ),
            at(
                265,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UDR0"#), num(108.0)],
                )),
            ),
            at(
                266,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UDR0"#), num(108.0)],
                )),
            ),
            at(
                267,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UDR0"#), num(111.0)],
                )),
            ),
            at(
                268,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UDR0"#), num(10.0)],
                )),
            ),
            at(
                269,
                check(
                    get(var(r#"usart"#), text(r#"onLineTransmit"#)),
                    r#"toHaveBeenCalledWith"#,
                    false,
                    vec![text(r#"Hello"#)],
                ),
            ),
        ],
    }
}
#[test]
#[ignore = "native peripheral implementation pending"]
fn case_023_should_call_onlinetransmit_with_the_current_line_buffer_after_every_newline_native() {
    crate::run_native(
        case_023_should_call_onlinetransmit_with_the_current_line_buffer_after_every_newline(),
    );
}

pub fn case_024_should_not_call_onlinetransmit_if_no_newline_was_received() -> Case {
    Case {
        source: r#"src/peripherals/usart.spec.ts"#,
        name: r#"USART / onLineTransmit / should not call onLineTransmit if no newline was received"#,
        line: 272,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                273,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                274,
                bind(
                    r#"usart"#,
                    new(
                        r#"AVRUSART"#,
                        vec![var(r#"cpu"#), var(r#"usart0Config"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                275,
                eval(assign(
                    get(var(r#"usart"#), text(r#"onLineTransmit"#)),
                    call(get(var(r#"vi"#), text(r#"fn"#)), vec![]),
                    r#"="#,
                )),
            ),
            at(
                276,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UCSR0B"#), var(r#"TXEN"#)],
                )),
            ),
            at(
                277,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UDR0"#), num(72.0)],
                )),
            ),
            at(
                278,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UDR0"#), num(105.0)],
                )),
            ),
            at(
                279,
                check(
                    get(var(r#"usart"#), text(r#"onLineTransmit"#)),
                    r#"toHaveBeenCalled"#,
                    true,
                    vec![],
                ),
            ),
        ],
    }
}
#[test]
#[ignore = "native peripheral implementation pending"]
fn case_024_should_not_call_onlinetransmit_if_no_newline_was_received_native() {
    crate::run_native(case_024_should_not_call_onlinetransmit_if_no_newline_was_received());
}

pub fn case_025_should_clear_the_line_buffer_after_each_call_to_onlinetransmit() -> Case {
    Case {
        source: r#"src/peripherals/usart.spec.ts"#,
        name: r#"USART / onLineTransmit / should clear the line buffer after each call to onLineTransmit"#,
        line: 282,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                283,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                284,
                bind(
                    r#"usart"#,
                    new(
                        r#"AVRUSART"#,
                        vec![var(r#"cpu"#), var(r#"usart0Config"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                285,
                eval(assign(
                    get(var(r#"usart"#), text(r#"onLineTransmit"#)),
                    call(get(var(r#"vi"#), text(r#"fn"#)), vec![]),
                    r#"="#,
                )),
            ),
            at(
                286,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UCSR0B"#), var(r#"TXEN"#)],
                )),
            ),
            at(
                287,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UDR0"#), num(72.0)],
                )),
            ),
            at(
                288,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UDR0"#), num(105.0)],
                )),
            ),
            at(
                289,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UDR0"#), num(10.0)],
                )),
            ),
            at(
                290,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UDR0"#), num(116.0)],
                )),
            ),
            at(
                291,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UDR0"#), num(104.0)],
                )),
            ),
            at(
                292,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UDR0"#), num(101.0)],
                )),
            ),
            at(
                293,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UDR0"#), num(114.0)],
                )),
            ),
            at(
                294,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UDR0"#), num(101.0)],
                )),
            ),
            at(
                295,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UDR0"#), num(10.0)],
                )),
            ),
            at(
                296,
                check(
                    get(var(r#"usart"#), text(r#"onLineTransmit"#)),
                    r#"toHaveBeenCalledWith"#,
                    false,
                    vec![text(r#"there"#)],
                ),
            ),
        ],
    }
}
#[test]
#[ignore = "native peripheral implementation pending"]
fn case_025_should_clear_the_line_buffer_after_each_call_to_onlinetransmit_native() {
    crate::run_native(case_025_should_clear_the_line_buffer_after_each_call_to_onlinetransmit());
}

pub fn case_026_should_return_false_if_called_when_rx_is_busy() -> Case {
    Case {
        source: r#"src/peripherals/usart.spec.ts"#,
        name: r#"USART / writeByte / should return false if called when RX is busy"#,
        line: 301,
        assertions: 3,
        setup: setup_0(),
        body: vec![
            at(
                302,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                303,
                bind(
                    r#"usart"#,
                    new(
                        r#"AVRUSART"#,
                        vec![var(r#"cpu"#), var(r#"usart0Config"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                304,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UCSR0B"#), var(r#"RXEN"#)],
                )),
            ),
            at(
                305,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UBRR0L"#), num(103.0)],
                )),
            ),
            at(
                306,
                check(
                    call(get(var(r#"usart"#), text(r#"writeByte"#)), vec![num(10.0)]),
                    r#"toEqual"#,
                    false,
                    vec![boolean(true)],
                ),
            ),
            at(
                307,
                check(
                    call(get(var(r#"usart"#), text(r#"writeByte"#)), vec![num(10.0)]),
                    r#"toEqual"#,
                    false,
                    vec![boolean(false)],
                ),
            ),
            at(308, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                309,
                check(
                    call(get(var(r#"usart"#), text(r#"writeByte"#)), vec![num(10.0)]),
                    r#"toEqual"#,
                    false,
                    vec![boolean(false)],
                ),
            ),
        ],
    }
}
#[test]
#[ignore = "native peripheral implementation pending"]
fn case_026_should_return_false_if_called_when_rx_is_busy_native() {
    crate::run_native(case_026_should_return_false_if_called_when_rx_is_busy());
}

pub fn case_027_should_set_the_txc_bit_after_1_04ms_when_baud_rate_set_to_9600() -> Case {
    Case {
        source: r#"src/peripherals/usart.spec.ts"#,
        name: r#"USART / Integration tests / should set the TXC bit after ~1.04mS when baud rate set to 9600"#,
        line: 314,
        assertions: 2,
        setup: setup_0(),
        body: vec![
            at(
                315,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                316,
                eval(new(
                    r#"AVRUSART"#,
                    vec![var(r#"cpu"#), var(r#"usart0Config"#), var(r#"FREQ_16MHZ"#)],
                )),
            ),
            at(
                317,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UCSR0B"#), var(r#"TXEN"#)],
                )),
            ),
            at(
                318,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UBRR0L"#), num(103.0)],
                )),
            ),
            at(
                319,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UDR0"#), num(72.0)],
                )),
            ),
            at(
                320,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(16000.0),
                    r#"+="#,
                )),
            ),
            at(321, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                322,
                check(
                    binary(
                        r#"&"#,
                        get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"UCSR0A"#)),
                        var(r#"TXC"#),
                    ),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
            at(
                323,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(800.0),
                    r#"+="#,
                )),
            ),
            at(324, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                325,
                check(
                    binary(
                        r#"&"#,
                        get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"UCSR0A"#)),
                        var(r#"TXC"#),
                    ),
                    r#"toEqual"#,
                    false,
                    vec![var(r#"TXC"#)],
                ),
            ),
        ],
    }
}
#[test]
#[ignore = "native peripheral implementation pending"]
fn case_027_should_set_the_txc_bit_after_1_04ms_when_baud_rate_set_to_9600_native() {
    crate::run_native(case_027_should_set_the_txc_bit_after_1_04ms_when_baud_rate_set_to_9600());
}

pub fn case_028_should_be_ready_to_recieve_the_next_byte_after_1_04ms_when_baudrate_set_to_9600(
) -> Case {
    Case {
        source: r#"src/peripherals/usart.spec.ts"#,
        name: r#"USART / Integration tests / should be ready to recieve the next byte after ~1.04ms when baudrate set to 9600"#,
        line: 328,
        assertions: 9,
        setup: setup_0(),
        body: vec![
            at(
                329,
                bind(
                    r#"cpu"#,
                    new(r#"CPU"#, vec![new(r#"Uint16Array"#, vec![num(1024.0)])]),
                ),
            ),
            at(
                330,
                bind(
                    r#"usart"#,
                    new(
                        r#"AVRUSART"#,
                        vec![var(r#"cpu"#), var(r#"usart0Config"#), var(r#"FREQ_16MHZ"#)],
                    ),
                ),
            ),
            at(
                331,
                bind(
                    r#"rxCompleteCallback"#,
                    call(get(var(r#"vi"#), text(r#"fn"#)), vec![]),
                ),
            ),
            at(
                332,
                eval(assign(
                    get(var(r#"usart"#), text(r#"onRxComplete"#)),
                    var(r#"rxCompleteCallback"#),
                    r#"="#,
                )),
            ),
            at(
                333,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UCSR0B"#), var(r#"RXEN"#)],
                )),
            ),
            at(
                334,
                eval(call(
                    get(var(r#"cpu"#), text(r#"writeData"#)),
                    vec![var(r#"UBRR0L"#), num(103.0)],
                )),
            ),
            at(
                335,
                check(
                    call(get(var(r#"usart"#), text(r#"writeByte"#)), vec![num(66.0)]),
                    r#"toBe"#,
                    false,
                    vec![boolean(true)],
                ),
            ),
            at(
                336,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(16000.0),
                    r#"+="#,
                )),
            ),
            at(337, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                338,
                check(
                    binary(
                        r#"&"#,
                        get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"UCSR0A"#)),
                        var(r#"RXC"#),
                    ),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
            at(
                339,
                check(
                    get(var(r#"usart"#), text(r#"rxBusy"#)),
                    r#"toBe"#,
                    false,
                    vec![boolean(true)],
                ),
            ),
            at(
                340,
                check(
                    var(r#"rxCompleteCallback"#),
                    r#"toHaveBeenCalled"#,
                    true,
                    vec![],
                ),
            ),
            at(
                341,
                eval(assign(
                    get(var(r#"cpu"#), text(r#"cycles"#)),
                    num(800.0),
                    r#"+="#,
                )),
            ),
            at(342, eval(call(get(var(r#"cpu"#), text(r#"tick"#)), vec![]))),
            at(
                343,
                check(
                    binary(
                        r#"&"#,
                        get(get(var(r#"cpu"#), text(r#"data"#)), var(r#"UCSR0A"#)),
                        var(r#"RXC"#),
                    ),
                    r#"toEqual"#,
                    false,
                    vec![var(r#"RXC"#)],
                ),
            ),
            at(
                344,
                check(
                    get(var(r#"usart"#), text(r#"rxBusy"#)),
                    r#"toBe"#,
                    false,
                    vec![boolean(false)],
                ),
            ),
            at(
                345,
                check(
                    var(r#"rxCompleteCallback"#),
                    r#"toHaveBeenCalled"#,
                    false,
                    vec![],
                ),
            ),
            at(
                346,
                check(
                    call(
                        get(var(r#"cpu"#), text(r#"readData"#)),
                        vec![var(r#"UDR0"#)],
                    ),
                    r#"toEqual"#,
                    false,
                    vec![num(66.0)],
                ),
            ),
            at(
                347,
                check(
                    call(
                        get(var(r#"cpu"#), text(r#"readData"#)),
                        vec![var(r#"UDR0"#)],
                    ),
                    r#"toEqual"#,
                    false,
                    vec![num(0.0)],
                ),
            ),
        ],
    }
}
#[test]
#[ignore = "native peripheral implementation pending"]
fn case_028_should_be_ready_to_recieve_the_next_byte_after_1_04ms_when_baudrate_set_to_9600_native()
{
    crate::run_native(
        case_028_should_be_ready_to_recieve_the_next_byte_after_1_04ms_when_baudrate_set_to_9600(),
    );
}
