// SPDX-License-Identifier: MIT
// Copyright (c) Uri Shaked and contributors
// Generated by tools/convert.cjs. Source: src/utils/assembler.spec.ts
use crate::scenario::*;
pub const IMPORTS: &[&str] = &[r#"assemble"#];
pub fn cases() -> Vec<Case> {
    vec![
        case_001_should_assemble_add_instruction(),
        case_002_should_support_labels(),
        case_003_should_support_mutli_line_programs(),
        case_004_should_successfully_assemble_an_empty_program(),
        case_005_should_return_an_empty_byte_array_in_case_of_program_error(),
        case_006_should_correctly_assemble_adc_r0_r1(),
        case_007_should_correctly_assemble_bclr_2(),
        case_008_should_correctly_assemble_bld_r4_7(),
        case_009_should_correctly_assemble_brbc_0_8(),
        case_010_should_correctly_assemble_brbs_3_92(),
        case_011_should_correctly_assemble_brbs_3_4(),
        case_012_should_correctly_assemble_breq_with_forward_label_target(),
        case_013_should_correctly_assemble_brne_with_forward_label_target(),
        case_014_should_correctly_assemble_cbi_0xc_5(),
        case_015_should_correctly_assemble_call_0xb8(),
        case_016_should_correctly_assemble_cpc_r27_r18(),
        case_017_should_correctly_assemble_cpc_r24_r1(),
        case_018_should_correctly_assemble_cpi_r26_0x9(),
        case_019_should_correctly_assemble_cpse_r2_r3(),
        case_020_should_correctly_assemble_icall(),
        case_021_should_correctly_assemble_ijmp(),
        case_022_should_correctly_assemble_in_r5_0xb(),
        case_023_should_correctly_assemble_inc_r5(),
        case_024_should_correctly_assemble_jmp_0xb8(),
        case_025_should_correctly_assemble_lac_r19(),
        case_026_should_correctly_assemble_las_z_r17(),
        case_027_should_correctly_assemble_lat_z_r0(),
        case_028_should_correctly_assemble_ldi_r28_0xff(),
        case_029_should_correctly_assemble_lds_r5_0x150(),
        case_030_should_correctly_assemble_ld_r1_x(),
        case_031_should_correctly_assemble_ld_r17_x(),
        case_032_should_correctly_assemble_ld_r1_x(),
        case_033_should_correctly_assemble_ld_r8_y(),
        case_034_should_correctly_assemble_ld_r3_y(),
        case_035_should_correctly_assemble_ld_r0_y(),
        case_036_should_correctly_assemble_ldd_r4_y_2(),
        case_037_should_correctly_assemble_ld_r5_z(),
        case_038_should_correctly_assemble_ld_r7_z(),
        case_039_should_correctly_assemble_ld_r0_z(),
        case_040_should_correctly_assemble_ldd_r15_z_31(),
        case_041_should_correctly_assemble_lpm(),
        case_042_should_correctly_assemble_lpm_r2_z(),
        case_043_should_correctly_assemble_lpm_r1_z(),
        case_044_should_correctly_assemble_lsr_r7(),
        case_045_should_correctly_assemble_mov_r7_r8(),
        case_046_should_correctly_assemble_movw_r26_r22(),
        case_047_should_correctly_assemble_mul_r5_r6(),
        case_048_should_correctly_assemble_muls_r18_r19(),
        case_049_should_correctly_assemble_mulsu_r16_r17(),
        case_050_should_correctly_assemble_neg_r20(),
        case_051_should_correctly_assemble_nop(),
        case_052_should_correctly_assemble_or_r5_r2(),
        case_053_should_correctly_assemble_ori_r22_0x81(),
        case_054_should_correctly_assemble_out_0x3f_r1(),
        case_055_should_correctly_assemble_pop_r26(),
        case_056_should_correctly_assemble_push_r11(),
        case_057_should_correctly_assemble_rcall_6(),
        case_058_should_correctly_assemble_rcall_4(),
        case_059_should_correctly_assemble_ret(),
        case_060_should_correctly_assemble_reti(),
        case_061_should_correctly_assemble_rjmp_2(),
        case_062_should_correctly_assemble_ror_r0(),
        case_063_should_correctly_assemble_sbci_r23_3(),
        case_064_should_correctly_assemble_sbi_0x0c_5(),
        case_065_should_correctly_assemble_sbis_0x0c_5(),
        case_066_should_correctly_assemble_sbiw_r28_2(),
        case_067_should_correctly_assemble_sleep(),
        case_068_should_correctly_assemble_spm(),
        case_069_should_correctly_assemble_spm_z(),
        case_070_should_correctly_assemble_sts_0x151_r31(),
        case_071_should_correctly_assemble_st_x_r1(),
        case_072_should_correctly_assemble_st_x_r1(),
        case_073_should_correctly_assemble_st_x_r17(),
        case_074_should_correctly_assemble_st_y_r2(),
        case_075_should_correctly_assemble_st_y_r1(),
        case_076_should_correctly_assemble_st_y_r1(),
        case_077_should_correctly_assemble_std_y_17_r0(),
        case_078_should_correctly_assemble_st_z_r16(),
        case_079_should_correctly_assemble_st_z_r0(),
        case_080_should_correctly_assemble_st_z_r16(),
        case_081_should_correctly_assemble_std_z_1_r0(),
        case_082_should_correctly_assemble_swap_r1(),
        case_083_should_correctly_assemble_xch_z_r21(),
    ]
}

fn setup_0() -> Vec<Step> {
    vec![at(
        7,
        bind(
            r#"bytes"#,
            function(
                vec![param(r#"hex"#, false)],
                vec![
                    at(
                        8,
                        bind(
                            r#"result"#,
                            new(
                                r#"Uint8Array"#,
                                vec![binary(
                                    r#"/"#,
                                    get(var(r#"hex"#), text(r#"length"#)),
                                    num(2.0),
                                )],
                            ),
                        ),
                    ),
                    at(
                        9,
                        for_(
                            vec![at(9, bind(r#"i"#, num(0.0)))],
                            binary(r#"<"#, var(r#"i"#), get(var(r#"hex"#), text(r#"length"#))),
                            assign(var(r#"i"#), num(2.0), r#"+="#),
                            vec![at(
                                10,
                                eval(assign(
                                    get(var(r#"result"#), binary(r#"/"#, var(r#"i"#), num(2.0))),
                                    call(
                                        var(r#"parseInt"#),
                                        vec![
                                            call(
                                                get(var(r#"hex"#), text(r#"substr"#)),
                                                vec![var(r#"i"#), num(2.0)],
                                            ),
                                            num(16.0),
                                        ],
                                    ),
                                    r#"="#,
                                )),
                            )],
                        ),
                    ),
                    at(12, ret(var(r#"result"#))),
                ],
            ),
        ),
    )]
}

pub fn case_001_should_assemble_add_instruction() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should assemble ADD instruction"#,
        line: 16,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            17,
            check(
                call(var(r#"assemble"#), vec![text(r#"ADD r16, r11"#)]),
                r#"toEqual"#,
                false,
                vec![object(vec![
                    entry(r#"bytes"#, call(var(r#"bytes"#), vec![text(r#"0b0d"#)])),
                    entry(r#"errors"#, array(vec![])),
                    entry(
                        r#"lines"#,
                        array(vec![object(vec![
                            entry(r#"byteOffset"#, num(0.0)),
                            entry(r#"bytes"#, text(r#"0d0b"#)),
                            entry(r#"line"#, num(1.0)),
                            entry(r#"text"#, text(r#"ADD r16, r11"#)),
                        ])]),
                    ),
                    entry(r#"labels"#, object(vec![])),
                ])],
            ),
        )],
    }
}
#[test]
fn case_001_should_assemble_add_instruction_native() {
    crate::run_native(case_001_should_assemble_add_instruction());
}

pub fn case_002_should_support_labels() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should support labels"#,
        line: 25,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            26,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"loop: JMP loop"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"0c940000"#)])],
            ),
        )],
    }
}
#[test]
fn case_002_should_support_labels_native() {
    crate::run_native(case_002_should_support_labels());
}

pub fn case_003_should_support_mutli_line_programs() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should support mutli-line programs"#,
        line: 29,
        assertions: 1,
        setup: setup_0(),
        body: vec![
            at(
                30,
                bind(
                    r#"input"#,
                    text(
                        r#"
      start: 
      LDI r16, 15
      EOR r16, r0
      BREQ start
    "#,
                    ),
                ),
            ),
            at(
                36,
                check(
                    get(
                        call(var(r#"assemble"#), vec![var(r#"input"#)]),
                        text(r#"bytes"#),
                    ),
                    r#"toEqual"#,
                    false,
                    vec![call(var(r#"bytes"#), vec![text(r#"0fe00025e9f3"#)])],
                ),
            ),
        ],
    }
}
#[test]
fn case_003_should_support_mutli_line_programs_native() {
    crate::run_native(case_003_should_support_mutli_line_programs());
}

pub fn case_004_should_successfully_assemble_an_empty_program() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should successfully assemble an empty program"#,
        line: 39,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            40,
            check(
                call(var(r#"assemble"#), vec![text(r#""#)]),
                r#"toEqual"#,
                false,
                vec![object(vec![
                    entry(r#"bytes"#, new(r#"Uint8Array"#, vec![num(0.0)])),
                    entry(r#"errors"#, array(vec![])),
                    entry(r#"lines"#, array(vec![])),
                    entry(r#"labels"#, object(vec![])),
                ])],
            ),
        )],
    }
}
#[test]
fn case_004_should_successfully_assemble_an_empty_program_native() {
    crate::run_native(case_004_should_successfully_assemble_an_empty_program());
}

pub fn case_005_should_return_an_empty_byte_array_in_case_of_program_error() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should return an empty byte array in case of program error"#,
        line: 48,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            49,
            check(
                call(var(r#"assemble"#), vec![text(r#"LDI r15, 20"#)]),
                r#"toEqual"#,
                false,
                vec![object(vec![
                    entry(r#"bytes"#, new(r#"Uint8Array"#, vec![num(0.0)])),
                    entry(
                        r#"errors"#,
                        array(vec![text(r#"Line 0: Rd out of range: 16<>31"#)]),
                    ),
                    entry(r#"lines"#, array(vec![])),
                    entry(r#"labels"#, object(vec![])),
                ])],
            ),
        )],
    }
}
#[test]
fn case_005_should_return_an_empty_byte_array_in_case_of_program_error_native() {
    crate::run_native(case_005_should_return_an_empty_byte_array_in_case_of_program_error());
}

pub fn case_006_should_correctly_assemble_adc_r0_r1() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `ADC r0, r1`"#,
        line: 57,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            58,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"ADC r0, r1"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"011c"#)])],
            ),
        )],
    }
}
#[test]
fn case_006_should_correctly_assemble_adc_r0_r1_native() {
    crate::run_native(case_006_should_correctly_assemble_adc_r0_r1());
}

pub fn case_007_should_correctly_assemble_bclr_2() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `BCLR 2`"#,
        line: 61,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            62,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"BCLR 2"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"a894"#)])],
            ),
        )],
    }
}
#[test]
fn case_007_should_correctly_assemble_bclr_2_native() {
    crate::run_native(case_007_should_correctly_assemble_bclr_2());
}

pub fn case_008_should_correctly_assemble_bld_r4_7() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `BLD r4, 7`"#,
        line: 65,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            66,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"BLD r4, 7"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"47f8"#)])],
            ),
        )],
    }
}
#[test]
fn case_008_should_correctly_assemble_bld_r4_7_native() {
    crate::run_native(case_008_should_correctly_assemble_bld_r4_7());
}

pub fn case_009_should_correctly_assemble_brbc_0_8() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `BRBC 0, +8`"#,
        line: 69,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            70,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"BRBC 0, +8"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"20f4"#)])],
            ),
        )],
    }
}
#[test]
fn case_009_should_correctly_assemble_brbc_0_8_native() {
    crate::run_native(case_009_should_correctly_assemble_brbc_0_8());
}

pub fn case_010_should_correctly_assemble_brbs_3_92() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `BRBS 3, 92`"#,
        line: 73,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            74,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"BRBS 3, 92"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"73f1"#)])],
            ),
        )],
    }
}
#[test]
fn case_010_should_correctly_assemble_brbs_3_92_native() {
    crate::run_native(case_010_should_correctly_assemble_brbs_3_92());
}

pub fn case_011_should_correctly_assemble_brbs_3_4() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `BRBS 3, -4`"#,
        line: 77,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            78,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"BRBS 3, -4"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"f3f3"#)])],
            ),
        )],
    }
}
#[test]
fn case_011_should_correctly_assemble_brbs_3_4_native() {
    crate::run_native(case_011_should_correctly_assemble_brbs_3_4());
}

pub fn case_012_should_correctly_assemble_breq_with_forward_label_target() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble BREQ with forward label target"#,
        line: 81,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            82,
            check(
                get(
                    call(
                        var(r#"assemble"#),
                        vec![text(
                            r#"BREQ next 
 next:"#,
                        )],
                    ),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"01f0"#)])],
            ),
        )],
    }
}
#[test]
fn case_012_should_correctly_assemble_breq_with_forward_label_target_native() {
    crate::run_native(case_012_should_correctly_assemble_breq_with_forward_label_target());
}

pub fn case_013_should_correctly_assemble_brne_with_forward_label_target() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble BRNE with forward label target"#,
        line: 85,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            86,
            check(
                get(
                    call(
                        var(r#"assemble"#),
                        vec![text(
                            r#"BRNE next 
 next:"#,
                        )],
                    ),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"01f4"#)])],
            ),
        )],
    }
}
#[test]
fn case_013_should_correctly_assemble_brne_with_forward_label_target_native() {
    crate::run_native(case_013_should_correctly_assemble_brne_with_forward_label_target());
}

pub fn case_014_should_correctly_assemble_cbi_0xc_5() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `CBI 0xc, 5`"#,
        line: 89,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            90,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"CBI 0xc, 5"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"6598"#)])],
            ),
        )],
    }
}
#[test]
fn case_014_should_correctly_assemble_cbi_0xc_5_native() {
    crate::run_native(case_014_should_correctly_assemble_cbi_0xc_5());
}

pub fn case_015_should_correctly_assemble_call_0xb8() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `CALL 0xb8`"#,
        line: 93,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            94,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"CALL 0xb8"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"0e945c00"#)])],
            ),
        )],
    }
}
#[test]
fn case_015_should_correctly_assemble_call_0xb8_native() {
    crate::run_native(case_015_should_correctly_assemble_call_0xb8());
}

pub fn case_016_should_correctly_assemble_cpc_r27_r18() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `CPC r27, r18`"#,
        line: 97,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            98,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"CPC r27, r18"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"b207"#)])],
            ),
        )],
    }
}
#[test]
fn case_016_should_correctly_assemble_cpc_r27_r18_native() {
    crate::run_native(case_016_should_correctly_assemble_cpc_r27_r18());
}

pub fn case_017_should_correctly_assemble_cpc_r24_r1() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `CPC r24, r1`"#,
        line: 101,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            102,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"CPC r24, r1"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"8105"#)])],
            ),
        )],
    }
}
#[test]
fn case_017_should_correctly_assemble_cpc_r24_r1_native() {
    crate::run_native(case_017_should_correctly_assemble_cpc_r24_r1());
}

pub fn case_018_should_correctly_assemble_cpi_r26_0x9() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `CPI r26, 0x9`"#,
        line: 105,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            106,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"CPI r26, 0x9"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"a930"#)])],
            ),
        )],
    }
}
#[test]
fn case_018_should_correctly_assemble_cpi_r26_0x9_native() {
    crate::run_native(case_018_should_correctly_assemble_cpi_r26_0x9());
}

pub fn case_019_should_correctly_assemble_cpse_r2_r3() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `CPSE r2, r3`"#,
        line: 109,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            110,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"CPSE r2, r3`"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"2310"#)])],
            ),
        )],
    }
}
#[test]
fn case_019_should_correctly_assemble_cpse_r2_r3_native() {
    crate::run_native(case_019_should_correctly_assemble_cpse_r2_r3());
}

pub fn case_020_should_correctly_assemble_icall() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `ICALL`"#,
        line: 113,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            114,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"ICALL"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"0995"#)])],
            ),
        )],
    }
}
#[test]
fn case_020_should_correctly_assemble_icall_native() {
    crate::run_native(case_020_should_correctly_assemble_icall());
}

pub fn case_021_should_correctly_assemble_ijmp() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `IJMP`"#,
        line: 117,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            118,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"IJMP"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"0994"#)])],
            ),
        )],
    }
}
#[test]
fn case_021_should_correctly_assemble_ijmp_native() {
    crate::run_native(case_021_should_correctly_assemble_ijmp());
}

pub fn case_022_should_correctly_assemble_in_r5_0xb() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `IN r5, 0xb`"#,
        line: 121,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            122,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"IN r5, 0xb"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"5bb0"#)])],
            ),
        )],
    }
}
#[test]
fn case_022_should_correctly_assemble_in_r5_0xb_native() {
    crate::run_native(case_022_should_correctly_assemble_in_r5_0xb());
}

pub fn case_023_should_correctly_assemble_inc_r5() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `INC r5`"#,
        line: 125,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            126,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"INC r5"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"5394"#)])],
            ),
        )],
    }
}
#[test]
fn case_023_should_correctly_assemble_inc_r5_native() {
    crate::run_native(case_023_should_correctly_assemble_inc_r5());
}

pub fn case_024_should_correctly_assemble_jmp_0xb8() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `JMP 0xb8`"#,
        line: 129,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            130,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"JMP 0xb8"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"0c945c00"#)])],
            ),
        )],
    }
}
#[test]
fn case_024_should_correctly_assemble_jmp_0xb8_native() {
    crate::run_native(case_024_should_correctly_assemble_jmp_0xb8());
}

pub fn case_025_should_correctly_assemble_lac_r19() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `LAC r19`"#,
        line: 133,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            134,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"LAC Z, r19"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"3693"#)])],
            ),
        )],
    }
}
#[test]
fn case_025_should_correctly_assemble_lac_r19_native() {
    crate::run_native(case_025_should_correctly_assemble_lac_r19());
}

pub fn case_026_should_correctly_assemble_las_z_r17() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `LAS Z, r17`"#,
        line: 137,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            138,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"LAS Z, r17"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"1593"#)])],
            ),
        )],
    }
}
#[test]
fn case_026_should_correctly_assemble_las_z_r17_native() {
    crate::run_native(case_026_should_correctly_assemble_las_z_r17());
}

pub fn case_027_should_correctly_assemble_lat_z_r0() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `LAT Z, r0`"#,
        line: 141,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            142,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"LAT Z, r0"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"0792"#)])],
            ),
        )],
    }
}
#[test]
fn case_027_should_correctly_assemble_lat_z_r0_native() {
    crate::run_native(case_027_should_correctly_assemble_lat_z_r0());
}

pub fn case_028_should_correctly_assemble_ldi_r28_0xff() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `LDI r28, 0xff`"#,
        line: 145,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            146,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"LDI r28, 0xff"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"cfef"#)])],
            ),
        )],
    }
}
#[test]
fn case_028_should_correctly_assemble_ldi_r28_0xff_native() {
    crate::run_native(case_028_should_correctly_assemble_ldi_r28_0xff());
}

pub fn case_029_should_correctly_assemble_lds_r5_0x150() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `LDS r5, 0x150`"#,
        line: 149,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            150,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"LDS r5, 0x150"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"50905001"#)])],
            ),
        )],
    }
}
#[test]
fn case_029_should_correctly_assemble_lds_r5_0x150_native() {
    crate::run_native(case_029_should_correctly_assemble_lds_r5_0x150());
}

pub fn case_030_should_correctly_assemble_ld_r1_x() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `LD r1, X`"#,
        line: 153,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            154,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"LD r1, X"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"1c90"#)])],
            ),
        )],
    }
}
#[test]
fn case_030_should_correctly_assemble_ld_r1_x_native() {
    crate::run_native(case_030_should_correctly_assemble_ld_r1_x());
}

pub fn case_031_should_correctly_assemble_ld_r17_x() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `LD r17, X+`"#,
        line: 157,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            158,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"LD r17, X+"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"1d91"#)])],
            ),
        )],
    }
}
#[test]
fn case_031_should_correctly_assemble_ld_r17_x_native() {
    crate::run_native(case_031_should_correctly_assemble_ld_r17_x());
}

pub fn case_032_should_correctly_assemble_ld_r1_x() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `LD r1, -X`"#,
        line: 161,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            162,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"LD r1, -X"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"1e90"#)])],
            ),
        )],
    }
}
#[test]
fn case_032_should_correctly_assemble_ld_r1_x_native() {
    crate::run_native(case_032_should_correctly_assemble_ld_r1_x());
}

pub fn case_033_should_correctly_assemble_ld_r8_y() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `LD r8, Y`"#,
        line: 165,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            166,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"LD r8, Y"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"8880"#)])],
            ),
        )],
    }
}
#[test]
fn case_033_should_correctly_assemble_ld_r8_y_native() {
    crate::run_native(case_033_should_correctly_assemble_ld_r8_y());
}

pub fn case_034_should_correctly_assemble_ld_r3_y() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `LD r3, Y+`"#,
        line: 169,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            170,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"LD r3, Y+"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"3990"#)])],
            ),
        )],
    }
}
#[test]
fn case_034_should_correctly_assemble_ld_r3_y_native() {
    crate::run_native(case_034_should_correctly_assemble_ld_r3_y());
}

pub fn case_035_should_correctly_assemble_ld_r0_y() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `LD r0, -Y`"#,
        line: 173,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            174,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"LD r0, -Y"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"0a90"#)])],
            ),
        )],
    }
}
#[test]
fn case_035_should_correctly_assemble_ld_r0_y_native() {
    crate::run_native(case_035_should_correctly_assemble_ld_r0_y());
}

pub fn case_036_should_correctly_assemble_ldd_r4_y_2() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `LDD r4, Y+2`"#,
        line: 177,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            178,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"LDD r4, Y+2"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"4a80"#)])],
            ),
        )],
    }
}
#[test]
fn case_036_should_correctly_assemble_ldd_r4_y_2_native() {
    crate::run_native(case_036_should_correctly_assemble_ldd_r4_y_2());
}

pub fn case_037_should_correctly_assemble_ld_r5_z() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `LD r5, Z`"#,
        line: 181,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            182,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"LD r5, Z"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"5080"#)])],
            ),
        )],
    }
}
#[test]
fn case_037_should_correctly_assemble_ld_r5_z_native() {
    crate::run_native(case_037_should_correctly_assemble_ld_r5_z());
}

pub fn case_038_should_correctly_assemble_ld_r7_z() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `LD r7, Z+`"#,
        line: 185,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            186,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"LD r7, Z+"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"7190"#)])],
            ),
        )],
    }
}
#[test]
fn case_038_should_correctly_assemble_ld_r7_z_native() {
    crate::run_native(case_038_should_correctly_assemble_ld_r7_z());
}

pub fn case_039_should_correctly_assemble_ld_r0_z() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `LD r0, -Z`"#,
        line: 189,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            190,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"LD r0, -Z"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"0290"#)])],
            ),
        )],
    }
}
#[test]
fn case_039_should_correctly_assemble_ld_r0_z_native() {
    crate::run_native(case_039_should_correctly_assemble_ld_r0_z());
}

pub fn case_040_should_correctly_assemble_ldd_r15_z_31() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `LDD r15, Z+31`"#,
        line: 193,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            194,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"LDD r15, Z+31"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"f78c"#)])],
            ),
        )],
    }
}
#[test]
fn case_040_should_correctly_assemble_ldd_r15_z_31_native() {
    crate::run_native(case_040_should_correctly_assemble_ldd_r15_z_31());
}

pub fn case_041_should_correctly_assemble_lpm() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `LPM`"#,
        line: 197,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            198,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"LPM"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"c895"#)])],
            ),
        )],
    }
}
#[test]
fn case_041_should_correctly_assemble_lpm_native() {
    crate::run_native(case_041_should_correctly_assemble_lpm());
}

pub fn case_042_should_correctly_assemble_lpm_r2_z() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `LPM r2, Z`"#,
        line: 201,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            202,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"LPM r2, Z"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"2490"#)])],
            ),
        )],
    }
}
#[test]
fn case_042_should_correctly_assemble_lpm_r2_z_native() {
    crate::run_native(case_042_should_correctly_assemble_lpm_r2_z());
}

pub fn case_043_should_correctly_assemble_lpm_r1_z() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `LPM r1, Z+`"#,
        line: 205,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            206,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"LPM r1, Z+"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"1590"#)])],
            ),
        )],
    }
}
#[test]
fn case_043_should_correctly_assemble_lpm_r1_z_native() {
    crate::run_native(case_043_should_correctly_assemble_lpm_r1_z());
}

pub fn case_044_should_correctly_assemble_lsr_r7() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `LSR r7`"#,
        line: 209,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            210,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"LSR r7"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"7694"#)])],
            ),
        )],
    }
}
#[test]
fn case_044_should_correctly_assemble_lsr_r7_native() {
    crate::run_native(case_044_should_correctly_assemble_lsr_r7());
}

pub fn case_045_should_correctly_assemble_mov_r7_r8() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `MOV r7, r8`"#,
        line: 213,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            214,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"MOV r7, r8"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"782c"#)])],
            ),
        )],
    }
}
#[test]
fn case_045_should_correctly_assemble_mov_r7_r8_native() {
    crate::run_native(case_045_should_correctly_assemble_mov_r7_r8());
}

pub fn case_046_should_correctly_assemble_movw_r26_r22() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `MOVW r26, r22`"#,
        line: 217,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            218,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"MOVW r26, r22"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"db01"#)])],
            ),
        )],
    }
}
#[test]
fn case_046_should_correctly_assemble_movw_r26_r22_native() {
    crate::run_native(case_046_should_correctly_assemble_movw_r26_r22());
}

pub fn case_047_should_correctly_assemble_mul_r5_r6() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `MUL r5, r6`"#,
        line: 221,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            222,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"MUL r5, r6"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"569c"#)])],
            ),
        )],
    }
}
#[test]
fn case_047_should_correctly_assemble_mul_r5_r6_native() {
    crate::run_native(case_047_should_correctly_assemble_mul_r5_r6());
}

pub fn case_048_should_correctly_assemble_muls_r18_r19() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `MULS r18, r19`"#,
        line: 225,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            226,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"MULS r18, r19"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"2302"#)])],
            ),
        )],
    }
}
#[test]
fn case_048_should_correctly_assemble_muls_r18_r19_native() {
    crate::run_native(case_048_should_correctly_assemble_muls_r18_r19());
}

pub fn case_049_should_correctly_assemble_mulsu_r16_r17() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `MULSU r16, r17`"#,
        line: 229,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            230,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"MULSU r16, r17"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"0103"#)])],
            ),
        )],
    }
}
#[test]
fn case_049_should_correctly_assemble_mulsu_r16_r17_native() {
    crate::run_native(case_049_should_correctly_assemble_mulsu_r16_r17());
}

pub fn case_050_should_correctly_assemble_neg_r20() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `NEG r20`"#,
        line: 233,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            234,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"NEG r20"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"4195"#)])],
            ),
        )],
    }
}
#[test]
fn case_050_should_correctly_assemble_neg_r20_native() {
    crate::run_native(case_050_should_correctly_assemble_neg_r20());
}

pub fn case_051_should_correctly_assemble_nop() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `NOP`"#,
        line: 237,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            238,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"NOP"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"0000"#)])],
            ),
        )],
    }
}
#[test]
fn case_051_should_correctly_assemble_nop_native() {
    crate::run_native(case_051_should_correctly_assemble_nop());
}

pub fn case_052_should_correctly_assemble_or_r5_r2() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `OR r5, r2`"#,
        line: 241,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            242,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"OR r5, r2"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"5228"#)])],
            ),
        )],
    }
}
#[test]
fn case_052_should_correctly_assemble_or_r5_r2_native() {
    crate::run_native(case_052_should_correctly_assemble_or_r5_r2());
}

pub fn case_053_should_correctly_assemble_ori_r22_0x81() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `ORI r22, 0x81`"#,
        line: 245,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            246,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"ORI r22, 0x81"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"6168"#)])],
            ),
        )],
    }
}
#[test]
fn case_053_should_correctly_assemble_ori_r22_0x81_native() {
    crate::run_native(case_053_should_correctly_assemble_ori_r22_0x81());
}

pub fn case_054_should_correctly_assemble_out_0x3f_r1() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `OUT 0x3f, r1`"#,
        line: 249,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            250,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"OUT 0x3f, r1"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"1fbe"#)])],
            ),
        )],
    }
}
#[test]
fn case_054_should_correctly_assemble_out_0x3f_r1_native() {
    crate::run_native(case_054_should_correctly_assemble_out_0x3f_r1());
}

pub fn case_055_should_correctly_assemble_pop_r26() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `POP r26`"#,
        line: 253,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            254,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"POP r26"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"af91"#)])],
            ),
        )],
    }
}
#[test]
fn case_055_should_correctly_assemble_pop_r26_native() {
    crate::run_native(case_055_should_correctly_assemble_pop_r26());
}

pub fn case_056_should_correctly_assemble_push_r11() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `PUSH r11`"#,
        line: 257,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            258,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"PUSH r11"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"bf92"#)])],
            ),
        )],
    }
}
#[test]
fn case_056_should_correctly_assemble_push_r11_native() {
    crate::run_native(case_056_should_correctly_assemble_push_r11());
}

pub fn case_057_should_correctly_assemble_rcall_6() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `RCALL +6`"#,
        line: 261,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            262,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"RCALL +6"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"03d0"#)])],
            ),
        )],
    }
}
#[test]
fn case_057_should_correctly_assemble_rcall_6_native() {
    crate::run_native(case_057_should_correctly_assemble_rcall_6());
}

pub fn case_058_should_correctly_assemble_rcall_4() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `RCALL -4`"#,
        line: 265,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            266,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"RCALL -4"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"fedf"#)])],
            ),
        )],
    }
}
#[test]
fn case_058_should_correctly_assemble_rcall_4_native() {
    crate::run_native(case_058_should_correctly_assemble_rcall_4());
}

pub fn case_059_should_correctly_assemble_ret() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `RET`"#,
        line: 269,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            270,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"RET"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"0895"#)])],
            ),
        )],
    }
}
#[test]
fn case_059_should_correctly_assemble_ret_native() {
    crate::run_native(case_059_should_correctly_assemble_ret());
}

pub fn case_060_should_correctly_assemble_reti() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `RETI`"#,
        line: 273,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            274,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"RETI"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"1895"#)])],
            ),
        )],
    }
}
#[test]
fn case_060_should_correctly_assemble_reti_native() {
    crate::run_native(case_060_should_correctly_assemble_reti());
}

pub fn case_061_should_correctly_assemble_rjmp_2() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `RJMP 2`"#,
        line: 277,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            278,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"RJMP 2"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"01c0"#)])],
            ),
        )],
    }
}
#[test]
fn case_061_should_correctly_assemble_rjmp_2_native() {
    crate::run_native(case_061_should_correctly_assemble_rjmp_2());
}

pub fn case_062_should_correctly_assemble_ror_r0() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `ROR r0`"#,
        line: 281,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            282,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"ROR r0"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"0794"#)])],
            ),
        )],
    }
}
#[test]
fn case_062_should_correctly_assemble_ror_r0_native() {
    crate::run_native(case_062_should_correctly_assemble_ror_r0());
}

pub fn case_063_should_correctly_assemble_sbci_r23_3() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `SBCI r23, 3`"#,
        line: 285,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            286,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"SBCI r23, 3"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"7340"#)])],
            ),
        )],
    }
}
#[test]
fn case_063_should_correctly_assemble_sbci_r23_3_native() {
    crate::run_native(case_063_should_correctly_assemble_sbci_r23_3());
}

pub fn case_064_should_correctly_assemble_sbi_0x0c_5() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `SBI 0x0c, 5`"#,
        line: 289,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            290,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"SBI 0x0c, 5"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"659a"#)])],
            ),
        )],
    }
}
#[test]
fn case_064_should_correctly_assemble_sbi_0x0c_5_native() {
    crate::run_native(case_064_should_correctly_assemble_sbi_0x0c_5());
}

pub fn case_065_should_correctly_assemble_sbis_0x0c_5() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `SBIS 0x0c, 5`"#,
        line: 293,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            294,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"SBIS 0x0c, 5"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"659b"#)])],
            ),
        )],
    }
}
#[test]
fn case_065_should_correctly_assemble_sbis_0x0c_5_native() {
    crate::run_native(case_065_should_correctly_assemble_sbis_0x0c_5());
}

pub fn case_066_should_correctly_assemble_sbiw_r28_2() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `SBIW r28, 2`"#,
        line: 297,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            298,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"SBIW r28, 2"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"2297"#)])],
            ),
        )],
    }
}
#[test]
fn case_066_should_correctly_assemble_sbiw_r28_2_native() {
    crate::run_native(case_066_should_correctly_assemble_sbiw_r28_2());
}

pub fn case_067_should_correctly_assemble_sleep() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `SLEEP`"#,
        line: 301,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            302,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"SLEEP"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"8895"#)])],
            ),
        )],
    }
}
#[test]
fn case_067_should_correctly_assemble_sleep_native() {
    crate::run_native(case_067_should_correctly_assemble_sleep());
}

pub fn case_068_should_correctly_assemble_spm() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `SPM`"#,
        line: 305,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            306,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"SPM"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"e895"#)])],
            ),
        )],
    }
}
#[test]
fn case_068_should_correctly_assemble_spm_native() {
    crate::run_native(case_068_should_correctly_assemble_spm());
}

pub fn case_069_should_correctly_assemble_spm_z() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `SPM Z+`"#,
        line: 309,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            310,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"SPM Z+"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"f895"#)])],
            ),
        )],
    }
}
#[test]
fn case_069_should_correctly_assemble_spm_z_native() {
    crate::run_native(case_069_should_correctly_assemble_spm_z());
}

pub fn case_070_should_correctly_assemble_sts_0x151_r31() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `STS 0x151, r31`"#,
        line: 313,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            314,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"STS 0x151, r31"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"f0935101"#)])],
            ),
        )],
    }
}
#[test]
fn case_070_should_correctly_assemble_sts_0x151_r31_native() {
    crate::run_native(case_070_should_correctly_assemble_sts_0x151_r31());
}

pub fn case_071_should_correctly_assemble_st_x_r1() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `ST X, r1`"#,
        line: 317,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            318,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"ST X, r1"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"1c92"#)])],
            ),
        )],
    }
}
#[test]
fn case_071_should_correctly_assemble_st_x_r1_native() {
    crate::run_native(case_071_should_correctly_assemble_st_x_r1());
}

pub fn case_072_should_correctly_assemble_st_x_r1() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `ST X+, r1`"#,
        line: 321,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            322,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"ST X+, r1"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"1d92"#)])],
            ),
        )],
    }
}
#[test]
fn case_072_should_correctly_assemble_st_x_r1_native() {
    crate::run_native(case_072_should_correctly_assemble_st_x_r1());
}

pub fn case_073_should_correctly_assemble_st_x_r17() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `ST -X, r17`"#,
        line: 325,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            326,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"ST -X, r17"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"1e93"#)])],
            ),
        )],
    }
}
#[test]
fn case_073_should_correctly_assemble_st_x_r17_native() {
    crate::run_native(case_073_should_correctly_assemble_st_x_r17());
}

pub fn case_074_should_correctly_assemble_st_y_r2() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `ST Y, r2`"#,
        line: 329,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            330,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"ST Y, r2"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"2882"#)])],
            ),
        )],
    }
}
#[test]
fn case_074_should_correctly_assemble_st_y_r2_native() {
    crate::run_native(case_074_should_correctly_assemble_st_y_r2());
}

pub fn case_075_should_correctly_assemble_st_y_r1() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `ST Y+, r1`"#,
        line: 333,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            334,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"ST Y+, r1"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"1992"#)])],
            ),
        )],
    }
}
#[test]
fn case_075_should_correctly_assemble_st_y_r1_native() {
    crate::run_native(case_075_should_correctly_assemble_st_y_r1());
}

pub fn case_076_should_correctly_assemble_st_y_r1() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `ST -Y, r1`"#,
        line: 337,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            338,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"ST -Y, r1"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"1a92"#)])],
            ),
        )],
    }
}
#[test]
fn case_076_should_correctly_assemble_st_y_r1_native() {
    crate::run_native(case_076_should_correctly_assemble_st_y_r1());
}

pub fn case_077_should_correctly_assemble_std_y_17_r0() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `STD Y+17, r0`"#,
        line: 341,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            342,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"STD Y+17, r0"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"098a"#)])],
            ),
        )],
    }
}
#[test]
fn case_077_should_correctly_assemble_std_y_17_r0_native() {
    crate::run_native(case_077_should_correctly_assemble_std_y_17_r0());
}

pub fn case_078_should_correctly_assemble_st_z_r16() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `ST Z, r16`"#,
        line: 345,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            346,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"ST Z, r16"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"0083"#)])],
            ),
        )],
    }
}
#[test]
fn case_078_should_correctly_assemble_st_z_r16_native() {
    crate::run_native(case_078_should_correctly_assemble_st_z_r16());
}

pub fn case_079_should_correctly_assemble_st_z_r0() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `ST Z+, r0`"#,
        line: 349,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            350,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"ST Z+, r0"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"0192"#)])],
            ),
        )],
    }
}
#[test]
fn case_079_should_correctly_assemble_st_z_r0_native() {
    crate::run_native(case_079_should_correctly_assemble_st_z_r0());
}

pub fn case_080_should_correctly_assemble_st_z_r16() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `ST -Z, r16`"#,
        line: 353,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            354,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"ST -Z, r16"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"0293"#)])],
            ),
        )],
    }
}
#[test]
fn case_080_should_correctly_assemble_st_z_r16_native() {
    crate::run_native(case_080_should_correctly_assemble_st_z_r16());
}

pub fn case_081_should_correctly_assemble_std_z_1_r0() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `STD Z+1, r0`"#,
        line: 357,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            358,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"STD Z+1, r0"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"0182"#)])],
            ),
        )],
    }
}
#[test]
fn case_081_should_correctly_assemble_std_z_1_r0_native() {
    crate::run_native(case_081_should_correctly_assemble_std_z_1_r0());
}

pub fn case_082_should_correctly_assemble_swap_r1() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `SWAP r1`"#,
        line: 361,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            362,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"SWAP r1"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"1294"#)])],
            ),
        )],
    }
}
#[test]
fn case_082_should_correctly_assemble_swap_r1_native() {
    crate::run_native(case_082_should_correctly_assemble_swap_r1());
}

pub fn case_083_should_correctly_assemble_xch_z_r21() -> Case {
    Case {
        source: r#"src/utils/assembler.spec.ts"#,
        name: r#"AVR assembler / should correctly assemble `XCH Z, r21`"#,
        line: 365,
        assertions: 1,
        setup: setup_0(),
        body: vec![at(
            366,
            check(
                get(
                    call(var(r#"assemble"#), vec![text(r#"XCH Z, r21"#)]),
                    text(r#"bytes"#),
                ),
                r#"toEqual"#,
                false,
                vec![call(var(r#"bytes"#), vec![text(r#"5493"#)])],
            ),
        )],
    }
}
#[test]
fn case_083_should_correctly_assemble_xch_z_r21_native() {
    crate::run_native(case_083_should_correctly_assemble_xch_z_r21());
}
